// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Acknowledgement record for an alert instance.
type AlertAck struct {
	ID         string `json:"id"`
	InstanceID string `json:"instanceId"`
	AckBy      string `json:"ackBy"`
	AckAt      string `json:"ackAt"`
	Note       string `json:"note"`
}

// Structured condition payload stored on an alert rule.
type AlertCondition struct {
	Type      AlertConditionType `json:"type"`
	Threshold float64            `json:"threshold"`
	WindowSec *int               `json:"windowSec,omitempty"`
}

type AlertConditionInput struct {
	Type      AlertConditionType `json:"type"`
	Threshold float64            `json:"threshold"`
	WindowSec *int               `json:"windowSec,omitempty"`
}

type AlertHistoryFilterInput struct {
	RuleID *string     `json:"ruleId,omitempty"`
	State  *AlertState `json:"state,omitempty"`
	After  *string     `json:"after,omitempty"`
	Before *string     `json:"before,omitempty"`
	Limit  *int        `json:"limit,omitempty"`
	Offset *int        `json:"offset,omitempty"`
}

type AlertHistoryPage struct {
	Instances []*AlertInstance `json:"instances"`
	Total     int              `json:"total"`
}

// A single firing/acknowledged/resolved alert occurrence.
type AlertInstance struct {
	ID           string     `json:"id"`
	RuleID       string     `json:"ruleId"`
	Rule         *AlertRule `json:"rule,omitempty"`
	State        AlertState `json:"state"`
	DedupKey     string     `json:"dedupKey"`
	FiredAt      string     `json:"firedAt"`
	LastSeenAt   string     `json:"lastSeenAt"`
	ResolvedAt   *string    `json:"resolvedAt,omitempty"`
	CurrentValue *float64   `json:"currentValue,omitempty"`
	Message      string     `json:"message"`
	ContextJSON  string     `json:"contextJson"`
}

// A configured alert rule.
type AlertRule struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Condition   *AlertCondition `json:"condition"`
	Severity    AlertSeverity   `json:"severity"`
	Owner       string          `json:"owner"`
	IsPreset    bool            `json:"isPreset"`
	Enabled     bool            `json:"enabled"`
	CreatedAt   string          `json:"createdAt"`
	UpdatedAt   string          `json:"updatedAt"`
}

type AllocatedSlot struct {
	Index    int                         `json:"index"`
	JobID    string                      `json:"jobId"`
	Resource *TaskManagerResourceProfile `json:"resource"`
}

// A Flink application in the cluster→application→job hierarchy (Flink 2.3+, FLIP-549).
type Application struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	State string `json:"state"`
	// Epoch-millis timestamp the application started. Null when unknown.
	StartTime *string `json:"startTime,omitempty"`
	// Number of jobs belonging to this application.
	JobCount int `json:"jobCount"`
}

type BackPressureInfo struct {
	Status            string                 `json:"status"`
	BackpressureLevel string                 `json:"backpressureLevel"`
	EndTimestamp      string                 `json:"endTimestamp"`
	Subtasks          []*SubtaskBackPressure `json:"subtasks"`
}

type BlueGreenConfigDiff struct {
	BlueYaml  string `json:"blueYAML"`
	GreenYaml string `json:"greenYAML"`
}

type BlueGreenDeployment struct {
	Name                     string         `json:"name"`
	Namespace                string         `json:"namespace"`
	State                    BlueGreenState `json:"state"`
	JobStatus                *string        `json:"jobStatus,omitempty"`
	Error                    *string        `json:"error,omitempty"`
	LastReconciledTimestamp  *string        `json:"lastReconciledTimestamp,omitempty"`
	AbortTimestamp           *string        `json:"abortTimestamp,omitempty"`
	DeploymentReadyTimestamp *string        `json:"deploymentReadyTimestamp,omitempty"`
	BlueDeploymentName       *string        `json:"blueDeploymentName,omitempty"`
	GreenDeploymentName      *string        `json:"greenDeploymentName,omitempty"`
	ActiveJobID              *string        `json:"activeJobId,omitempty"`
	PendingJobID             *string        `json:"pendingJobId,omitempty"`
	AbortGracePeriod         *string        `json:"abortGracePeriod,omitempty"`
	DeploymentDeletionDelay  *string        `json:"deploymentDeletionDelay,omitempty"`
}

type CancelApplicationResult struct {
	Success bool `json:"success"`
}

type CancelJobResult struct {
	Success bool `json:"success"`
}

type CatalogDatabase struct {
	Name string `json:"name"`
}

type CatalogInfo struct {
	Name          string         `json:"name"`
	Source        string         `json:"source"`
	ConnectorType string         `json:"connectorType"`
	Properties    map[string]any `json:"properties,omitempty"`
	DatabaseCount int            `json:"databaseCount"`
	TableCount    int            `json:"tableCount"`
}

type CatalogTable struct {
	Name string `json:"name"`
}

type CheckpointConfig struct {
	Mode                             string `json:"mode"`
	Interval                         string `json:"interval"`
	Timeout                          string `json:"timeout"`
	MinPause                         string `json:"minPause"`
	MaxConcurrent                    int    `json:"maxConcurrent"`
	ExternalizedEnabled              bool   `json:"externalizedEnabled"`
	ExternalizedDeleteOnCancellation bool   `json:"externalizedDeleteOnCancellation"`
	UnalignedCheckpoints             bool   `json:"unalignedCheckpoints"`
	// State backend class name, e.g. HashMapStateBackend. Absent on older Flink.
	StateBackend *string `json:"stateBackend,omitempty"`
	// Checkpoint storage, e.g. FileSystemCheckpointStorage. Absent on older Flink.
	CheckpointStorage           *string `json:"checkpointStorage,omitempty"`
	TolerableFailedCheckpoints  *int    `json:"tolerableFailedCheckpoints,omitempty"`
	AlignedCheckpointTimeout    *string `json:"alignedCheckpointTimeout,omitempty"`
	CheckpointsAfterTasksFinish *bool   `json:"checkpointsAfterTasksFinish,omitempty"`
}

type CheckpointCounts struct {
	Completed  int `json:"completed"`
	InProgress int `json:"inProgress"`
	Failed     int `json:"failed"`
	Total      int `json:"total"`
	Restored   int `json:"restored"`
}

// Full detail for a single checkpoint
// (GET /jobs/:jid/checkpoints/details/:checkpointid).
type CheckpointDetail struct {
	ID          string `json:"id"`
	Status      string `json:"status"`
	IsSavepoint bool   `json:"isSavepoint"`
	// CHECKPOINT, UNALIGNED_CHECKPOINT, SAVEPOINT, or SYNC_SAVEPOINT.
	CheckpointType          *string `json:"checkpointType,omitempty"`
	TriggerTimestamp        string  `json:"triggerTimestamp"`
	LatestAckTimestamp      string  `json:"latestAckTimestamp"`
	StateSize               string  `json:"stateSize"`
	EndToEndDuration        string  `json:"endToEndDuration"`
	NumSubtasks             int     `json:"numSubtasks"`
	NumAcknowledgedSubtasks int     `json:"numAcknowledgedSubtasks"`
	CheckpointedSize        *string `json:"checkpointedSize,omitempty"`
	ProcessedData           *string `json:"processedData,omitempty"`
	PersistedData           *string `json:"persistedData,omitempty"`
	// Restore location. Null unless the checkpoint is externally addressable.
	ExternalPath *string `json:"externalPath,omitempty"`
	Discarded    *bool   `json:"discarded,omitempty"`
	// Failure reason. Null unless status is FAILED.
	FailureMessage *string `json:"failureMessage,omitempty"`
	// Failure time (epoch millis). Null unless status is FAILED.
	FailureTimestamp *string                 `json:"failureTimestamp,omitempty"`
	Tasks            []*CheckpointTaskDetail `json:"tasks"`
}

// Connection type for paginated checkpoint history results.
type CheckpointHistoryConnection struct {
	// List of checkpoint history edges.
	Edges []*CheckpointHistoryEdge `json:"edges"`
	// Pagination metadata.
	PageInfo *CheckpointHistoryPageInfo `json:"pageInfo"`
}

// A single edge in the checkpoint history connection.
type CheckpointHistoryEdge struct {
	// The checkpoint record.
	Node *StoredCheckpoint `json:"node"`
	// Opaque cursor for this edge.
	Cursor string `json:"cursor"`
}

type CheckpointHistoryEntry struct {
	ID          string `json:"id"`
	Status      string `json:"status"`
	IsSavepoint bool   `json:"isSavepoint"`
	// CHECKPOINT, UNALIGNED_CHECKPOINT, SAVEPOINT, or SYNC_SAVEPOINT.
	CheckpointType          *string `json:"checkpointType,omitempty"`
	TriggerTimestamp        string  `json:"triggerTimestamp"`
	LatestAckTimestamp      string  `json:"latestAckTimestamp"`
	StateSize               string  `json:"stateSize"`
	EndToEndDuration        string  `json:"endToEndDuration"`
	ProcessedData           string  `json:"processedData"`
	PersistedData           string  `json:"persistedData"`
	NumSubtasks             int     `json:"numSubtasks"`
	NumAcknowledgedSubtasks int     `json:"numAcknowledgedSubtasks"`
	CheckpointedSize        *string `json:"checkpointedSize,omitempty"`
	// Restore location. Null unless the checkpoint is externally addressable.
	ExternalPath *string `json:"externalPath,omitempty"`
	// Failure reason. Null unless status is FAILED.
	FailureMessage *string `json:"failureMessage,omitempty"`
	// Failure time (epoch millis). Null unless status is FAILED.
	FailureTimestamp *string `json:"failureTimestamp,omitempty"`
}

// Filter criteria for historical checkpoint queries.
type CheckpointHistoryFilter struct {
	// Filter by cluster name.
	ClusterID *string `json:"clusterID,omitempty"`
	// Filter by job ID.
	JobID *string `json:"jobID,omitempty"`
	// Filter by checkpoint status (e.g. COMPLETED, FAILED, IN_PROGRESS).
	Status *string `json:"status,omitempty"`
	// Filter to savepoints only.
	IsSavepoint *bool `json:"isSavepoint,omitempty"`
	// Return only checkpoints with trigger_timestamp >= this timestamp.
	After *string `json:"after,omitempty"`
	// Return only checkpoints with trigger_timestamp <= this timestamp.
	Before *string `json:"before,omitempty"`
}

// Page info for checkpoint history pagination.
type CheckpointHistoryPageInfo struct {
	// Whether there are more pages after this one.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor for fetching the next page.
	EndCursor *string `json:"endCursor,omitempty"`
}

type CheckpointLatest struct {
	Completed *CheckpointHistoryEntry `json:"completed,omitempty"`
	Failed    *CheckpointHistoryEntry `json:"failed,omitempty"`
	Savepoint *CheckpointHistoryEntry `json:"savepoint,omitempty"`
	Restored  *CheckpointRestoredInfo `json:"restored,omitempty"`
}

type CheckpointMinMaxAvg struct {
	Min string `json:"min"`
	Max string `json:"max"`
	Avg string `json:"avg"`
}

type CheckpointRestoredInfo struct {
	ID               string  `json:"id"`
	RestoreTimestamp string  `json:"restoreTimestamp"`
	IsSavepoint      bool    `json:"isSavepoint"`
	ExternalPath     *string `json:"externalPath,omitempty"`
}

type CheckpointStats struct {
	Counts  *CheckpointCounts         `json:"counts"`
	History []*CheckpointHistoryEntry `json:"history"`
	Summary *CheckpointSummary        `json:"summary,omitempty"`
	Latest  *CheckpointLatest         `json:"latest,omitempty"`
}

// One subtask's checkpoint stats. Subtasks that have not acknowledged carry
// only index and status.
type CheckpointSubtaskEntry struct {
	Index               int     `json:"index"`
	Status              string  `json:"status"`
	AckTimestamp        *string `json:"ackTimestamp,omitempty"`
	EndToEndDuration    *string `json:"endToEndDuration,omitempty"`
	StateSize           *string `json:"stateSize,omitempty"`
	CheckpointedSize    *string `json:"checkpointedSize,omitempty"`
	SyncDuration        *string `json:"syncDuration,omitempty"`
	AsyncDuration       *string `json:"asyncDuration,omitempty"`
	AlignmentBuffered   *string `json:"alignmentBuffered,omitempty"`
	AlignmentProcessed  *string `json:"alignmentProcessed,omitempty"`
	AlignmentPersisted  *string `json:"alignmentPersisted,omitempty"`
	AlignmentDuration   *string `json:"alignmentDuration,omitempty"`
	StartDelay          *string `json:"startDelay,omitempty"`
	UnalignedCheckpoint *bool   `json:"unalignedCheckpoint,omitempty"`
	Aborted             *bool   `json:"aborted,omitempty"`
}

// Per-subtask checkpoint stats for one vertex of a checkpoint
// (GET /jobs/:jid/checkpoints/details/:checkpointid/subtasks/:vertexid).
type CheckpointSubtaskStats struct {
	VertexID                string                    `json:"vertexId"`
	Status                  string                    `json:"status"`
	LatestAckTimestamp      string                    `json:"latestAckTimestamp"`
	StateSize               string                    `json:"stateSize"`
	EndToEndDuration        string                    `json:"endToEndDuration"`
	NumSubtasks             int                       `json:"numSubtasks"`
	NumAcknowledgedSubtasks int                       `json:"numAcknowledgedSubtasks"`
	Summary                 *CheckpointSubtaskSummary `json:"summary,omitempty"`
	Subtasks                []*CheckpointSubtaskEntry `json:"subtasks"`
}

// Min/avg/max rollups for one vertex's subtask checkpoint stats.
type CheckpointSubtaskSummary struct {
	StateSize          *CheckpointMinMaxAvg `json:"stateSize,omitempty"`
	EndToEndDuration   *CheckpointMinMaxAvg `json:"endToEndDuration,omitempty"`
	CheckpointedSize   *CheckpointMinMaxAvg `json:"checkpointedSize,omitempty"`
	SyncDuration       *CheckpointMinMaxAvg `json:"syncDuration,omitempty"`
	AsyncDuration      *CheckpointMinMaxAvg `json:"asyncDuration,omitempty"`
	AlignmentBuffered  *CheckpointMinMaxAvg `json:"alignmentBuffered,omitempty"`
	AlignmentProcessed *CheckpointMinMaxAvg `json:"alignmentProcessed,omitempty"`
	AlignmentPersisted *CheckpointMinMaxAvg `json:"alignmentPersisted,omitempty"`
	AlignmentDuration  *CheckpointMinMaxAvg `json:"alignmentDuration,omitempty"`
	StartDelay         *CheckpointMinMaxAvg `json:"startDelay,omitempty"`
}

type CheckpointSummary struct {
	StateSize        *CheckpointMinMaxAvg `json:"stateSize,omitempty"`
	EndToEndDuration *CheckpointMinMaxAvg `json:"endToEndDuration,omitempty"`
	CheckpointedSize *CheckpointMinMaxAvg `json:"checkpointedSize,omitempty"`
	ProcessedData    *CheckpointMinMaxAvg `json:"processedData,omitempty"`
	PersistedData    *CheckpointMinMaxAvg `json:"persistedData,omitempty"`
}

// Per-vertex rollup within a checkpoint detail, keyed by the job vertex.
type CheckpointTaskDetail struct {
	VertexID                string  `json:"vertexId"`
	Status                  string  `json:"status"`
	LatestAckTimestamp      string  `json:"latestAckTimestamp"`
	StateSize               string  `json:"stateSize"`
	EndToEndDuration        string  `json:"endToEndDuration"`
	NumSubtasks             int     `json:"numSubtasks"`
	NumAcknowledgedSubtasks int     `json:"numAcknowledgedSubtasks"`
	CheckpointedSize        *string `json:"checkpointedSize,omitempty"`
	ProcessedData           *string `json:"processedData,omitempty"`
	PersistedData           *string `json:"persistedData,omitempty"`
}

// Information about a registered Flink cluster connection.
type ClusterInfo struct {
	Name          string        `json:"name"`
	URL           string        `json:"url"`
	Status        ClusterStatus `json:"status"`
	LastCheckTime *string       `json:"lastCheckTime,omitempty"`
	Version       *string       `json:"version,omitempty"`
	Capabilities  []string      `json:"capabilities"`
}

// A cluster overview snapshot capturing capacity and job counts at a point in time.
type ClusterOverviewSnapshot struct {
	// Cluster name.
	Cluster string `json:"cluster"`
	// Flink version string.
	FlinkVersion string `json:"flinkVersion"`
	// Total task slots.
	SlotsTotal int `json:"slotsTotal"`
	// Available (free) task slots.
	SlotsAvailable int `json:"slotsAvailable"`
	// Number of running jobs.
	JobsRunning int `json:"jobsRunning"`
	// Number of finished jobs.
	JobsFinished int `json:"jobsFinished"`
	// Number of cancelled jobs.
	JobsCancelled int `json:"jobsCancelled"`
	// Number of failed jobs.
	JobsFailed int `json:"jobsFailed"`
	// Number of task managers.
	TaskManagers int `json:"taskManagers"`
	// When this snapshot was captured (RFC3339).
	CapturedAt string `json:"capturedAt"`
}

type ColumnInfo struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type CompatibilityIssue struct {
	OperatorKey string `json:"operatorKey"`
	Component   string `json:"component"`
	// MAX_PARALLELISM | UNMAPPED_STATE | SERIALIZER | SCHEMA_EVOLUTION
	Category string        `json:"category"`
	Severity IssueSeverity `json:"severity"`
	Message  string        `json:"message"`
}

type CompatibilityReport struct {
	Pipeline    string                `json:"pipeline"`
	Environment string                `json:"environment"`
	Verdict     CompatibilityVerdict  `json:"verdict"`
	CanProceed  bool                  `json:"canProceed"`
	Issues      []*CompatibilityIssue `json:"issues"`
	// ISO timestamp; null for a non-persisted preview.
	CheckedAt *string `json:"checkedAt,omitempty"`
	// Set when the check was persisted.
	CheckID *string `json:"checkId,omitempty"`
}

// The result of a compatibility check. `messages` describes incompatibilities
// when `isCompatible` is false; empty otherwise.
type CompatibilityResult struct {
	IsCompatible bool     `json:"isCompatible"`
	Messages     []string `json:"messages"`
}

type ConfigEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// I/O throughput metrics for a connector
type ConnectorMetrics struct {
	// Records read (for sources)
	RecordsRead string `json:"recordsRead"`
	// Records written (for sinks)
	RecordsWritten string `json:"recordsWritten"`
	// Bytes read
	BytesRead string `json:"bytesRead"`
	// Bytes written
	BytesWritten string `json:"bytesWritten"`
}

type CreateAlertRuleInput struct {
	Name        string               `json:"name"`
	Description *string              `json:"description,omitempty"`
	Condition   *AlertConditionInput `json:"condition"`
	Severity    AlertSeverity        `json:"severity"`
	Owner       *string              `json:"owner,omitempty"`
	Enabled     *bool                `json:"enabled,omitempty"`
}

type DashboardConfig struct {
	Clusters    []string `json:"clusters"`
	Instruments []string `json:"instruments"`
}

// A column in a database table.
type DatabaseColumn struct {
	Name         string `json:"name"`
	DataType     string `json:"dataType"`
	Nullable     bool   `json:"nullable"`
	DefaultValue string `json:"defaultValue"`
	IsPrimaryKey bool   `json:"isPrimaryKey"`
	Comment      string `json:"comment"`
}

// A constraint on a database table.
type DatabaseConstraint struct {
	Name       string   `json:"name"`
	Type       string   `json:"type"`
	Columns    []string `json:"columns"`
	RefTable   string   `json:"refTable"`
	RefColumns []string `json:"refColumns"`
}

// An index on a database table.
type DatabaseIndex struct {
	Name    string   `json:"name"`
	Columns []string `json:"columns"`
	Unique  bool     `json:"unique"`
	Type    string   `json:"type"`
}

// A recorded query execution in the history.
type DatabaseQueryHistoryEntry struct {
	SQL             string  `json:"sql"`
	ExecutedAt      string  `json:"executedAt"`
	ExecutionTimeMs int     `json:"executionTimeMs"`
	RowCount        int     `json:"rowCount"`
	Error           *string `json:"error,omitempty"`
}

// Result of executing a database query.
type DatabaseQueryResult struct {
	Columns         []*DatabaseResultColumn `json:"columns"`
	Rows            [][]map[string]any      `json:"rows"`
	RowCount        int                     `json:"rowCount"`
	ExecutionTimeMs int                     `json:"executionTimeMs"`
	Truncated       bool                    `json:"truncated"`
}

// A column in a query result set.
type DatabaseResultColumn struct {
	Name     string `json:"name"`
	DataType string `json:"dataType"`
}

// A database schema (e.g., public, analytics).
type DatabaseSchema struct {
	Name       string `json:"name"`
	TableCount int    `json:"tableCount"`
}

// Detailed information about a database table.
type DatabaseTableDetail struct {
	Name        string                `json:"name"`
	Schema      string                `json:"schema"`
	Columns     []*DatabaseColumn     `json:"columns"`
	Indexes     []*DatabaseIndex      `json:"indexes"`
	Constraints []*DatabaseConstraint `json:"constraints"`
}

// Summary of a database table within a schema.
type DatabaseTableSummary struct {
	Name             string `json:"name"`
	Schema           string `json:"schema"`
	Type             string `json:"type"`
	RowCountEstimate int    `json:"rowCountEstimate"`
}

type DeleteResult struct {
	Success bool `json:"success"`
}

type ExceptionEntry struct {
	ExceptionName string  `json:"exceptionName"`
	Stacktrace    string  `json:"stacktrace"`
	Timestamp     string  `json:"timestamp"`
	TaskName      *string `json:"taskName,omitempty"`
	Endpoint      *string `json:"endpoint,omitempty"`
	TaskManagerID *string `json:"taskManagerId,omitempty"`
}

// Connection type for paginated exception history results.
type ExceptionHistoryConnection struct {
	// List of exception history edges.
	Edges []*ExceptionHistoryEdge `json:"edges"`
	// Pagination metadata.
	PageInfo *ExceptionHistoryPageInfo `json:"pageInfo"`
}

// A single edge in the exception history connection.
type ExceptionHistoryEdge struct {
	// The exception record.
	Node *StoredException `json:"node"`
	// Opaque cursor for this edge.
	Cursor string `json:"cursor"`
}

// Filter criteria for historical exception queries.
type ExceptionHistoryFilter struct {
	// Filter by cluster name.
	ClusterID *string `json:"clusterID,omitempty"`
	// Filter by job ID.
	JobID *string `json:"jobID,omitempty"`
	// Filter by exception name (case-insensitive substring match).
	ExceptionName *string `json:"exceptionName,omitempty"`
	// Return only exceptions with timestamp >= this timestamp.
	After *string `json:"after,omitempty"`
	// Return only exceptions with timestamp <= this timestamp.
	Before *string `json:"before,omitempty"`
}

// Page info for exception history pagination.
type ExceptionHistoryPageInfo struct {
	// Whether there are more pages after this one.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor for fetching the next page.
	EndCursor *string `json:"endCursor,omitempty"`
}

type Flamegraph struct {
	EndTimestamp string          `json:"endTimestamp"`
	Data         *FlamegraphNode `json:"data"`
}

type FlamegraphNode struct {
	Name     string            `json:"name"`
	Value    string            `json:"value"`
	Children []*FlamegraphNode `json:"children,omitempty"`
}

type FlinkConfig struct {
	RefreshInterval int            `json:"refreshInterval"`
	TimezoneName    string         `json:"timezoneName"`
	TimezoneOffset  string         `json:"timezoneOffset"`
	FlinkVersion    string         `json:"flinkVersion"`
	FlinkRevision   string         `json:"flinkRevision"`
	Features        *FlinkFeatures `json:"features"`
}

type FlinkFeatures struct {
	WebSubmit  bool `json:"webSubmit"`
	WebCancel  bool `json:"webCancel"`
	WebRescale bool `json:"webRescale"`
	WebHistory bool `json:"webHistory"`
}

// Fields of a single column in a Fluss table schema.
type FlussSchemaField struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Nullable bool   `json:"nullable"`
	Comment  string `json:"comment"`
}

// Full metadata for a single Fluss table — schema, bucket configuration,
// connector properties, last-update timestamp.
type FlussTableMetadata struct {
	Database      string              `json:"database"`
	Name          string              `json:"name"`
	TableType     string              `json:"tableType"`
	BucketCount   int                 `json:"bucketCount"`
	BucketKey     []string            `json:"bucketKey"`
	PrimaryKey    []string            `json:"primaryKey"`
	Schema        []*FlussSchemaField `json:"schema"`
	Properties    map[string]any      `json:"properties"`
	Comment       string              `json:"comment"`
	LastUpdatedMs int                 `json:"lastUpdatedMs"`
}

// A Fluss table at the summary granularity returned by `flussTables`.
// The `tableType` is either "PrimaryKey" (KV-style upsert) or "Log" (append-only).
type FlussTableSummary struct {
	Database      string   `json:"database"`
	Name          string   `json:"name"`
	TableType     string   `json:"tableType"`
	BucketCount   int      `json:"bucketCount"`
	BucketKey     []string `json:"bucketKey"`
	PrimaryKey    []string `json:"primaryKey"`
	LastUpdatedMs int      `json:"lastUpdatedMs"`
}

// Health of a single TabletServer in the Fluss cluster. `leadership` is the
// number of bucket leaderships the server currently holds.
type FlussTabletServerHealth struct {
	Server     string `json:"server"`
	Alive      bool   `json:"alive"`
	Leadership int    `json:"leadership"`
}

// High-availability status derived from the cluster config (observe-only).
type HAStatus struct {
	// True when HA is configured (type is neither none nor empty).
	Enabled bool `json:"enabled"`
	// HA type/mode: NONE, zookeeper, or kubernetes (raw value from config).
	Mode string `json:"mode"`
	// HA storage directory (high-availability.storageDir), when set.
	StorageDir *string `json:"storageDir,omitempty"`
	// HA cluster id (high-availability.cluster-id), when set.
	ClusterID *string `json:"clusterId,omitempty"`
}

// Information about a registered infrastructure instrument.
type InstrumentInfo struct {
	Name            string   `json:"name"`
	DisplayName     string   `json:"displayName"`
	Type            string   `json:"type"`
	Version         string   `json:"version"`
	Healthy         bool     `json:"healthy"`
	LastHealthCheck *string  `json:"lastHealthCheck,omitempty"`
	Capabilities    []string `json:"capabilities"`
}

// The result of a live instrument connection test. `ok` is true when the
// transient instrument initialized and its health check passed. `message`
// carries the failure reason when `ok` is false. `latencyMs` is the round-trip
// time of the successful check.
type InstrumentTestResult struct {
	Ok        bool    `json:"ok"`
	Message   *string `json:"message,omitempty"`
	LatencyMs *int    `json:"latencyMs,omitempty"`
}

type JMConfigEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type JMEnvironment struct {
	Jvm       *JMEnvironmentJvm `json:"jvm"`
	Classpath []string          `json:"classpath"`
}

type JMEnvironmentJvm struct {
	Version string   `json:"version"`
	Arch    string   `json:"arch"`
	Options []string `json:"options"`
}

type JarEntryPoint struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type JarFile struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Uploaded string           `json:"uploaded"`
	Entry    []*JarEntryPoint `json:"entry"`
}

type JarRunResult struct {
	JobID string `json:"jobId"`
}

type JarUploadResult struct {
	Filename string `json:"filename"`
	Status   string `json:"status"`
}

type JobConfig struct {
	Jid             string         `json:"jid"`
	Name            string         `json:"name"`
	ExecutionMode   string         `json:"executionMode"`
	RestartStrategy string         `json:"restartStrategy"`
	JobParallelism  int            `json:"jobParallelism"`
	ObjectReuseMode bool           `json:"objectReuseMode"`
	UserConfig      []*ConfigEntry `json:"userConfig"`
}

// Detected source or sink connector for a job
type JobConnector struct {
	// Flink vertex ID
	VertexID string `json:"vertexId"`
	// Vertex or component name
	VertexName string `json:"vertexName"`
	// Connector technology: kafka, iceberg, paimon, jdbc, filesystem, unknown
	ConnectorType string `json:"connectorType"`
	// Role in the pipeline: source or sink
	Role string `json:"role"`
	// Primary resource identifier (topic, table, path)
	Resource string `json:"resource"`
	// Detection confidence 0.0-1.0
	Confidence float64 `json:"confidence"`
	// How the connector was detected: manifest, vertex_name, plan_node
	DetectionMethod string `json:"detectionMethod"`
	// I/O metrics for this connector's vertex
	Metrics *ConnectorMetrics `json:"metrics,omitempty"`
}

type JobDetail struct {
	ID               string            `json:"id"`
	Name             string            `json:"name"`
	State            string            `json:"state"`
	StartTime        string            `json:"startTime"`
	EndTime          string            `json:"endTime"`
	Duration         string            `json:"duration"`
	Now              string            `json:"now"`
	Vertices         []*JobVertex      `json:"vertices"`
	Plan             *JobPlan          `json:"plan"`
	Exceptions       []*ExceptionEntry `json:"exceptions"`
	Checkpoints      *CheckpointStats  `json:"checkpoints,omitempty"`
	CheckpointConfig *CheckpointConfig `json:"checkpointConfig,omitempty"`
	JobConfig        *JobConfig        `json:"jobConfig,omitempty"`
	// Per-job failover / restart summary (observe-only). Null when unavailable.
	RestartInfo   *RestartInfo          `json:"restartInfo,omitempty"`
	VertexDetails []*VertexDetail       `json:"vertexDetails,omitempty"`
	Watermarks    []*VertexWatermarks   `json:"watermarks,omitempty"`
	BackPressure  []*VertexBackPressure `json:"backPressure,omitempty"`
	Accumulators  []*VertexAccumulators `json:"accumulators,omitempty"`
	// Job-wide throughput rates derived from source/sink vertex metrics.
	Metrics *JobMetrics `json:"metrics,omitempty"`
	// Watermark lag in milliseconds (`now - min subtask watermark`).
	// Encoded as a string (Long) to safely represent very large lags.
	// Null when no valid watermarks are reported (e.g. batch jobs, or before
	// any source has emitted a watermark).
	WatermarkLag *string `json:"watermarkLag,omitempty"`
	// Detected sources and sinks for this job
	SourcesAndSinks []*JobConnector `json:"sourcesAndSinks"`
}

// Connection type for paginated job history results.
type JobHistoryConnection struct {
	// List of job history edges.
	Edges []*JobHistoryEdge `json:"edges"`
	// Pagination metadata.
	PageInfo *JobHistoryPageInfo `json:"pageInfo"`
}

// A single edge in the job history connection.
type JobHistoryEdge struct {
	// The job record.
	Node *JobHistoryEntry `json:"node"`
	// Opaque cursor for this edge.
	Cursor string `json:"cursor"`
}

// A historical job record from PostgreSQL.
type JobHistoryEntry struct {
	Jid           string  `json:"jid"`
	Cluster       string  `json:"cluster"`
	Name          string  `json:"name"`
	State         string  `json:"state"`
	StartTime     *string `json:"startTime,omitempty"`
	EndTime       *string `json:"endTime,omitempty"`
	DurationMs    string  `json:"durationMs"`
	TasksTotal    int     `json:"tasksTotal"`
	TasksRunning  int     `json:"tasksRunning"`
	TasksFinished int     `json:"tasksFinished"`
	TasksCanceled int     `json:"tasksCanceled"`
	TasksFailed   int     `json:"tasksFailed"`
	CapturedAt    string  `json:"capturedAt"`
}

// Filter criteria for historical job queries.
type JobHistoryFilter struct {
	// Filter by cluster name.
	ClusterID *string `json:"clusterID,omitempty"`
	// Filter by job state (e.g. RUNNING, FAILED, FINISHED, CANCELED).
	State *string `json:"state,omitempty"`
	// Filter by job name (case-insensitive substring match).
	Name *string `json:"name,omitempty"`
	// Return only jobs with start_time >= this timestamp.
	After *string `json:"after,omitempty"`
	// Return only jobs with start_time <= this timestamp.
	Before *string `json:"before,omitempty"`
	// Preset time range filter. Custom after/before takes precedence if both provided.
	TimeRange *TimeRange `json:"timeRange,omitempty"`
}

// Page info for cursor-based pagination.
type JobHistoryPageInfo struct {
	// Whether there are more pages after this one.
	HasNextPage bool `json:"hasNextPage"`
	// Cursor for fetching the next page.
	EndCursor *string `json:"endCursor,omitempty"`
	// Total number of items matching the filter (for UI pagination controls).
	TotalCount int `json:"totalCount"`
}

type JobManagerDetail struct {
	Config      []*JMConfigEntry `json:"config"`
	Environment *JMEnvironment   `json:"environment,omitempty"`
	Metrics     []*MetricEntry   `json:"metrics"`
	// High-availability status derived from the cluster config.
	HaStatus *HAStatus `json:"haStatus"`
}

// Job-level rate metrics, aggregated from source/sink vertices.
type JobMetrics struct {
	// Records-per-second emitted by source vertices (job-wide input throughput).
	RecordsInPerSecond float64 `json:"recordsInPerSecond"`
	// Records-per-second consumed by sink vertices (job-wide output throughput).
	RecordsOutPerSecond float64 `json:"recordsOutPerSecond"`
}

type JobOverview struct {
	ID               string      `json:"id"`
	Name             string      `json:"name"`
	State            string      `json:"state"`
	StartTime        string      `json:"startTime"`
	EndTime          string      `json:"endTime"`
	Duration         string      `json:"duration"`
	LastModification string      `json:"lastModification"`
	Tasks            *TaskCounts `json:"tasks"`
	// Records-per-second emitted by source vertices (job-wide input throughput). Null when no vertex metrics are available yet.
	RecordsInPerSecond *float64 `json:"recordsInPerSecond,omitempty"`
	// Records-per-second consumed by sink vertices (job-wide output throughput). Null when no vertex metrics are available yet.
	RecordsOutPerSecond *float64 `json:"recordsOutPerSecond,omitempty"`
	// Watermark lag in milliseconds (`now - min subtask watermark`). Null for batch jobs or before any source has emitted a watermark.
	WatermarkLag *int `json:"watermarkLag,omitempty"`
	// Scheduler type (e.g. `Adaptive`/`Default`). Added to /jobs/overview in Flink 2.3 (FLIP-487); null on older clusters.
	SchedulerType *string `json:"schedulerType,omitempty"`
	// Job type (`STREAMING`/`BATCH`). Added to /jobs/overview in Flink 2.3 (FLIP-487); null on older clusters.
	JobType *string `json:"jobType,omitempty"`
}

type JobPlan struct {
	Jid   string      `json:"jid"`
	Name  string      `json:"name"`
	Type  string      `json:"type"`
	Nodes []*PlanNode `json:"nodes"`
}

// A job status transition event emitted when a Flink job changes state.
type JobStatusEvent struct {
	JobID          string  `json:"jobId"`
	JobName        string  `json:"jobName"`
	PreviousStatus *string `json:"previousStatus,omitempty"`
	CurrentStatus  string  `json:"currentStatus"`
	Cluster        string  `json:"cluster"`
}

type JobVertex struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	MaxParallelism int            `json:"maxParallelism"`
	Parallelism    int            `json:"parallelism"`
	Status         string         `json:"status"`
	StartTime      string         `json:"startTime"`
	EndTime        string         `json:"endTime"`
	Duration       string         `json:"duration"`
	Tasks          *TaskCounts    `json:"tasks"`
	Metrics        *VertexMetrics `json:"metrics"`
}

// A Kafka topic or broker configuration entry.
type KafkaConfigEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Summary of a Kafka consumer group.
type KafkaConsumerGroup struct {
	GroupID     string `json:"groupId"`
	State       string `json:"state"`
	MemberCount int    `json:"memberCount"`
	TotalLag    int    `json:"totalLag"`
}

// Detailed information about a Kafka consumer group.
type KafkaConsumerGroupDetail struct {
	GroupID      string                  `json:"groupId"`
	State        string                  `json:"state"`
	Protocol     string                  `json:"protocol"`
	ProtocolType string                  `json:"protocolType"`
	Members      []*KafkaGroupMember     `json:"members"`
	Offsets      []*KafkaPartitionOffset `json:"offsets"`
}

// A member of a Kafka consumer group.
type KafkaGroupMember struct {
	ClientID    string                 `json:"clientId"`
	ClientHost  string                 `json:"clientHost"`
	Assignments []*KafkaTopicPartition `json:"assignments"`
}

// A single Kafka record returned by a topic preview read.
type KafkaMessage struct {
	Partition int `json:"partition"`
	Offset    int `json:"offset"`
	// Record timestamp in epoch milliseconds.
	Timestamp int     `json:"timestamp"`
	Key       *string `json:"key,omitempty"`
	Value     string  `json:"value"`
}

// A single partition within a Kafka topic.
type KafkaPartition struct {
	ID             int   `json:"id"`
	Leader         int   `json:"leader"`
	Replicas       []int `json:"replicas"`
	InSyncReplicas []int `json:"inSyncReplicas"`
}

// Per-partition offset and lag for a consumer group.
type KafkaPartitionOffset struct {
	Topic           string `json:"topic"`
	Partition       int    `json:"partition"`
	CommittedOffset int    `json:"committedOffset"`
	EndOffset       int    `json:"endOffset"`
	Lag             int    `json:"lag"`
}

// Result of seeding sample data into a Kafka instrument.
type KafkaSeedResult struct {
	Topics          []*KafkaSeededTopic `json:"topics"`
	RecordsProduced int                 `json:"recordsProduced"`
	// Topic names skipped for any reason (no sample rows, or already populated with skipNonEmpty).
	Skipped []string `json:"skipped"`
	DryRun  bool     `json:"dryRun"`
}

// A topic touched during a Kafka seed operation. Both dry and real runs consult
// the broker, so existed/existingRecords reflect actual broker state either way.
type KafkaSeededTopic struct {
	Topic string `json:"topic"`
	// Template domain from the seed catalog (e.g. ecommerce, iot).
	Domain string `json:"domain"`
	// Whether the topic already existed in the broker when the seed ran.
	Existed bool `json:"existed"`
	// Records already in the topic (sum of partition end−start offsets); 0 when absent.
	ExistingRecords int `json:"existingRecords"`
	// Topic was created (real run) / would be created (dry run).
	Created bool `json:"created"`
	// Skipped because the topic already holds records and skipNonEmpty was set.
	Skipped bool `json:"skipped"`
	// Records produced (real run) / that would be produced (dry run).
	RecordsProduced int `json:"recordsProduced"`
	// Per-topic failure; null when the topic seeded cleanly. Seeding is best-effort per topic.
	Error *string `json:"error,omitempty"`
}

// Summary of a Kafka topic.
type KafkaTopic struct {
	Name              string `json:"name"`
	PartitionCount    int    `json:"partitionCount"`
	ReplicationFactor int    `json:"replicationFactor"`
	Internal          bool   `json:"internal"`
}

// Detailed information about a Kafka topic including partitions and config.
type KafkaTopicDetail struct {
	Name              string              `json:"name"`
	PartitionCount    int                 `json:"partitionCount"`
	ReplicationFactor int                 `json:"replicationFactor"`
	Internal          bool                `json:"internal"`
	Partitions        []*KafkaPartition   `json:"partitions"`
	ConfigEntries     []*KafkaConfigEntry `json:"configEntries"`
	MessageCount      int                 `json:"messageCount"`
}

// A topic-partition assignment.
type KafkaTopicPartition struct {
	Topic     string `json:"topic"`
	Partition int    `json:"partition"`
}

type KeyFieldInput struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// A column in a materialized table's schema (Flink 2.3+, from DESCRIBE).
type MaterializedColumn struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Nullable   bool   `json:"nullable"`
	PrimaryKey bool   `json:"primaryKey"`
	// Watermark expression when the column is a rowtime attribute, else null.
	Watermark *string `json:"watermark,omitempty"`
}

type MaterializedTable struct {
	Name          string                         `json:"name"`
	Catalog       string                         `json:"catalog"`
	Database      string                         `json:"database"`
	RefreshStatus MaterializedTableRefreshStatus `json:"refreshStatus"`
	RefreshMode   *string                        `json:"refreshMode,omitempty"`
	Freshness     *string                        `json:"freshness,omitempty"`
	DefiningQuery *string                        `json:"definingQuery,omitempty"`
	// Schema columns parsed from DESCRIBE MATERIALIZED TABLE (Flink 2.3+); empty on older clusters.
	Columns []*MaterializedColumn `json:"columns"`
}

// A metric available in the catalog (discovered from stored data).
type MetricCatalogEntry struct {
	SourceType string `json:"sourceType"`
	SourceID   string `json:"sourceID"`
	MetricID   string `json:"metricID"`
}

// A single metric data point in a time series.
type MetricDataPoint struct {
	// The metric value.
	Value float64 `json:"value"`
	// When this data point was captured (RFC3339).
	CapturedAt string `json:"capturedAt"`
}

type MetricEntry struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

// A sampled metric value published at ~1s cadence by the server's
// MetricSampler. `jobId` is null for cluster-wide aggregates.
// Supported `metric` values for v1: `throughput`, `watermarkLag`.
type MetricEvent struct {
	ClusterID string  `json:"clusterID"`
	JobID     *string `json:"jobId,omitempty"`
	Metric    string  `json:"metric"`
	Value     float64 `json:"value"`
	Timestamp string  `json:"timestamp"`
}

// Filter criteria for metric time-series queries.
type MetricHistoryFilter struct {
	// Filter by cluster name (required).
	ClusterID string `json:"clusterID"`
	// Filter by source type: job_manager, task_manager, vertex.
	SourceType *string `json:"sourceType,omitempty"`
	// Filter by source ID (e.g. TM ID, vertex ID).
	SourceID *string `json:"sourceID,omitempty"`
	// Filter by metric ID (e.g. Status.JVM.CPU.Load).
	MetricID *string `json:"metricID,omitempty"`
	// Return only data points captured after this timestamp (RFC3339).
	After *string `json:"after,omitempty"`
	// Return only data points captured before this timestamp (RFC3339).
	Before *string `json:"before,omitempty"`
}

// Request for a single metric time series.
type MetricSeriesRequest struct {
	SourceType string `json:"sourceType"`
	SourceID   string `json:"sourceID"`
	MetricID   string `json:"metricID"`
}

// A time series for one metric.
type MetricTimeSeries struct {
	SourceType string             `json:"sourceType"`
	SourceID   string             `json:"sourceID"`
	MetricID   string             `json:"metricID"`
	Points     []*MetricDataPoint `json:"points"`
}

type Mutation struct {
}

type OperatorStateInput struct {
	LogicalKey     string           `json:"logicalKey"`
	NodeID         string           `json:"nodeId"`
	Component      string           `json:"component"`
	StateRole      string           `json:"stateRole"`
	KeyFields      []*KeyFieldInput `json:"keyFields"`
	ChangelogMode  string           `json:"changelogMode"`
	TTL            *string          `json:"ttl,omitempty"`
	MaxParallelism *int             `json:"maxParallelism,omitempty"`
	OperatorHash   string           `json:"operatorHash"`
}

// Sorting configuration for query results.
type OrderByInput struct {
	// The field to sort by.
	Field JobHistoryOrderField `json:"field"`
	// Sort direction (ASC or DESC).
	Direction OrderDirection `json:"direction"`
}

// Cursor-based pagination input.
type PaginationInput struct {
	// Maximum number of items to return.
	First *int `json:"first,omitempty"`
	// Opaque cursor for the next page.
	After *string `json:"after,omitempty"`
}

type PipelineManifestVersion struct {
	ID               string  `json:"id"`
	Pipeline         string  `json:"pipeline"`
	Environment      string  `json:"environment"`
	Version          int     `json:"version"`
	FlinkVersion     *string `json:"flinkVersion,omitempty"`
	StateFingerprint string  `json:"stateFingerprint"`
	Source           string  `json:"source"`
	CreatedAt        string  `json:"createdAt"`
	// The full canonical State Manifest JSON (sorted keys) for version diffing.
	ManifestJSON string `json:"manifestJson"`
}

// A per-pipeline rollup for the State Registry index and the deployment kanban's
// "Blocked" join. One row per (pipeline, environment); fetched in a single query
// to avoid an N+1 over the per-pipeline report endpoints.
type PipelineStateSummary struct {
	Pipeline         string  `json:"pipeline"`
	Environment      string  `json:"environment"`
	LatestVersion    int     `json:"latestVersion"`
	VersionCount     int     `json:"versionCount"`
	StateFingerprint string  `json:"stateFingerprint"`
	FlinkVersion     *string `json:"flinkVersion,omitempty"`
	// Verdict of the most recent compatibility check; null when none has run.
	LastVerdict   *CompatibilityVerdict `json:"lastVerdict,omitempty"`
	LastCheckedAt *string               `json:"lastCheckedAt,omitempty"`
	// Number of issues in the most recent check; null when none has run.
	LastIssueCount *int `json:"lastIssueCount,omitempty"`
	// Count of non-PENDING restore outcomes observed for this pipeline.
	RestoreTotal int `json:"restoreTotal"`
	// Count of SUCCESS restore outcomes (restoreTotal - this = failures).
	RestoreSuccess int `json:"restoreSuccess"`
	// ISO timestamp of the latest manifest version.
	UpdatedAt string `json:"updatedAt"`
}

type PlanNode struct {
	ID               string           `json:"id"`
	Parallelism      int              `json:"parallelism"`
	Operator         string           `json:"operator"`
	OperatorStrategy string           `json:"operatorStrategy"`
	Description      string           `json:"description"`
	Inputs           []*PlanNodeInput `json:"inputs,omitempty"`
}

type PlanNodeInput struct {
	Num          int    `json:"num"`
	ID           string `json:"id"`
	ShipStrategy string `json:"shipStrategy"`
	Exchange     string `json:"exchange"`
}

// Result of a single pre-flight check for simulation readiness.
type PreflightCheck struct {
	ID       string  `json:"id"`
	Label    string  `json:"label"`
	Status   string  `json:"status"`
	Detail   *string `json:"detail,omitempty"`
	Fix      *string `json:"fix,omitempty"`
	Required bool    `json:"required"`
}

type Query struct {
}

// A single field/value pair from a Redis HASH.
type RedisHashEntry struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

// Metadata about a single Redis key.
type RedisKeyInfo struct {
	Key         string `json:"key"`
	Type        string `json:"type"`
	TTL         int    `json:"ttl"`
	Encoding    string `json:"encoding"`
	MemoryUsage int    `json:"memoryUsage"`
}

// The type-aware value of a Redis key. Only the field corresponding to `type` is
// populated; the others are null.
type RedisKeyValue struct {
	Key         string            `json:"key"`
	Type        string            `json:"type"`
	StringValue *string           `json:"stringValue,omitempty"`
	HashValue   []*RedisHashEntry `json:"hashValue,omitempty"`
	ListValue   []string          `json:"listValue,omitempty"`
	SetValue    []string          `json:"setValue,omitempty"`
	ZsetValue   []*RedisZSetEntry `json:"zsetValue,omitempty"`
	Truncated   bool              `json:"truncated"`
	TotalSize   int               `json:"totalSize"`
}

// Memory breakdown parsed from INFO memory.
type RedisMemoryStats struct {
	UsedMemory         int     `json:"usedMemory"`
	PeakMemory         int     `json:"peakMemory"`
	Rss                int     `json:"rss"`
	FragmentationRatio float64 `json:"fragmentationRatio"`
	DatasetSize        int     `json:"datasetSize"`
	Overhead           int     `json:"overhead"`
	Allocator          string  `json:"allocator"`
}

// Result of a Redis SCAN operation: a batch of keys plus the cursor for the next
// page (or "0" when iteration is complete).
type RedisScanResult struct {
	Keys    []string `json:"keys"`
	Cursor  string   `json:"cursor"`
	HasMore bool     `json:"hasMore"`
}

// High-level Redis server statistics parsed from INFO.
type RedisServerInfo struct {
	Version          string `json:"version"`
	Uptime           int    `json:"uptime"`
	ConnectedClients int    `json:"connectedClients"`
	UsedMemory       int    `json:"usedMemory"`
	TotalKeys        int    `json:"totalKeys"`
	KeyspaceHits     int    `json:"keyspaceHits"`
	KeyspaceMisses   int    `json:"keyspaceMisses"`
}

// A single member/score pair from a Redis ZSET.
type RedisZSetEntry struct {
	Member string  `json:"member"`
	Score  float64 `json:"score"`
}

// A single AdaptiveScheduler rescale event (Flink 2.3+, FLIP-495).
type RescaleEvent struct {
	// Rescale event identifier (UUID).
	UUID   string        `json:"uuid"`
	Status RescaleStatus `json:"status"`
	// Epoch-millis timestamp at which the rescale was triggered.
	TriggeredAt string `json:"triggeredAt"`
	// Wall-clock duration of the rescale in ms. Null until finished.
	DurationMs *string `json:"durationMs,omitempty"`
	// Job parallelism before the rescale. Null when unknown.
	ParallelismBefore *int `json:"parallelismBefore,omitempty"`
	// Job parallelism after the rescale. Null when unknown.
	ParallelismAfter *int `json:"parallelismAfter,omitempty"`
	// Failure reason. Null unless `status: FAILED`.
	Error *string `json:"error,omitempty"`
}

type RescaleResult struct {
	RequestID string `json:"requestId"`
}

// Aggregate rescale statistics for a job (Flink 2.3+, FLIP-495).
type RescaleSummary struct {
	TotalRescales int `json:"totalRescales"`
	// Epoch-millis timestamp of the most recent rescale. Null when none.
	LastRescaleAt *string `json:"lastRescaleAt,omitempty"`
}

// Per-job failover / restart summary, sourced from job metrics
// (numRestarts / fullRestarts / uptime / downtime) and job config
// (restart-strategy). All fields are nullable — an absent metric means
// "unknown", not zero. uptimeMs / downtimeMs are encoded as Long-safe
// strings (ms can exceed a 32-bit Int for long-running jobs).
type RestartInfo struct {
	NumRestarts     *int    `json:"numRestarts,omitempty"`
	FullRestarts    *int    `json:"fullRestarts,omitempty"`
	RestartStrategy *string `json:"restartStrategy,omitempty"`
	UptimeMs        *string `json:"uptimeMs,omitempty"`
	DowntimeMs      *string `json:"downtimeMs,omitempty"`
}

type RestoreEvent struct {
	ID          string  `json:"id"`
	Pipeline    string  `json:"pipeline"`
	Environment string  `json:"environment"`
	Cluster     string  `json:"cluster"`
	Jid         *string `json:"jid,omitempty"`
	// PENDING | SUCCESS | FAILED | UNKNOWN
	Outcome              string  `json:"outcome"`
	ErrorCategory        *string `json:"errorCategory,omitempty"`
	RestoredCheckpointID *int    `json:"restoredCheckpointId,omitempty"`
	BlueGreenName        *string `json:"blueGreenName,omitempty"`
	ObservedAt           string  `json:"observedAt"`
}

type SQLCloseResult struct {
	Success bool `json:"success"`
}

// A column descriptor from SQL Gateway results.
type SQLColumn struct {
	Name     string `json:"name"`
	DataType string `json:"dataType"`
}

// Result of an EXPLAIN statement — returns the plan text and detected format
type SQLExplainResult struct {
	PlanText string `json:"planText"`
	Format   string `json:"format"`
}

type SQLFetchResult struct {
	Columns   []*SQLColumn `json:"columns"`
	Rows      [][]*string  `json:"rows"`
	HasMore   bool         `json:"hasMore"`
	NextToken *string      `json:"nextToken,omitempty"`
	// Flink job id when this statement launched a job (INSERT / streaming SELECT); null for DDL or bounded batch.
	JobID *string `json:"jobID,omitempty"`
}

// A batch of SQL Gateway query results.
type SQLResultBatch struct {
	Columns []*SQLColumn `json:"columns"`
	Rows    [][]*string  `json:"rows"`
	HasMore bool         `json:"hasMore"`
}

type SQLSessionResult struct {
	SessionHandle string `json:"sessionHandle"`
}

type SQLStatementResult struct {
	OperationHandle string `json:"operationHandle"`
}

// A single Flink savepoint operation.
type Savepoint struct {
	// The Flink savepoint operation handle.
	ID          string               `json:"id"`
	Status      SavepointStatus      `json:"status"`
	TriggerType SavepointTriggerType `json:"triggerType"`
	// Savepoint storage path. Null until the operation completes successfully.
	Location *string `json:"location,omitempty"`
	// Savepoint size in bytes (String to safely encode int64). Null until completed.
	SizeBytes *string `json:"sizeBytes,omitempty"`
	// Trigger-to-completion duration in milliseconds. Null until completed.
	DurationMs *string `json:"durationMs,omitempty"`
	// ISO-millisecond epoch timestamp at which the operation was triggered.
	TriggeredAt string `json:"triggeredAt"`
	// Failure reason. Null unless `status: FAILED`.
	Error *string `json:"error,omitempty"`
}

type SavepointTriggerResult struct {
	RequestID string `json:"requestId"`
}

// The full content of a single schema version.
type SchemaDetail struct {
	Subject    string             `json:"subject"`
	Version    int                `json:"version"`
	ID         int                `json:"id"`
	SchemaType string             `json:"schemaType"`
	Schema     string             `json:"schema"`
	References []*SchemaReference `json:"references"`
}

// A cross-subject reference embedded in a schema.
type SchemaReference struct {
	Name    string `json:"name"`
	Subject string `json:"subject"`
	Version int    `json:"version"`
}

// The registry's global default compatibility level (e.g. BACKWARD, FULL,
// NONE). Individual subjects may override this — see `SchemaSubject.compatibility`.
type SchemaRegistryConfig struct {
	Compatibility string `json:"compatibility"`
}

// A subject in the Schema Registry, with metadata about its latest version.
type SchemaSubject struct {
	Name          string `json:"name"`
	LatestVersion int    `json:"latestVersion"`
	SchemaType    string `json:"schemaType"`
	SchemaID      int    `json:"schemaId"`
	Compatibility string `json:"compatibility"`
}

type SimulationInput struct {
	Scenario   string         `json:"scenario"`
	TargetJobs []string       `json:"targetJobs,omitempty"`
	Parameters map[string]any `json:"parameters"`
	Cluster    *string        `json:"cluster,omitempty"`
}

type SimulationObservation struct {
	Timestamp  string  `json:"timestamp"`
	Metric     string  `json:"metric"`
	Value      float64 `json:"value"`
	Annotation *string `json:"annotation,omitempty"`
}

type SimulationPreset struct {
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	Scenario          string         `json:"scenario"`
	DefaultParameters map[string]any `json:"defaultParameters"`
	Category          string         `json:"category"`
}

type SimulationRun struct {
	ID           string                   `json:"id"`
	Scenario     string                   `json:"scenario"`
	Status       SimulationStatus         `json:"status"`
	StartedAt    string                   `json:"startedAt"`
	StoppedAt    *string                  `json:"stoppedAt,omitempty"`
	Parameters   map[string]any           `json:"parameters"`
	Observations []*SimulationObservation `json:"observations"`
}

type StateManifestInput struct {
	SchemaVersion int                   `json:"schemaVersion"`
	PipelineName  string                `json:"pipelineName"`
	FlinkVersion  string                `json:"flinkVersion"`
	Operators     []*OperatorStateInput `json:"operators"`
	Fingerprint   string                `json:"fingerprint"`
}

// Status of the PostgreSQL historical storage backend.
type StorageStatus struct {
	// Whether storage is enabled in configuration.
	Enabled bool `json:"enabled"`
	// Whether the database connection is healthy.
	Connected bool `json:"connected"`
	// Current migration version applied, empty if none.
	MigrationVersion string `json:"migrationVersion"`
	// Total connections in the pool.
	TotalConns int `json:"totalConns"`
	// Idle connections in the pool.
	IdleConns int `json:"idleConns"`
}

// A historical checkpoint record from PostgreSQL.
type StoredCheckpoint struct {
	CheckpointID     string  `json:"checkpointID"`
	Jid              string  `json:"jid"`
	Cluster          string  `json:"cluster"`
	Status           string  `json:"status"`
	IsSavepoint      bool    `json:"isSavepoint"`
	TriggerTimestamp *string `json:"triggerTimestamp,omitempty"`
	LatestAck        *string `json:"latestAck,omitempty"`
	StateSize        string  `json:"stateSize"`
	EndToEndDuration string  `json:"endToEndDuration"`
	ProcessedData    string  `json:"processedData"`
	PersistedData    string  `json:"persistedData"`
	NumSubtasks      int     `json:"numSubtasks"`
	NumAckSubtasks   int     `json:"numAckSubtasks"`
	CheckpointedSize *string `json:"checkpointedSize,omitempty"`
	// Failure reason. Null unless status is FAILED.
	FailureMessage *string `json:"failureMessage,omitempty"`
	// Failure time (RFC3339). Null unless status is FAILED.
	FailureTimestamp *string `json:"failureTimestamp,omitempty"`
	// Restore location. Null unless the checkpoint was externally addressable.
	ExternalPath *string `json:"externalPath,omitempty"`
	CapturedAt   string  `json:"capturedAt"`
}

// A historical exception record from PostgreSQL.
type StoredException struct {
	ID            string  `json:"id"`
	Jid           string  `json:"jid"`
	Cluster       string  `json:"cluster"`
	ExceptionName string  `json:"exceptionName"`
	Stacktrace    *string `json:"stacktrace,omitempty"`
	Timestamp     string  `json:"timestamp"`
	TaskName      *string `json:"taskName,omitempty"`
	Endpoint      *string `json:"endpoint,omitempty"`
	TaskManagerID *string `json:"taskManagerID,omitempty"`
	CapturedAt    string  `json:"capturedAt"`
}

type Subscription struct {
}

type SubtaskBackPressure struct {
	Subtask           int     `json:"subtask"`
	AttemptNumber     int     `json:"attemptNumber"`
	BackpressureLevel string  `json:"backpressureLevel"`
	Ratio             float64 `json:"ratio"`
	BusyRatio         float64 `json:"busyRatio"`
	IdleRatio         float64 `json:"idleRatio"`
}

type SubtaskInfo struct {
	Subtask       int            `json:"subtask"`
	Status        string         `json:"status"`
	Attempt       int            `json:"attempt"`
	Endpoint      string         `json:"endpoint"`
	StartTime     string         `json:"startTime"`
	EndTime       string         `json:"endTime"`
	Duration      string         `json:"duration"`
	Metrics       *VertexMetrics `json:"metrics"`
	TaskManagerID string         `json:"taskManagerId"`
}

type SubtaskTimes struct {
	ID       string               `json:"id"`
	Name     string               `json:"name"`
	Now      string               `json:"now"`
	Subtasks []*SubtaskTimesEntry `json:"subtasks"`
}

type SubtaskTimesEntry struct {
	Subtask    int               `json:"subtask"`
	Host       string            `json:"host"`
	Duration   string            `json:"duration"`
	Timestamps []*TimestampEntry `json:"timestamps"`
}

type TMLogEntry struct {
	Name string `json:"name"`
	Size string `json:"size"`
}

type TapManifest struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Version     string         `json:"version"`
	Config      map[string]any `json:"config,omitempty"`
}

type TaskCounts struct {
	Created      int `json:"created"`
	Scheduled    int `json:"scheduled"`
	Deploying    int `json:"deploying"`
	Running      int `json:"running"`
	Finished     int `json:"finished"`
	Canceling    int `json:"canceling"`
	Canceled     int `json:"canceled"`
	Failed       int `json:"failed"`
	Reconciling  int `json:"reconciling"`
	Initializing int `json:"initializing"`
}

type TaskManagerDetail struct {
	ID                     string                      `json:"id"`
	Path                   string                      `json:"path"`
	DataPort               int                         `json:"dataPort"`
	JmxPort                int                         `json:"jmxPort"`
	TimeSinceLastHeartbeat string                      `json:"timeSinceLastHeartbeat"`
	SlotsNumber            int                         `json:"slotsNumber"`
	FreeSlots              int                         `json:"freeSlots"`
	TotalResource          *TaskManagerResourceProfile `json:"totalResource"`
	FreeResource           *TaskManagerResourceProfile `json:"freeResource"`
	Hardware               *TaskManagerHardware        `json:"hardware"`
	MemoryConfiguration    *TaskManagerMemory          `json:"memoryConfiguration"`
	AllocatedSlots         []*AllocatedSlot            `json:"allocatedSlots"`
	Metrics                []*MetricEntry              `json:"metrics"`
}

type TaskManagerHardware struct {
	CPUCores       int    `json:"cpuCores"`
	PhysicalMemory string `json:"physicalMemory"`
	FreeMemory     string `json:"freeMemory"`
	ManagedMemory  string `json:"managedMemory"`
}

type TaskManagerMemory struct {
	FrameworkHeap      string `json:"frameworkHeap"`
	TaskHeap           string `json:"taskHeap"`
	FrameworkOffHeap   string `json:"frameworkOffHeap"`
	TaskOffHeap        string `json:"taskOffHeap"`
	NetworkMemory      string `json:"networkMemory"`
	ManagedMemory      string `json:"managedMemory"`
	JvmMetaspace       string `json:"jvmMetaspace"`
	JvmOverhead        string `json:"jvmOverhead"`
	TotalFlinkMemory   string `json:"totalFlinkMemory"`
	TotalProcessMemory string `json:"totalProcessMemory"`
}

type TaskManagerOverview struct {
	ID                     string                      `json:"id"`
	Path                   string                      `json:"path"`
	DataPort               int                         `json:"dataPort"`
	JmxPort                int                         `json:"jmxPort"`
	TimeSinceLastHeartbeat string                      `json:"timeSinceLastHeartbeat"`
	SlotsNumber            int                         `json:"slotsNumber"`
	FreeSlots              int                         `json:"freeSlots"`
	TotalResource          *TaskManagerResourceProfile `json:"totalResource"`
	FreeResource           *TaskManagerResourceProfile `json:"freeResource"`
	Hardware               *TaskManagerHardware        `json:"hardware"`
	MemoryConfiguration    *TaskManagerMemory          `json:"memoryConfiguration"`
}

type TaskManagerResourceProfile struct {
	CPUCores          float64 `json:"cpuCores"`
	TaskHeapMemory    string  `json:"taskHeapMemory"`
	TaskOffHeapMemory string  `json:"taskOffHeapMemory"`
	ManagedMemory     string  `json:"managedMemory"`
	NetworkMemory     string  `json:"networkMemory"`
}

type ThreadDumpEntry struct {
	ThreadName            string `json:"threadName"`
	StringifiedThreadInfo string `json:"stringifiedThreadInfo"`
}

type TimestampEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UpdateAlertRuleInput struct {
	Name        string               `json:"name"`
	Description *string              `json:"description,omitempty"`
	Condition   *AlertConditionInput `json:"condition"`
	Severity    AlertSeverity        `json:"severity"`
	Owner       *string              `json:"owner,omitempty"`
	Enabled     bool                 `json:"enabled"`
}

type UserAccumulator struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type VertexAccumulators struct {
	VertexID     string             `json:"vertexId"`
	Accumulators []*UserAccumulator `json:"accumulators"`
}

type VertexBackPressure struct {
	VertexID     string            `json:"vertexId"`
	BackPressure *BackPressureInfo `json:"backPressure"`
}

type VertexDetail struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Parallelism int            `json:"parallelism"`
	Now         string         `json:"now"`
	Subtasks    []*SubtaskInfo `json:"subtasks"`
}

type VertexMetrics struct {
	ReadBytes                string `json:"readBytes"`
	ReadBytesComplete        bool   `json:"readBytesComplete"`
	WriteBytes               string `json:"writeBytes"`
	WriteBytesComplete       bool   `json:"writeBytesComplete"`
	ReadRecords              string `json:"readRecords"`
	ReadRecordsComplete      bool   `json:"readRecordsComplete"`
	WriteRecords             string `json:"writeRecords"`
	WriteRecordsComplete     bool   `json:"writeRecordsComplete"`
	AccumulatedBackpressured string `json:"accumulatedBackpressured"`
	AccumulatedIdle          string `json:"accumulatedIdle"`
	AccumulatedBusy          string `json:"accumulatedBusy"`
}

type VertexWatermarks struct {
	VertexID   string            `json:"vertexId"`
	Watermarks []*WatermarkEntry `json:"watermarks"`
}

type WatermarkEntry struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

// Alert rule condition type. v1 enum.
type AlertConditionType string

const (
	AlertConditionTypeSlotExhaustion        AlertConditionType = "SLOT_EXHAUSTION"
	AlertConditionTypeBackpressure          AlertConditionType = "BACKPRESSURE"
	AlertConditionTypeCheckpointFailure     AlertConditionType = "CHECKPOINT_FAILURE"
	AlertConditionTypeTmMemory              AlertConditionType = "TM_MEMORY"
	AlertConditionTypeTmLost                AlertConditionType = "TM_LOST"
	AlertConditionTypeProcessMemoryHeadroom AlertConditionType = "PROCESS_MEMORY_HEADROOM"
	AlertConditionTypeGcPressure            AlertConditionType = "GC_PRESSURE"
)

var AllAlertConditionType = []AlertConditionType{
	AlertConditionTypeSlotExhaustion,
	AlertConditionTypeBackpressure,
	AlertConditionTypeCheckpointFailure,
	AlertConditionTypeTmMemory,
	AlertConditionTypeTmLost,
	AlertConditionTypeProcessMemoryHeadroom,
	AlertConditionTypeGcPressure,
}

func (e AlertConditionType) IsValid() bool {
	switch e {
	case AlertConditionTypeSlotExhaustion, AlertConditionTypeBackpressure, AlertConditionTypeCheckpointFailure, AlertConditionTypeTmMemory, AlertConditionTypeTmLost, AlertConditionTypeProcessMemoryHeadroom, AlertConditionTypeGcPressure:
		return true
	}
	return false
}

func (e AlertConditionType) String() string {
	return string(e)
}

func (e *AlertConditionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertConditionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertConditionType", str)
	}
	return nil
}

func (e AlertConditionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertConditionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertConditionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlertSeverity string

const (
	AlertSeverityInfo     AlertSeverity = "info"
	AlertSeverityWarning  AlertSeverity = "warning"
	AlertSeverityCritical AlertSeverity = "critical"
)

var AllAlertSeverity = []AlertSeverity{
	AlertSeverityInfo,
	AlertSeverityWarning,
	AlertSeverityCritical,
}

func (e AlertSeverity) IsValid() bool {
	switch e {
	case AlertSeverityInfo, AlertSeverityWarning, AlertSeverityCritical:
		return true
	}
	return false
}

func (e AlertSeverity) String() string {
	return string(e)
}

func (e *AlertSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertSeverity", str)
	}
	return nil
}

func (e AlertSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlertState string

const (
	AlertStateFiring       AlertState = "FIRING"
	AlertStateAcknowledged AlertState = "ACKNOWLEDGED"
	AlertStateSilenced     AlertState = "SILENCED"
	AlertStateResolved     AlertState = "RESOLVED"
)

var AllAlertState = []AlertState{
	AlertStateFiring,
	AlertStateAcknowledged,
	AlertStateSilenced,
	AlertStateResolved,
}

func (e AlertState) IsValid() bool {
	switch e {
	case AlertStateFiring, AlertStateAcknowledged, AlertStateSilenced, AlertStateResolved:
		return true
	}
	return false
}

func (e AlertState) String() string {
	return string(e)
}

func (e *AlertState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertState", str)
	}
	return nil
}

func (e AlertState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BlueGreenState string

const (
	BlueGreenStateInitializingBlue     BlueGreenState = "INITIALIZING_BLUE"
	BlueGreenStateActiveBlue           BlueGreenState = "ACTIVE_BLUE"
	BlueGreenStateActiveGreen          BlueGreenState = "ACTIVE_GREEN"
	BlueGreenStateSavepointingBlue     BlueGreenState = "SAVEPOINTING_BLUE"
	BlueGreenStateSavepointingGreen    BlueGreenState = "SAVEPOINTING_GREEN"
	BlueGreenStateTransitioningToBlue  BlueGreenState = "TRANSITIONING_TO_BLUE"
	BlueGreenStateTransitioningToGreen BlueGreenState = "TRANSITIONING_TO_GREEN"
)

var AllBlueGreenState = []BlueGreenState{
	BlueGreenStateInitializingBlue,
	BlueGreenStateActiveBlue,
	BlueGreenStateActiveGreen,
	BlueGreenStateSavepointingBlue,
	BlueGreenStateSavepointingGreen,
	BlueGreenStateTransitioningToBlue,
	BlueGreenStateTransitioningToGreen,
}

func (e BlueGreenState) IsValid() bool {
	switch e {
	case BlueGreenStateInitializingBlue, BlueGreenStateActiveBlue, BlueGreenStateActiveGreen, BlueGreenStateSavepointingBlue, BlueGreenStateSavepointingGreen, BlueGreenStateTransitioningToBlue, BlueGreenStateTransitioningToGreen:
		return true
	}
	return false
}

func (e BlueGreenState) String() string {
	return string(e)
}

func (e *BlueGreenState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlueGreenState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlueGreenState", str)
	}
	return nil
}

func (e BlueGreenState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BlueGreenState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BlueGreenState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Health status of a registered Flink cluster.
type ClusterStatus string

const (
	ClusterStatusHealthy   ClusterStatus = "HEALTHY"
	ClusterStatusUnhealthy ClusterStatus = "UNHEALTHY"
	ClusterStatusUnknown   ClusterStatus = "UNKNOWN"
)

var AllClusterStatus = []ClusterStatus{
	ClusterStatusHealthy,
	ClusterStatusUnhealthy,
	ClusterStatusUnknown,
}

func (e ClusterStatus) IsValid() bool {
	switch e {
	case ClusterStatusHealthy, ClusterStatusUnhealthy, ClusterStatusUnknown:
		return true
	}
	return false
}

func (e ClusterStatus) String() string {
	return string(e)
}

func (e *ClusterStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClusterStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClusterStatus", str)
	}
	return nil
}

func (e ClusterStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClusterStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClusterStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompatibilityVerdict string

const (
	CompatibilityVerdictCompatible   CompatibilityVerdict = "COMPATIBLE"
	CompatibilityVerdictWarning      CompatibilityVerdict = "WARNING"
	CompatibilityVerdictIncompatible CompatibilityVerdict = "INCOMPATIBLE"
)

var AllCompatibilityVerdict = []CompatibilityVerdict{
	CompatibilityVerdictCompatible,
	CompatibilityVerdictWarning,
	CompatibilityVerdictIncompatible,
}

func (e CompatibilityVerdict) IsValid() bool {
	switch e {
	case CompatibilityVerdictCompatible, CompatibilityVerdictWarning, CompatibilityVerdictIncompatible:
		return true
	}
	return false
}

func (e CompatibilityVerdict) String() string {
	return string(e)
}

func (e *CompatibilityVerdict) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompatibilityVerdict(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompatibilityVerdict", str)
	}
	return nil
}

func (e CompatibilityVerdict) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompatibilityVerdict) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompatibilityVerdict) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IssueSeverity string

const (
	IssueSeverityWarning IssueSeverity = "WARNING"
	IssueSeverityError   IssueSeverity = "ERROR"
)

var AllIssueSeverity = []IssueSeverity{
	IssueSeverityWarning,
	IssueSeverityError,
}

func (e IssueSeverity) IsValid() bool {
	switch e {
	case IssueSeverityWarning, IssueSeverityError:
		return true
	}
	return false
}

func (e IssueSeverity) String() string {
	return string(e)
}

func (e *IssueSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IssueSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IssueSeverity", str)
	}
	return nil
}

func (e IssueSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IssueSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IssueSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sortable fields for job history results.
type JobHistoryOrderField string

const (
	JobHistoryOrderFieldStartTime JobHistoryOrderField = "START_TIME"
	JobHistoryOrderFieldEndTime   JobHistoryOrderField = "END_TIME"
	JobHistoryOrderFieldDuration  JobHistoryOrderField = "DURATION"
	JobHistoryOrderFieldName      JobHistoryOrderField = "NAME"
	JobHistoryOrderFieldState     JobHistoryOrderField = "STATE"
)

var AllJobHistoryOrderField = []JobHistoryOrderField{
	JobHistoryOrderFieldStartTime,
	JobHistoryOrderFieldEndTime,
	JobHistoryOrderFieldDuration,
	JobHistoryOrderFieldName,
	JobHistoryOrderFieldState,
}

func (e JobHistoryOrderField) IsValid() bool {
	switch e {
	case JobHistoryOrderFieldStartTime, JobHistoryOrderFieldEndTime, JobHistoryOrderFieldDuration, JobHistoryOrderFieldName, JobHistoryOrderFieldState:
		return true
	}
	return false
}

func (e JobHistoryOrderField) String() string {
	return string(e)
}

func (e *JobHistoryOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobHistoryOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobHistoryOrderField", str)
	}
	return nil
}

func (e JobHistoryOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobHistoryOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobHistoryOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Read order for a topic preview.
type KafkaMessageOrder string

const (
	// Most recent records first (the live end of the stream).
	KafkaMessageOrderNewest KafkaMessageOrder = "NEWEST"
	// Earliest retained records first (e.g. the deterministic seed rows).
	KafkaMessageOrderOldest KafkaMessageOrder = "OLDEST"
)

var AllKafkaMessageOrder = []KafkaMessageOrder{
	KafkaMessageOrderNewest,
	KafkaMessageOrderOldest,
}

func (e KafkaMessageOrder) IsValid() bool {
	switch e {
	case KafkaMessageOrderNewest, KafkaMessageOrderOldest:
		return true
	}
	return false
}

func (e KafkaMessageOrder) String() string {
	return string(e)
}

func (e *KafkaMessageOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KafkaMessageOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KafkaMessageOrder", str)
	}
	return nil
}

func (e KafkaMessageOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KafkaMessageOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KafkaMessageOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MaterializedTableRefreshStatus string

const (
	MaterializedTableRefreshStatusActivated    MaterializedTableRefreshStatus = "ACTIVATED"
	MaterializedTableRefreshStatusSuspended    MaterializedTableRefreshStatus = "SUSPENDED"
	MaterializedTableRefreshStatusInitializing MaterializedTableRefreshStatus = "INITIALIZING"
)

var AllMaterializedTableRefreshStatus = []MaterializedTableRefreshStatus{
	MaterializedTableRefreshStatusActivated,
	MaterializedTableRefreshStatusSuspended,
	MaterializedTableRefreshStatusInitializing,
}

func (e MaterializedTableRefreshStatus) IsValid() bool {
	switch e {
	case MaterializedTableRefreshStatusActivated, MaterializedTableRefreshStatusSuspended, MaterializedTableRefreshStatusInitializing:
		return true
	}
	return false
}

func (e MaterializedTableRefreshStatus) String() string {
	return string(e)
}

func (e *MaterializedTableRefreshStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MaterializedTableRefreshStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MaterializedTableRefreshStatus", str)
	}
	return nil
}

func (e MaterializedTableRefreshStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MaterializedTableRefreshStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MaterializedTableRefreshStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sort direction.
type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Lifecycle state of an adaptive-scheduler rescale event (Flink 2.3+, FLIP-495).
type RescaleStatus string

const (
	RescaleStatusPending    RescaleStatus = "PENDING"
	RescaleStatusInProgress RescaleStatus = "IN_PROGRESS"
	RescaleStatusCompleted  RescaleStatus = "COMPLETED"
	RescaleStatusFailed     RescaleStatus = "FAILED"
)

var AllRescaleStatus = []RescaleStatus{
	RescaleStatusPending,
	RescaleStatusInProgress,
	RescaleStatusCompleted,
	RescaleStatusFailed,
}

func (e RescaleStatus) IsValid() bool {
	switch e {
	case RescaleStatusPending, RescaleStatusInProgress, RescaleStatusCompleted, RescaleStatusFailed:
		return true
	}
	return false
}

func (e RescaleStatus) String() string {
	return string(e)
}

func (e *RescaleStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RescaleStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RescaleStatus", str)
	}
	return nil
}

func (e RescaleStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RescaleStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RescaleStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Lifecycle state of a savepoint operation.
type SavepointStatus string

const (
	SavepointStatusInProgress SavepointStatus = "IN_PROGRESS"
	SavepointStatusCompleted  SavepointStatus = "COMPLETED"
	SavepointStatusFailed     SavepointStatus = "FAILED"
)

var AllSavepointStatus = []SavepointStatus{
	SavepointStatusInProgress,
	SavepointStatusCompleted,
	SavepointStatusFailed,
}

func (e SavepointStatus) IsValid() bool {
	switch e {
	case SavepointStatusInProgress, SavepointStatusCompleted, SavepointStatusFailed:
		return true
	}
	return false
}

func (e SavepointStatus) String() string {
	return string(e)
}

func (e *SavepointStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SavepointStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SavepointStatus", str)
	}
	return nil
}

func (e SavepointStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SavepointStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SavepointStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// How a savepoint was triggered.
//
// The server records this when its own mutations initiate a savepoint;
// savepoints observed in Flink but not initiated by this server default
// to MANUAL.
type SavepointTriggerType string

const (
	SavepointTriggerTypeManual            SavepointTriggerType = "MANUAL"
	SavepointTriggerTypeStopWithSavepoint SavepointTriggerType = "STOP_WITH_SAVEPOINT"
	SavepointTriggerTypeBlueGreen         SavepointTriggerType = "BLUE_GREEN"
)

var AllSavepointTriggerType = []SavepointTriggerType{
	SavepointTriggerTypeManual,
	SavepointTriggerTypeStopWithSavepoint,
	SavepointTriggerTypeBlueGreen,
}

func (e SavepointTriggerType) IsValid() bool {
	switch e {
	case SavepointTriggerTypeManual, SavepointTriggerTypeStopWithSavepoint, SavepointTriggerTypeBlueGreen:
		return true
	}
	return false
}

func (e SavepointTriggerType) String() string {
	return string(e)
}

func (e *SavepointTriggerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SavepointTriggerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SavepointTriggerType", str)
	}
	return nil
}

func (e SavepointTriggerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SavepointTriggerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SavepointTriggerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SimulationStatus string

const (
	SimulationStatusPending   SimulationStatus = "PENDING"
	SimulationStatusRunning   SimulationStatus = "RUNNING"
	SimulationStatusCompleted SimulationStatus = "COMPLETED"
	SimulationStatusFailed    SimulationStatus = "FAILED"
	SimulationStatusCancelled SimulationStatus = "CANCELLED"
)

var AllSimulationStatus = []SimulationStatus{
	SimulationStatusPending,
	SimulationStatusRunning,
	SimulationStatusCompleted,
	SimulationStatusFailed,
	SimulationStatusCancelled,
}

func (e SimulationStatus) IsValid() bool {
	switch e {
	case SimulationStatusPending, SimulationStatusRunning, SimulationStatusCompleted, SimulationStatusFailed, SimulationStatusCancelled:
		return true
	}
	return false
}

func (e SimulationStatus) String() string {
	return string(e)
}

func (e *SimulationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SimulationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SimulationStatus", str)
	}
	return nil
}

func (e SimulationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SimulationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SimulationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Preset time range for filtering historical data.
type TimeRange string

const (
	TimeRangeLast1h  TimeRange = "LAST_1H"
	TimeRangeLast2h  TimeRange = "LAST_2H"
	TimeRangeLast24h TimeRange = "LAST_24H"
	TimeRangeLast7d  TimeRange = "LAST_7D"
	TimeRangeLast30d TimeRange = "LAST_30D"
)

var AllTimeRange = []TimeRange{
	TimeRangeLast1h,
	TimeRangeLast2h,
	TimeRangeLast24h,
	TimeRangeLast7d,
	TimeRangeLast30d,
}

func (e TimeRange) IsValid() bool {
	switch e {
	case TimeRangeLast1h, TimeRangeLast2h, TimeRangeLast24h, TimeRangeLast7d, TimeRangeLast30d:
		return true
	}
	return false
}

func (e TimeRange) String() string {
	return string(e)
}

func (e *TimeRange) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeRange(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeRange", str)
	}
	return nil
}

func (e TimeRange) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeRange) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeRange) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
