// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AllocatedSlot struct {
	Index    int                         `json:"index"`
	JobID    string                      `json:"jobId"`
	Resource *TaskManagerResourceProfile `json:"resource"`
}

type BackPressureInfo struct {
	Status            string                 `json:"status"`
	BackpressureLevel string                 `json:"backpressureLevel"`
	EndTimestamp      string                 `json:"endTimestamp"`
	Subtasks          []*SubtaskBackPressure `json:"subtasks"`
}

type BlueGreenDeployment struct {
	Name                     string         `json:"name"`
	Namespace                string         `json:"namespace"`
	State                    BlueGreenState `json:"state"`
	JobStatus                *string        `json:"jobStatus,omitempty"`
	Error                    *string        `json:"error,omitempty"`
	LastReconciledTimestamp  *string        `json:"lastReconciledTimestamp,omitempty"`
	AbortTimestamp           *string        `json:"abortTimestamp,omitempty"`
	DeploymentReadyTimestamp *string        `json:"deploymentReadyTimestamp,omitempty"`
	BlueDeploymentName       *string        `json:"blueDeploymentName,omitempty"`
	GreenDeploymentName      *string        `json:"greenDeploymentName,omitempty"`
	ActiveJobID              *string        `json:"activeJobId,omitempty"`
	PendingJobID             *string        `json:"pendingJobId,omitempty"`
	AbortGracePeriod         *string        `json:"abortGracePeriod,omitempty"`
	DeploymentDeletionDelay  *string        `json:"deploymentDeletionDelay,omitempty"`
}

type CancelJobResult struct {
	Success bool `json:"success"`
}

type CheckpointConfig struct {
	Mode                             string `json:"mode"`
	Interval                         string `json:"interval"`
	Timeout                          string `json:"timeout"`
	MinPause                         string `json:"minPause"`
	MaxConcurrent                    int    `json:"maxConcurrent"`
	ExternalizedEnabled              bool   `json:"externalizedEnabled"`
	ExternalizedDeleteOnCancellation bool   `json:"externalizedDeleteOnCancellation"`
	UnalignedCheckpoints             bool   `json:"unalignedCheckpoints"`
}

type CheckpointCounts struct {
	Completed  int `json:"completed"`
	InProgress int `json:"inProgress"`
	Failed     int `json:"failed"`
	Total      int `json:"total"`
	Restored   int `json:"restored"`
}

type CheckpointHistoryEntry struct {
	ID                      string  `json:"id"`
	Status                  string  `json:"status"`
	IsSavepoint             bool    `json:"isSavepoint"`
	TriggerTimestamp        string  `json:"triggerTimestamp"`
	LatestAckTimestamp      string  `json:"latestAckTimestamp"`
	StateSize               string  `json:"stateSize"`
	EndToEndDuration        string  `json:"endToEndDuration"`
	ProcessedData           string  `json:"processedData"`
	PersistedData           string  `json:"persistedData"`
	NumSubtasks             int     `json:"numSubtasks"`
	NumAcknowledgedSubtasks int     `json:"numAcknowledgedSubtasks"`
	CheckpointedSize        *string `json:"checkpointedSize,omitempty"`
}

type CheckpointLatest struct {
	Completed *CheckpointHistoryEntry `json:"completed,omitempty"`
	Failed    *CheckpointHistoryEntry `json:"failed,omitempty"`
	Savepoint *CheckpointHistoryEntry `json:"savepoint,omitempty"`
	Restored  *CheckpointRestoredInfo `json:"restored,omitempty"`
}

type CheckpointMinMaxAvg struct {
	Min string `json:"min"`
	Max string `json:"max"`
	Avg string `json:"avg"`
}

type CheckpointRestoredInfo struct {
	ID               string  `json:"id"`
	RestoreTimestamp string  `json:"restoreTimestamp"`
	IsSavepoint      bool    `json:"isSavepoint"`
	ExternalPath     *string `json:"externalPath,omitempty"`
}

type CheckpointStats struct {
	Counts  *CheckpointCounts         `json:"counts"`
	History []*CheckpointHistoryEntry `json:"history"`
	Summary *CheckpointSummary        `json:"summary,omitempty"`
	Latest  *CheckpointLatest         `json:"latest,omitempty"`
}

type CheckpointSummary struct {
	StateSize        *CheckpointMinMaxAvg `json:"stateSize,omitempty"`
	EndToEndDuration *CheckpointMinMaxAvg `json:"endToEndDuration,omitempty"`
	CheckpointedSize *CheckpointMinMaxAvg `json:"checkpointedSize,omitempty"`
	ProcessedData    *CheckpointMinMaxAvg `json:"processedData,omitempty"`
	PersistedData    *CheckpointMinMaxAvg `json:"persistedData,omitempty"`
}

// Information about a registered Flink cluster connection.
type ClusterInfo struct {
	Name          string        `json:"name"`
	URL           string        `json:"url"`
	Status        ClusterStatus `json:"status"`
	LastCheckTime *string       `json:"lastCheckTime,omitempty"`
	Version       *string       `json:"version,omitempty"`
	Capabilities  []string      `json:"capabilities"`
}

type DashboardConfig struct {
	Clusters    []string `json:"clusters"`
	Instruments []string `json:"instruments"`
}

// A column in a database table.
type DatabaseColumn struct {
	Name         string `json:"name"`
	DataType     string `json:"dataType"`
	Nullable     bool   `json:"nullable"`
	DefaultValue string `json:"defaultValue"`
	IsPrimaryKey bool   `json:"isPrimaryKey"`
	Comment      string `json:"comment"`
}

// A constraint on a database table.
type DatabaseConstraint struct {
	Name       string   `json:"name"`
	Type       string   `json:"type"`
	Columns    []string `json:"columns"`
	RefTable   string   `json:"refTable"`
	RefColumns []string `json:"refColumns"`
}

// An index on a database table.
type DatabaseIndex struct {
	Name    string   `json:"name"`
	Columns []string `json:"columns"`
	Unique  bool     `json:"unique"`
	Type    string   `json:"type"`
}

// A recorded query execution in the history.
type DatabaseQueryHistoryEntry struct {
	SQL             string  `json:"sql"`
	ExecutedAt      string  `json:"executedAt"`
	ExecutionTimeMs int     `json:"executionTimeMs"`
	RowCount        int     `json:"rowCount"`
	Error           *string `json:"error,omitempty"`
}

// Result of executing a database query.
type DatabaseQueryResult struct {
	Columns         []*DatabaseResultColumn `json:"columns"`
	Rows            [][]map[string]any      `json:"rows"`
	RowCount        int                     `json:"rowCount"`
	ExecutionTimeMs int                     `json:"executionTimeMs"`
	Truncated       bool                    `json:"truncated"`
}

// A column in a query result set.
type DatabaseResultColumn struct {
	Name     string `json:"name"`
	DataType string `json:"dataType"`
}

// A database schema (e.g., public, analytics).
type DatabaseSchema struct {
	Name       string `json:"name"`
	TableCount int    `json:"tableCount"`
}

// Detailed information about a database table.
type DatabaseTableDetail struct {
	Name        string                `json:"name"`
	Schema      string                `json:"schema"`
	Columns     []*DatabaseColumn     `json:"columns"`
	Indexes     []*DatabaseIndex      `json:"indexes"`
	Constraints []*DatabaseConstraint `json:"constraints"`
}

// Summary of a database table within a schema.
type DatabaseTableSummary struct {
	Name             string `json:"name"`
	Schema           string `json:"schema"`
	Type             string `json:"type"`
	RowCountEstimate int    `json:"rowCountEstimate"`
}

type DeleteResult struct {
	Success bool `json:"success"`
}

type ExceptionEntry struct {
	ExceptionName string  `json:"exceptionName"`
	Stacktrace    string  `json:"stacktrace"`
	Timestamp     string  `json:"timestamp"`
	TaskName      *string `json:"taskName,omitempty"`
	Endpoint      *string `json:"endpoint,omitempty"`
	TaskManagerID *string `json:"taskManagerId,omitempty"`
}

type Flamegraph struct {
	EndTimestamp string          `json:"endTimestamp"`
	Data         *FlamegraphNode `json:"data"`
}

type FlamegraphNode struct {
	Name     string            `json:"name"`
	Value    string            `json:"value"`
	Children []*FlamegraphNode `json:"children,omitempty"`
}

type FlinkConfig struct {
	RefreshInterval int            `json:"refreshInterval"`
	TimezoneName    string         `json:"timezoneName"`
	TimezoneOffset  string         `json:"timezoneOffset"`
	FlinkVersion    string         `json:"flinkVersion"`
	FlinkRevision   string         `json:"flinkRevision"`
	Features        *FlinkFeatures `json:"features"`
}

type FlinkFeatures struct {
	WebSubmit  bool `json:"webSubmit"`
	WebCancel  bool `json:"webCancel"`
	WebRescale bool `json:"webRescale"`
	WebHistory bool `json:"webHistory"`
}

// Information about a registered infrastructure instrument.
type InstrumentInfo struct {
	Name            string   `json:"name"`
	DisplayName     string   `json:"displayName"`
	Type            string   `json:"type"`
	Version         string   `json:"version"`
	Healthy         bool     `json:"healthy"`
	LastHealthCheck *string  `json:"lastHealthCheck,omitempty"`
	Capabilities    []string `json:"capabilities"`
}

type JMConfigEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type JMEnvironment struct {
	Jvm       *JMEnvironmentJvm `json:"jvm"`
	Classpath []string          `json:"classpath"`
}

type JMEnvironmentJvm struct {
	Version string   `json:"version"`
	Arch    string   `json:"arch"`
	Options []string `json:"options"`
}

type JarEntryPoint struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type JarFile struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Uploaded string           `json:"uploaded"`
	Entry    []*JarEntryPoint `json:"entry"`
}

type JarRunResult struct {
	JobID string `json:"jobId"`
}

type JarUploadResult struct {
	Filename string `json:"filename"`
	Status   string `json:"status"`
}

type JobDetail struct {
	ID               string                `json:"id"`
	Name             string                `json:"name"`
	State            string                `json:"state"`
	StartTime        string                `json:"startTime"`
	EndTime          string                `json:"endTime"`
	Duration         string                `json:"duration"`
	Now              string                `json:"now"`
	Vertices         []*JobVertex          `json:"vertices"`
	Plan             *JobPlan              `json:"plan"`
	Exceptions       []*ExceptionEntry     `json:"exceptions"`
	Checkpoints      *CheckpointStats      `json:"checkpoints,omitempty"`
	CheckpointConfig *CheckpointConfig     `json:"checkpointConfig,omitempty"`
	VertexDetails    []*VertexDetail       `json:"vertexDetails,omitempty"`
	Watermarks       []*VertexWatermarks   `json:"watermarks,omitempty"`
	BackPressure     []*VertexBackPressure `json:"backPressure,omitempty"`
	Accumulators     []*VertexAccumulators `json:"accumulators,omitempty"`
}

type JobManagerDetail struct {
	Config      []*JMConfigEntry `json:"config"`
	Environment *JMEnvironment   `json:"environment,omitempty"`
	Metrics     []*MetricEntry   `json:"metrics"`
}

type JobOverview struct {
	ID               string      `json:"id"`
	Name             string      `json:"name"`
	State            string      `json:"state"`
	StartTime        string      `json:"startTime"`
	EndTime          string      `json:"endTime"`
	Duration         string      `json:"duration"`
	LastModification string      `json:"lastModification"`
	Tasks            *TaskCounts `json:"tasks"`
}

type JobPlan struct {
	Jid   string      `json:"jid"`
	Name  string      `json:"name"`
	Type  string      `json:"type"`
	Nodes []*PlanNode `json:"nodes"`
}

// A job status transition event emitted when a Flink job changes state.
type JobStatusEvent struct {
	JobID          string  `json:"jobId"`
	JobName        string  `json:"jobName"`
	PreviousStatus *string `json:"previousStatus,omitempty"`
	CurrentStatus  string  `json:"currentStatus"`
	Cluster        string  `json:"cluster"`
}

type JobVertex struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	MaxParallelism int            `json:"maxParallelism"`
	Parallelism    int            `json:"parallelism"`
	Status         string         `json:"status"`
	StartTime      string         `json:"startTime"`
	EndTime        string         `json:"endTime"`
	Duration       string         `json:"duration"`
	Tasks          *TaskCounts    `json:"tasks"`
	Metrics        *VertexMetrics `json:"metrics"`
}

// A Kafka topic or broker configuration entry.
type KafkaConfigEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Summary of a Kafka consumer group.
type KafkaConsumerGroup struct {
	GroupID     string `json:"groupId"`
	State       string `json:"state"`
	MemberCount int    `json:"memberCount"`
	TotalLag    int    `json:"totalLag"`
}

// Detailed information about a Kafka consumer group.
type KafkaConsumerGroupDetail struct {
	GroupID      string                  `json:"groupId"`
	State        string                  `json:"state"`
	Protocol     string                  `json:"protocol"`
	ProtocolType string                  `json:"protocolType"`
	Members      []*KafkaGroupMember     `json:"members"`
	Offsets      []*KafkaPartitionOffset `json:"offsets"`
}

// A member of a Kafka consumer group.
type KafkaGroupMember struct {
	ClientID    string                 `json:"clientId"`
	ClientHost  string                 `json:"clientHost"`
	Assignments []*KafkaTopicPartition `json:"assignments"`
}

// A single partition within a Kafka topic.
type KafkaPartition struct {
	ID             int   `json:"id"`
	Leader         int   `json:"leader"`
	Replicas       []int `json:"replicas"`
	InSyncReplicas []int `json:"inSyncReplicas"`
}

// Per-partition offset and lag for a consumer group.
type KafkaPartitionOffset struct {
	Topic           string `json:"topic"`
	Partition       int    `json:"partition"`
	CommittedOffset int    `json:"committedOffset"`
	EndOffset       int    `json:"endOffset"`
	Lag             int    `json:"lag"`
}

// Summary of a Kafka topic.
type KafkaTopic struct {
	Name              string `json:"name"`
	PartitionCount    int    `json:"partitionCount"`
	ReplicationFactor int    `json:"replicationFactor"`
	Internal          bool   `json:"internal"`
}

// Detailed information about a Kafka topic including partitions and config.
type KafkaTopicDetail struct {
	Name              string              `json:"name"`
	PartitionCount    int                 `json:"partitionCount"`
	ReplicationFactor int                 `json:"replicationFactor"`
	Internal          bool                `json:"internal"`
	Partitions        []*KafkaPartition   `json:"partitions"`
	ConfigEntries     []*KafkaConfigEntry `json:"configEntries"`
	MessageCount      int                 `json:"messageCount"`
}

// A topic-partition assignment.
type KafkaTopicPartition struct {
	Topic     string `json:"topic"`
	Partition int    `json:"partition"`
}

type MaterializedTable struct {
	Name          string                         `json:"name"`
	Catalog       string                         `json:"catalog"`
	Database      string                         `json:"database"`
	RefreshStatus MaterializedTableRefreshStatus `json:"refreshStatus"`
	RefreshMode   *string                        `json:"refreshMode,omitempty"`
	Freshness     *string                        `json:"freshness,omitempty"`
	DefiningQuery *string                        `json:"definingQuery,omitempty"`
}

type MetricEntry struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

type Mutation struct {
}

type PlanNode struct {
	ID               string           `json:"id"`
	Parallelism      int              `json:"parallelism"`
	Operator         string           `json:"operator"`
	OperatorStrategy string           `json:"operatorStrategy"`
	Description      string           `json:"description"`
	Inputs           []*PlanNodeInput `json:"inputs,omitempty"`
}

type PlanNodeInput struct {
	Num          int    `json:"num"`
	ID           string `json:"id"`
	ShipStrategy string `json:"shipStrategy"`
	Exchange     string `json:"exchange"`
}

type Query struct {
}

type SQLCloseResult struct {
	Success bool `json:"success"`
}

// A column descriptor from SQL Gateway results.
type SQLColumn struct {
	Name     string `json:"name"`
	DataType string `json:"dataType"`
}

type SQLFetchResult struct {
	Columns   []*SQLColumn `json:"columns"`
	Rows      [][]*string  `json:"rows"`
	HasMore   bool         `json:"hasMore"`
	NextToken *string      `json:"nextToken,omitempty"`
}

// A batch of SQL Gateway query results.
type SQLResultBatch struct {
	Columns []*SQLColumn `json:"columns"`
	Rows    [][]*string  `json:"rows"`
	HasMore bool         `json:"hasMore"`
}

type SQLSessionResult struct {
	SessionHandle string `json:"sessionHandle"`
}

type SQLStatementResult struct {
	OperationHandle string `json:"operationHandle"`
}

type Subscription struct {
}

type SubtaskBackPressure struct {
	Subtask           int     `json:"subtask"`
	AttemptNumber     int     `json:"attemptNumber"`
	BackpressureLevel string  `json:"backpressureLevel"`
	Ratio             float64 `json:"ratio"`
	BusyRatio         float64 `json:"busyRatio"`
	IdleRatio         float64 `json:"idleRatio"`
}

type SubtaskInfo struct {
	Subtask       int            `json:"subtask"`
	Status        string         `json:"status"`
	Attempt       int            `json:"attempt"`
	Endpoint      string         `json:"endpoint"`
	StartTime     string         `json:"startTime"`
	EndTime       string         `json:"endTime"`
	Duration      string         `json:"duration"`
	Metrics       *VertexMetrics `json:"metrics"`
	TaskManagerID string         `json:"taskManagerId"`
}

type SubtaskTimes struct {
	ID       string               `json:"id"`
	Name     string               `json:"name"`
	Now      string               `json:"now"`
	Subtasks []*SubtaskTimesEntry `json:"subtasks"`
}

type SubtaskTimesEntry struct {
	Subtask    int               `json:"subtask"`
	Host       string            `json:"host"`
	Duration   string            `json:"duration"`
	Timestamps []*TimestampEntry `json:"timestamps"`
}

type TMLogEntry struct {
	Name string `json:"name"`
	Size string `json:"size"`
}

type TapManifest struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Version     string         `json:"version"`
	Config      map[string]any `json:"config,omitempty"`
}

type TaskCounts struct {
	Created      int `json:"created"`
	Scheduled    int `json:"scheduled"`
	Deploying    int `json:"deploying"`
	Running      int `json:"running"`
	Finished     int `json:"finished"`
	Canceling    int `json:"canceling"`
	Canceled     int `json:"canceled"`
	Failed       int `json:"failed"`
	Reconciling  int `json:"reconciling"`
	Initializing int `json:"initializing"`
}

type TaskManagerDetail struct {
	ID                     string                      `json:"id"`
	Path                   string                      `json:"path"`
	DataPort               int                         `json:"dataPort"`
	JmxPort                int                         `json:"jmxPort"`
	TimeSinceLastHeartbeat string                      `json:"timeSinceLastHeartbeat"`
	SlotsNumber            int                         `json:"slotsNumber"`
	FreeSlots              int                         `json:"freeSlots"`
	TotalResource          *TaskManagerResourceProfile `json:"totalResource"`
	FreeResource           *TaskManagerResourceProfile `json:"freeResource"`
	Hardware               *TaskManagerHardware        `json:"hardware"`
	MemoryConfiguration    *TaskManagerMemory          `json:"memoryConfiguration"`
	AllocatedSlots         []*AllocatedSlot            `json:"allocatedSlots"`
	Metrics                []*MetricEntry              `json:"metrics"`
}

type TaskManagerHardware struct {
	CPUCores       int    `json:"cpuCores"`
	PhysicalMemory string `json:"physicalMemory"`
	FreeMemory     string `json:"freeMemory"`
	ManagedMemory  string `json:"managedMemory"`
}

type TaskManagerMemory struct {
	FrameworkHeap      string `json:"frameworkHeap"`
	TaskHeap           string `json:"taskHeap"`
	FrameworkOffHeap   string `json:"frameworkOffHeap"`
	TaskOffHeap        string `json:"taskOffHeap"`
	NetworkMemory      string `json:"networkMemory"`
	ManagedMemory      string `json:"managedMemory"`
	JvmMetaspace       string `json:"jvmMetaspace"`
	JvmOverhead        string `json:"jvmOverhead"`
	TotalFlinkMemory   string `json:"totalFlinkMemory"`
	TotalProcessMemory string `json:"totalProcessMemory"`
}

type TaskManagerOverview struct {
	ID                     string                      `json:"id"`
	Path                   string                      `json:"path"`
	DataPort               int                         `json:"dataPort"`
	JmxPort                int                         `json:"jmxPort"`
	TimeSinceLastHeartbeat string                      `json:"timeSinceLastHeartbeat"`
	SlotsNumber            int                         `json:"slotsNumber"`
	FreeSlots              int                         `json:"freeSlots"`
	TotalResource          *TaskManagerResourceProfile `json:"totalResource"`
	FreeResource           *TaskManagerResourceProfile `json:"freeResource"`
	Hardware               *TaskManagerHardware        `json:"hardware"`
	MemoryConfiguration    *TaskManagerMemory          `json:"memoryConfiguration"`
}

type TaskManagerResourceProfile struct {
	CPUCores          float64 `json:"cpuCores"`
	TaskHeapMemory    string  `json:"taskHeapMemory"`
	TaskOffHeapMemory string  `json:"taskOffHeapMemory"`
	ManagedMemory     string  `json:"managedMemory"`
	NetworkMemory     string  `json:"networkMemory"`
}

type ThreadDumpEntry struct {
	ThreadName            string `json:"threadName"`
	StringifiedThreadInfo string `json:"stringifiedThreadInfo"`
}

type TimestampEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UserAccumulator struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type VertexAccumulators struct {
	VertexID     string             `json:"vertexId"`
	Accumulators []*UserAccumulator `json:"accumulators"`
}

type VertexBackPressure struct {
	VertexID     string            `json:"vertexId"`
	BackPressure *BackPressureInfo `json:"backPressure"`
}

type VertexDetail struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Parallelism int            `json:"parallelism"`
	Now         string         `json:"now"`
	Subtasks    []*SubtaskInfo `json:"subtasks"`
}

type VertexMetrics struct {
	ReadBytes                string `json:"readBytes"`
	ReadBytesComplete        bool   `json:"readBytesComplete"`
	WriteBytes               string `json:"writeBytes"`
	WriteBytesComplete       bool   `json:"writeBytesComplete"`
	ReadRecords              string `json:"readRecords"`
	ReadRecordsComplete      bool   `json:"readRecordsComplete"`
	WriteRecords             string `json:"writeRecords"`
	WriteRecordsComplete     bool   `json:"writeRecordsComplete"`
	AccumulatedBackpressured string `json:"accumulatedBackpressured"`
	AccumulatedIdle          string `json:"accumulatedIdle"`
	AccumulatedBusy          string `json:"accumulatedBusy"`
}

type VertexWatermarks struct {
	VertexID   string            `json:"vertexId"`
	Watermarks []*WatermarkEntry `json:"watermarks"`
}

type WatermarkEntry struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

type BlueGreenState string

const (
	BlueGreenStateInitializingBlue     BlueGreenState = "INITIALIZING_BLUE"
	BlueGreenStateActiveBlue           BlueGreenState = "ACTIVE_BLUE"
	BlueGreenStateActiveGreen          BlueGreenState = "ACTIVE_GREEN"
	BlueGreenStateSavepointingBlue     BlueGreenState = "SAVEPOINTING_BLUE"
	BlueGreenStateSavepointingGreen    BlueGreenState = "SAVEPOINTING_GREEN"
	BlueGreenStateTransitioningToBlue  BlueGreenState = "TRANSITIONING_TO_BLUE"
	BlueGreenStateTransitioningToGreen BlueGreenState = "TRANSITIONING_TO_GREEN"
)

var AllBlueGreenState = []BlueGreenState{
	BlueGreenStateInitializingBlue,
	BlueGreenStateActiveBlue,
	BlueGreenStateActiveGreen,
	BlueGreenStateSavepointingBlue,
	BlueGreenStateSavepointingGreen,
	BlueGreenStateTransitioningToBlue,
	BlueGreenStateTransitioningToGreen,
}

func (e BlueGreenState) IsValid() bool {
	switch e {
	case BlueGreenStateInitializingBlue, BlueGreenStateActiveBlue, BlueGreenStateActiveGreen, BlueGreenStateSavepointingBlue, BlueGreenStateSavepointingGreen, BlueGreenStateTransitioningToBlue, BlueGreenStateTransitioningToGreen:
		return true
	}
	return false
}

func (e BlueGreenState) String() string {
	return string(e)
}

func (e *BlueGreenState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlueGreenState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlueGreenState", str)
	}
	return nil
}

func (e BlueGreenState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BlueGreenState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BlueGreenState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Health status of a registered Flink cluster.
type ClusterStatus string

const (
	ClusterStatusHealthy   ClusterStatus = "HEALTHY"
	ClusterStatusUnhealthy ClusterStatus = "UNHEALTHY"
	ClusterStatusUnknown   ClusterStatus = "UNKNOWN"
)

var AllClusterStatus = []ClusterStatus{
	ClusterStatusHealthy,
	ClusterStatusUnhealthy,
	ClusterStatusUnknown,
}

func (e ClusterStatus) IsValid() bool {
	switch e {
	case ClusterStatusHealthy, ClusterStatusUnhealthy, ClusterStatusUnknown:
		return true
	}
	return false
}

func (e ClusterStatus) String() string {
	return string(e)
}

func (e *ClusterStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClusterStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClusterStatus", str)
	}
	return nil
}

func (e ClusterStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClusterStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClusterStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MaterializedTableRefreshStatus string

const (
	MaterializedTableRefreshStatusActivated    MaterializedTableRefreshStatus = "ACTIVATED"
	MaterializedTableRefreshStatusSuspended    MaterializedTableRefreshStatus = "SUSPENDED"
	MaterializedTableRefreshStatusInitializing MaterializedTableRefreshStatus = "INITIALIZING"
)

var AllMaterializedTableRefreshStatus = []MaterializedTableRefreshStatus{
	MaterializedTableRefreshStatusActivated,
	MaterializedTableRefreshStatusSuspended,
	MaterializedTableRefreshStatusInitializing,
}

func (e MaterializedTableRefreshStatus) IsValid() bool {
	switch e {
	case MaterializedTableRefreshStatusActivated, MaterializedTableRefreshStatusSuspended, MaterializedTableRefreshStatusInitializing:
		return true
	}
	return false
}

func (e MaterializedTableRefreshStatus) String() string {
	return string(e)
}

func (e *MaterializedTableRefreshStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MaterializedTableRefreshStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MaterializedTableRefreshStatus", str)
	}
	return nil
}

func (e MaterializedTableRefreshStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MaterializedTableRefreshStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MaterializedTableRefreshStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
