/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SharedIndexRouteImport } from './routes/shared/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as PrimitivesIndexRouteImport } from './routes/primitives/index'
import { Route as DomainIndexRouteImport } from './routes/domain/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimitivesIndexRoute = PrimitivesIndexRouteImport.update({
  id: '/primitives/',
  path: '/primitives/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainIndexRoute = DomainIndexRouteImport.update({
  id: '/domain/',
  path: '/domain/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domain/': typeof DomainIndexRoute
  '/primitives/': typeof PrimitivesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domain': typeof DomainIndexRoute
  '/primitives': typeof PrimitivesIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/shared': typeof SharedIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domain/': typeof DomainIndexRoute
  '/primitives/': typeof PrimitivesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domain/'
    | '/primitives/'
    | '/scenarios/'
    | '/shared/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/domain' | '/primitives' | '/scenarios' | '/shared' | '/templates'
  id:
    | '__root__'
    | '/'
    | '/domain/'
    | '/primitives/'
    | '/scenarios/'
    | '/shared/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainIndexRoute: typeof DomainIndexRoute
  PrimitivesIndexRoute: typeof PrimitivesIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  SharedIndexRoute: typeof SharedIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/': {
      id: '/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primitives/': {
      id: '/primitives/'
      path: '/primitives'
      fullPath: '/primitives/'
      preLoaderRoute: typeof PrimitivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/': {
      id: '/domain/'
      path: '/domain'
      fullPath: '/domain/'
      preLoaderRoute: typeof DomainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainIndexRoute: DomainIndexRoute,
  PrimitivesIndexRoute: PrimitivesIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  SharedIndexRoute: SharedIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
