/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SharedIndexRouteImport } from './routes/shared/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as PrimitivesIndexRouteImport } from './routes/primitives/index'
import { Route as DomainIndexRouteImport } from './routes/domain/index'
import { Route as TemplatesTaskManagersRouteImport } from './routes/templates/task-managers'
import { Route as TemplatesPlanAnalyzerRouteImport } from './routes/templates/plan-analyzer'
import { Route as TemplatesOverviewRouteImport } from './routes/templates/overview'
import { Route as TemplatesMonitoringRouteImport } from './routes/templates/monitoring'
import { Route as TemplatesMaterializedTablesRouteImport } from './routes/templates/materialized-tables'
import { Route as TemplatesLogsRouteImport } from './routes/templates/logs'
import { Route as TemplatesJobsRouteImport } from './routes/templates/jobs'
import { Route as TemplatesJobManagerRouteImport } from './routes/templates/job-manager'
import { Route as TemplatesInsightsRouteImport } from './routes/templates/insights'
import { Route as TemplatesErrorsRouteImport } from './routes/templates/errors'
import { Route as TemplatesDeploymentsRouteImport } from './routes/templates/deployments'
import { Route as TemplatesCatalogsRouteImport } from './routes/templates/catalogs'
import { Route as ScenariosHealthyRouteImport } from './routes/scenarios/healthy'
import { Route as ScenariosFailingRouteImport } from './routes/scenarios/failing'
import { Route as ScenariosEmptyRouteImport } from './routes/scenarios/empty'
import { Route as ScenariosDegradedRouteImport } from './routes/scenarios/degraded'
import { Route as DomainTapRouteImport } from './routes/domain/tap'
import { Route as DomainPlanAnalyzerRouteImport } from './routes/domain/plan-analyzer'
import { Route as DomainOverviewRouteImport } from './routes/domain/overview'
import { Route as DomainMonitoringRouteImport } from './routes/domain/monitoring'
import { Route as DomainMaterializedTablesRouteImport } from './routes/domain/materialized-tables'
import { Route as DomainLogsRouteImport } from './routes/domain/logs'
import { Route as DomainJobsRouteImport } from './routes/domain/jobs'
import { Route as DomainInsightsRouteImport } from './routes/domain/insights'
import { Route as DomainErrorsRouteImport } from './routes/domain/errors'
import { Route as DomainCatalogsRouteImport } from './routes/domain/catalogs'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScenariosRoute,
} as any)
const PrimitivesIndexRoute = PrimitivesIndexRouteImport.update({
  id: '/primitives/',
  path: '/primitives/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainIndexRoute = DomainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainRoute,
} as any)
const TemplatesTaskManagersRoute = TemplatesTaskManagersRouteImport.update({
  id: '/task-managers',
  path: '/task-managers',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesPlanAnalyzerRoute = TemplatesPlanAnalyzerRouteImport.update({
  id: '/plan-analyzer',
  path: '/plan-analyzer',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesOverviewRoute = TemplatesOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesMonitoringRoute = TemplatesMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesMaterializedTablesRoute =
  TemplatesMaterializedTablesRouteImport.update({
    id: '/materialized-tables',
    path: '/materialized-tables',
    getParentRoute: () => TemplatesRoute,
  } as any)
const TemplatesLogsRoute = TemplatesLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesJobsRoute = TemplatesJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesJobManagerRoute = TemplatesJobManagerRouteImport.update({
  id: '/job-manager',
  path: '/job-manager',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesInsightsRoute = TemplatesInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesErrorsRoute = TemplatesErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesDeploymentsRoute = TemplatesDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesCatalogsRoute = TemplatesCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => TemplatesRoute,
} as any)
const ScenariosHealthyRoute = ScenariosHealthyRouteImport.update({
  id: '/healthy',
  path: '/healthy',
  getParentRoute: () => ScenariosRoute,
} as any)
const ScenariosFailingRoute = ScenariosFailingRouteImport.update({
  id: '/failing',
  path: '/failing',
  getParentRoute: () => ScenariosRoute,
} as any)
const ScenariosEmptyRoute = ScenariosEmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => ScenariosRoute,
} as any)
const ScenariosDegradedRoute = ScenariosDegradedRouteImport.update({
  id: '/degraded',
  path: '/degraded',
  getParentRoute: () => ScenariosRoute,
} as any)
const DomainTapRoute = DomainTapRouteImport.update({
  id: '/tap',
  path: '/tap',
  getParentRoute: () => DomainRoute,
} as any)
const DomainPlanAnalyzerRoute = DomainPlanAnalyzerRouteImport.update({
  id: '/plan-analyzer',
  path: '/plan-analyzer',
  getParentRoute: () => DomainRoute,
} as any)
const DomainOverviewRoute = DomainOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DomainRoute,
} as any)
const DomainMonitoringRoute = DomainMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DomainRoute,
} as any)
const DomainMaterializedTablesRoute =
  DomainMaterializedTablesRouteImport.update({
    id: '/materialized-tables',
    path: '/materialized-tables',
    getParentRoute: () => DomainRoute,
  } as any)
const DomainLogsRoute = DomainLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DomainRoute,
} as any)
const DomainJobsRoute = DomainJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DomainRoute,
} as any)
const DomainInsightsRoute = DomainInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DomainRoute,
} as any)
const DomainErrorsRoute = DomainErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DomainRoute,
} as any)
const DomainCatalogsRoute = DomainCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => DomainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domain': typeof DomainRouteWithChildren
  '/scenarios': typeof ScenariosRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/domain/catalogs': typeof DomainCatalogsRoute
  '/domain/errors': typeof DomainErrorsRoute
  '/domain/insights': typeof DomainInsightsRoute
  '/domain/jobs': typeof DomainJobsRoute
  '/domain/logs': typeof DomainLogsRoute
  '/domain/materialized-tables': typeof DomainMaterializedTablesRoute
  '/domain/monitoring': typeof DomainMonitoringRoute
  '/domain/overview': typeof DomainOverviewRoute
  '/domain/plan-analyzer': typeof DomainPlanAnalyzerRoute
  '/domain/tap': typeof DomainTapRoute
  '/scenarios/degraded': typeof ScenariosDegradedRoute
  '/scenarios/empty': typeof ScenariosEmptyRoute
  '/scenarios/failing': typeof ScenariosFailingRoute
  '/scenarios/healthy': typeof ScenariosHealthyRoute
  '/templates/catalogs': typeof TemplatesCatalogsRoute
  '/templates/deployments': typeof TemplatesDeploymentsRoute
  '/templates/errors': typeof TemplatesErrorsRoute
  '/templates/insights': typeof TemplatesInsightsRoute
  '/templates/job-manager': typeof TemplatesJobManagerRoute
  '/templates/jobs': typeof TemplatesJobsRoute
  '/templates/logs': typeof TemplatesLogsRoute
  '/templates/materialized-tables': typeof TemplatesMaterializedTablesRoute
  '/templates/monitoring': typeof TemplatesMonitoringRoute
  '/templates/overview': typeof TemplatesOverviewRoute
  '/templates/plan-analyzer': typeof TemplatesPlanAnalyzerRoute
  '/templates/task-managers': typeof TemplatesTaskManagersRoute
  '/domain/': typeof DomainIndexRoute
  '/primitives/': typeof PrimitivesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domain/catalogs': typeof DomainCatalogsRoute
  '/domain/errors': typeof DomainErrorsRoute
  '/domain/insights': typeof DomainInsightsRoute
  '/domain/jobs': typeof DomainJobsRoute
  '/domain/logs': typeof DomainLogsRoute
  '/domain/materialized-tables': typeof DomainMaterializedTablesRoute
  '/domain/monitoring': typeof DomainMonitoringRoute
  '/domain/overview': typeof DomainOverviewRoute
  '/domain/plan-analyzer': typeof DomainPlanAnalyzerRoute
  '/domain/tap': typeof DomainTapRoute
  '/scenarios/degraded': typeof ScenariosDegradedRoute
  '/scenarios/empty': typeof ScenariosEmptyRoute
  '/scenarios/failing': typeof ScenariosFailingRoute
  '/scenarios/healthy': typeof ScenariosHealthyRoute
  '/templates/catalogs': typeof TemplatesCatalogsRoute
  '/templates/deployments': typeof TemplatesDeploymentsRoute
  '/templates/errors': typeof TemplatesErrorsRoute
  '/templates/insights': typeof TemplatesInsightsRoute
  '/templates/job-manager': typeof TemplatesJobManagerRoute
  '/templates/jobs': typeof TemplatesJobsRoute
  '/templates/logs': typeof TemplatesLogsRoute
  '/templates/materialized-tables': typeof TemplatesMaterializedTablesRoute
  '/templates/monitoring': typeof TemplatesMonitoringRoute
  '/templates/overview': typeof TemplatesOverviewRoute
  '/templates/plan-analyzer': typeof TemplatesPlanAnalyzerRoute
  '/templates/task-managers': typeof TemplatesTaskManagersRoute
  '/domain': typeof DomainIndexRoute
  '/primitives': typeof PrimitivesIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/shared': typeof SharedIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domain': typeof DomainRouteWithChildren
  '/scenarios': typeof ScenariosRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/domain/catalogs': typeof DomainCatalogsRoute
  '/domain/errors': typeof DomainErrorsRoute
  '/domain/insights': typeof DomainInsightsRoute
  '/domain/jobs': typeof DomainJobsRoute
  '/domain/logs': typeof DomainLogsRoute
  '/domain/materialized-tables': typeof DomainMaterializedTablesRoute
  '/domain/monitoring': typeof DomainMonitoringRoute
  '/domain/overview': typeof DomainOverviewRoute
  '/domain/plan-analyzer': typeof DomainPlanAnalyzerRoute
  '/domain/tap': typeof DomainTapRoute
  '/scenarios/degraded': typeof ScenariosDegradedRoute
  '/scenarios/empty': typeof ScenariosEmptyRoute
  '/scenarios/failing': typeof ScenariosFailingRoute
  '/scenarios/healthy': typeof ScenariosHealthyRoute
  '/templates/catalogs': typeof TemplatesCatalogsRoute
  '/templates/deployments': typeof TemplatesDeploymentsRoute
  '/templates/errors': typeof TemplatesErrorsRoute
  '/templates/insights': typeof TemplatesInsightsRoute
  '/templates/job-manager': typeof TemplatesJobManagerRoute
  '/templates/jobs': typeof TemplatesJobsRoute
  '/templates/logs': typeof TemplatesLogsRoute
  '/templates/materialized-tables': typeof TemplatesMaterializedTablesRoute
  '/templates/monitoring': typeof TemplatesMonitoringRoute
  '/templates/overview': typeof TemplatesOverviewRoute
  '/templates/plan-analyzer': typeof TemplatesPlanAnalyzerRoute
  '/templates/task-managers': typeof TemplatesTaskManagersRoute
  '/domain/': typeof DomainIndexRoute
  '/primitives/': typeof PrimitivesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domain'
    | '/scenarios'
    | '/templates'
    | '/domain/catalogs'
    | '/domain/errors'
    | '/domain/insights'
    | '/domain/jobs'
    | '/domain/logs'
    | '/domain/materialized-tables'
    | '/domain/monitoring'
    | '/domain/overview'
    | '/domain/plan-analyzer'
    | '/domain/tap'
    | '/scenarios/degraded'
    | '/scenarios/empty'
    | '/scenarios/failing'
    | '/scenarios/healthy'
    | '/templates/catalogs'
    | '/templates/deployments'
    | '/templates/errors'
    | '/templates/insights'
    | '/templates/job-manager'
    | '/templates/jobs'
    | '/templates/logs'
    | '/templates/materialized-tables'
    | '/templates/monitoring'
    | '/templates/overview'
    | '/templates/plan-analyzer'
    | '/templates/task-managers'
    | '/domain/'
    | '/primitives/'
    | '/scenarios/'
    | '/shared/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/domain/catalogs'
    | '/domain/errors'
    | '/domain/insights'
    | '/domain/jobs'
    | '/domain/logs'
    | '/domain/materialized-tables'
    | '/domain/monitoring'
    | '/domain/overview'
    | '/domain/plan-analyzer'
    | '/domain/tap'
    | '/scenarios/degraded'
    | '/scenarios/empty'
    | '/scenarios/failing'
    | '/scenarios/healthy'
    | '/templates/catalogs'
    | '/templates/deployments'
    | '/templates/errors'
    | '/templates/insights'
    | '/templates/job-manager'
    | '/templates/jobs'
    | '/templates/logs'
    | '/templates/materialized-tables'
    | '/templates/monitoring'
    | '/templates/overview'
    | '/templates/plan-analyzer'
    | '/templates/task-managers'
    | '/domain'
    | '/primitives'
    | '/scenarios'
    | '/shared'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/domain'
    | '/scenarios'
    | '/templates'
    | '/domain/catalogs'
    | '/domain/errors'
    | '/domain/insights'
    | '/domain/jobs'
    | '/domain/logs'
    | '/domain/materialized-tables'
    | '/domain/monitoring'
    | '/domain/overview'
    | '/domain/plan-analyzer'
    | '/domain/tap'
    | '/scenarios/degraded'
    | '/scenarios/empty'
    | '/scenarios/failing'
    | '/scenarios/healthy'
    | '/templates/catalogs'
    | '/templates/deployments'
    | '/templates/errors'
    | '/templates/insights'
    | '/templates/job-manager'
    | '/templates/jobs'
    | '/templates/logs'
    | '/templates/materialized-tables'
    | '/templates/monitoring'
    | '/templates/overview'
    | '/templates/plan-analyzer'
    | '/templates/task-managers'
    | '/domain/'
    | '/primitives/'
    | '/scenarios/'
    | '/shared/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainRoute: typeof DomainRouteWithChildren
  ScenariosRoute: typeof ScenariosRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  PrimitivesIndexRoute: typeof PrimitivesIndexRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/shared/': {
      id: '/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/primitives/': {
      id: '/primitives/'
      path: '/primitives'
      fullPath: '/primitives/'
      preLoaderRoute: typeof PrimitivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/': {
      id: '/domain/'
      path: '/'
      fullPath: '/domain/'
      preLoaderRoute: typeof DomainIndexRouteImport
      parentRoute: typeof DomainRoute
    }
    '/templates/task-managers': {
      id: '/templates/task-managers'
      path: '/task-managers'
      fullPath: '/templates/task-managers'
      preLoaderRoute: typeof TemplatesTaskManagersRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/plan-analyzer': {
      id: '/templates/plan-analyzer'
      path: '/plan-analyzer'
      fullPath: '/templates/plan-analyzer'
      preLoaderRoute: typeof TemplatesPlanAnalyzerRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/overview': {
      id: '/templates/overview'
      path: '/overview'
      fullPath: '/templates/overview'
      preLoaderRoute: typeof TemplatesOverviewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/monitoring': {
      id: '/templates/monitoring'
      path: '/monitoring'
      fullPath: '/templates/monitoring'
      preLoaderRoute: typeof TemplatesMonitoringRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/materialized-tables': {
      id: '/templates/materialized-tables'
      path: '/materialized-tables'
      fullPath: '/templates/materialized-tables'
      preLoaderRoute: typeof TemplatesMaterializedTablesRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/logs': {
      id: '/templates/logs'
      path: '/logs'
      fullPath: '/templates/logs'
      preLoaderRoute: typeof TemplatesLogsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/jobs': {
      id: '/templates/jobs'
      path: '/jobs'
      fullPath: '/templates/jobs'
      preLoaderRoute: typeof TemplatesJobsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/job-manager': {
      id: '/templates/job-manager'
      path: '/job-manager'
      fullPath: '/templates/job-manager'
      preLoaderRoute: typeof TemplatesJobManagerRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/insights': {
      id: '/templates/insights'
      path: '/insights'
      fullPath: '/templates/insights'
      preLoaderRoute: typeof TemplatesInsightsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/errors': {
      id: '/templates/errors'
      path: '/errors'
      fullPath: '/templates/errors'
      preLoaderRoute: typeof TemplatesErrorsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/deployments': {
      id: '/templates/deployments'
      path: '/deployments'
      fullPath: '/templates/deployments'
      preLoaderRoute: typeof TemplatesDeploymentsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/catalogs': {
      id: '/templates/catalogs'
      path: '/catalogs'
      fullPath: '/templates/catalogs'
      preLoaderRoute: typeof TemplatesCatalogsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/scenarios/healthy': {
      id: '/scenarios/healthy'
      path: '/healthy'
      fullPath: '/scenarios/healthy'
      preLoaderRoute: typeof ScenariosHealthyRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/scenarios/failing': {
      id: '/scenarios/failing'
      path: '/failing'
      fullPath: '/scenarios/failing'
      preLoaderRoute: typeof ScenariosFailingRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/scenarios/empty': {
      id: '/scenarios/empty'
      path: '/empty'
      fullPath: '/scenarios/empty'
      preLoaderRoute: typeof ScenariosEmptyRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/scenarios/degraded': {
      id: '/scenarios/degraded'
      path: '/degraded'
      fullPath: '/scenarios/degraded'
      preLoaderRoute: typeof ScenariosDegradedRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/domain/tap': {
      id: '/domain/tap'
      path: '/tap'
      fullPath: '/domain/tap'
      preLoaderRoute: typeof DomainTapRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/plan-analyzer': {
      id: '/domain/plan-analyzer'
      path: '/plan-analyzer'
      fullPath: '/domain/plan-analyzer'
      preLoaderRoute: typeof DomainPlanAnalyzerRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/overview': {
      id: '/domain/overview'
      path: '/overview'
      fullPath: '/domain/overview'
      preLoaderRoute: typeof DomainOverviewRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/monitoring': {
      id: '/domain/monitoring'
      path: '/monitoring'
      fullPath: '/domain/monitoring'
      preLoaderRoute: typeof DomainMonitoringRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/materialized-tables': {
      id: '/domain/materialized-tables'
      path: '/materialized-tables'
      fullPath: '/domain/materialized-tables'
      preLoaderRoute: typeof DomainMaterializedTablesRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/logs': {
      id: '/domain/logs'
      path: '/logs'
      fullPath: '/domain/logs'
      preLoaderRoute: typeof DomainLogsRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/jobs': {
      id: '/domain/jobs'
      path: '/jobs'
      fullPath: '/domain/jobs'
      preLoaderRoute: typeof DomainJobsRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/insights': {
      id: '/domain/insights'
      path: '/insights'
      fullPath: '/domain/insights'
      preLoaderRoute: typeof DomainInsightsRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/errors': {
      id: '/domain/errors'
      path: '/errors'
      fullPath: '/domain/errors'
      preLoaderRoute: typeof DomainErrorsRouteImport
      parentRoute: typeof DomainRoute
    }
    '/domain/catalogs': {
      id: '/domain/catalogs'
      path: '/catalogs'
      fullPath: '/domain/catalogs'
      preLoaderRoute: typeof DomainCatalogsRouteImport
      parentRoute: typeof DomainRoute
    }
  }
}

interface DomainRouteChildren {
  DomainCatalogsRoute: typeof DomainCatalogsRoute
  DomainErrorsRoute: typeof DomainErrorsRoute
  DomainInsightsRoute: typeof DomainInsightsRoute
  DomainJobsRoute: typeof DomainJobsRoute
  DomainLogsRoute: typeof DomainLogsRoute
  DomainMaterializedTablesRoute: typeof DomainMaterializedTablesRoute
  DomainMonitoringRoute: typeof DomainMonitoringRoute
  DomainOverviewRoute: typeof DomainOverviewRoute
  DomainPlanAnalyzerRoute: typeof DomainPlanAnalyzerRoute
  DomainTapRoute: typeof DomainTapRoute
  DomainIndexRoute: typeof DomainIndexRoute
}

const DomainRouteChildren: DomainRouteChildren = {
  DomainCatalogsRoute: DomainCatalogsRoute,
  DomainErrorsRoute: DomainErrorsRoute,
  DomainInsightsRoute: DomainInsightsRoute,
  DomainJobsRoute: DomainJobsRoute,
  DomainLogsRoute: DomainLogsRoute,
  DomainMaterializedTablesRoute: DomainMaterializedTablesRoute,
  DomainMonitoringRoute: DomainMonitoringRoute,
  DomainOverviewRoute: DomainOverviewRoute,
  DomainPlanAnalyzerRoute: DomainPlanAnalyzerRoute,
  DomainTapRoute: DomainTapRoute,
  DomainIndexRoute: DomainIndexRoute,
}

const DomainRouteWithChildren =
  DomainRoute._addFileChildren(DomainRouteChildren)

interface ScenariosRouteChildren {
  ScenariosDegradedRoute: typeof ScenariosDegradedRoute
  ScenariosEmptyRoute: typeof ScenariosEmptyRoute
  ScenariosFailingRoute: typeof ScenariosFailingRoute
  ScenariosHealthyRoute: typeof ScenariosHealthyRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
}

const ScenariosRouteChildren: ScenariosRouteChildren = {
  ScenariosDegradedRoute: ScenariosDegradedRoute,
  ScenariosEmptyRoute: ScenariosEmptyRoute,
  ScenariosFailingRoute: ScenariosFailingRoute,
  ScenariosHealthyRoute: ScenariosHealthyRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
}

const ScenariosRouteWithChildren = ScenariosRoute._addFileChildren(
  ScenariosRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesCatalogsRoute: typeof TemplatesCatalogsRoute
  TemplatesDeploymentsRoute: typeof TemplatesDeploymentsRoute
  TemplatesErrorsRoute: typeof TemplatesErrorsRoute
  TemplatesInsightsRoute: typeof TemplatesInsightsRoute
  TemplatesJobManagerRoute: typeof TemplatesJobManagerRoute
  TemplatesJobsRoute: typeof TemplatesJobsRoute
  TemplatesLogsRoute: typeof TemplatesLogsRoute
  TemplatesMaterializedTablesRoute: typeof TemplatesMaterializedTablesRoute
  TemplatesMonitoringRoute: typeof TemplatesMonitoringRoute
  TemplatesOverviewRoute: typeof TemplatesOverviewRoute
  TemplatesPlanAnalyzerRoute: typeof TemplatesPlanAnalyzerRoute
  TemplatesTaskManagersRoute: typeof TemplatesTaskManagersRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesCatalogsRoute: TemplatesCatalogsRoute,
  TemplatesDeploymentsRoute: TemplatesDeploymentsRoute,
  TemplatesErrorsRoute: TemplatesErrorsRoute,
  TemplatesInsightsRoute: TemplatesInsightsRoute,
  TemplatesJobManagerRoute: TemplatesJobManagerRoute,
  TemplatesJobsRoute: TemplatesJobsRoute,
  TemplatesLogsRoute: TemplatesLogsRoute,
  TemplatesMaterializedTablesRoute: TemplatesMaterializedTablesRoute,
  TemplatesMonitoringRoute: TemplatesMonitoringRoute,
  TemplatesOverviewRoute: TemplatesOverviewRoute,
  TemplatesPlanAnalyzerRoute: TemplatesPlanAnalyzerRoute,
  TemplatesTaskManagersRoute: TemplatesTaskManagersRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainRoute: DomainRouteWithChildren,
  ScenariosRoute: ScenariosRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  PrimitivesIndexRoute: PrimitivesIndexRoute,
  SharedIndexRoute: SharedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
