/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as JobManagerRouteImport } from './routes/job-manager'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskManagersIndexRouteImport } from './routes/task-managers/index'
import { Route as SandboxIndexRouteImport } from './routes/sandbox/index'
import { Route as MaterializedTablesIndexRouteImport } from './routes/materialized-tables/index'
import { Route as InstrumentsIndexRouteImport } from './routes/instruments/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments/index'
import { Route as CatalogsIndexRouteImport } from './routes/catalogs/index'
import { Route as TaskManagersIdRouteImport } from './routes/task-managers/$id'
import { Route as SandboxEditorRouteImport } from './routes/sandbox/editor'
import { Route as MonitoringCheckpointsRouteImport } from './routes/monitoring/checkpoints'
import { Route as MonitoringAlertsRouteImport } from './routes/monitoring/alerts'
import { Route as MaterializedTablesNameRouteImport } from './routes/materialized-tables/$name'
import { Route as JobsSubmitRouteImport } from './routes/jobs/submit'
import { Route as JobsRunningRouteImport } from './routes/jobs/running'
import { Route as JobsCompletedRouteImport } from './routes/jobs/completed'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as InstrumentsInstrumentNameRouteImport } from './routes/instruments/$instrumentName'
import { Route as InsightsMetricsRouteImport } from './routes/insights/metrics'
import { Route as InsightsHealthRouteImport } from './routes/insights/health'
import { Route as InsightsBottlenecksRouteImport } from './routes/insights/bottlenecks'
import { Route as DeploymentsNameRouteImport } from './routes/deployments/$name'
import { Route as CatalogsExploreRouteImport } from './routes/catalogs/explore'
import { Route as CatalogsAvailableRouteImport } from './routes/catalogs/available'
import { Route as InstrumentsInstrumentNameIndexRouteImport } from './routes/instruments/$instrumentName/index'
import { Route as AdminSimulationsIndexRouteImport } from './routes/admin/simulations/index'
import { Route as AdminBenchmarksIndexRouteImport } from './routes/admin/benchmarks/index'
import { Route as AdminSimulationsRunIdRouteImport } from './routes/admin/simulations/$runId'
import { Route as InstrumentsInstrumentNameSchemaRegistryIndexRouteImport } from './routes/instruments/$instrumentName/schema-registry/index'
import { Route as InstrumentsInstrumentNameRedisIndexRouteImport } from './routes/instruments/$instrumentName/redis/index'
import { Route as InstrumentsInstrumentNameDatabaseIndexRouteImport } from './routes/instruments/$instrumentName/database/index'
import { Route as InstrumentsInstrumentNameSchemaRegistrySubjectRouteImport } from './routes/instruments/$instrumentName/schema-registry/subject'
import { Route as InstrumentsInstrumentNameSchemaRegistryCompatibilityRouteImport } from './routes/instruments/$instrumentName/schema-registry/compatibility'
import { Route as InstrumentsInstrumentNameRedisServerRouteImport } from './routes/instruments/$instrumentName/redis/server'
import { Route as InstrumentsInstrumentNameRedisKeyRouteImport } from './routes/instruments/$instrumentName/redis/key'
import { Route as InstrumentsInstrumentNameDatabaseTableRouteImport } from './routes/instruments/$instrumentName/database/table'
import { Route as InstrumentsInstrumentNameDatabaseQueryRouteImport } from './routes/instruments/$instrumentName/database/query'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobManagerRoute = JobManagerRouteImport.update({
  id: '/job-manager',
  path: '/job-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskManagersIndexRoute = TaskManagersIndexRouteImport.update({
  id: '/task-managers/',
  path: '/task-managers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxIndexRoute = SandboxIndexRouteImport.update({
  id: '/sandbox/',
  path: '/sandbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterializedTablesIndexRoute = MaterializedTablesIndexRouteImport.update({
  id: '/materialized-tables/',
  path: '/materialized-tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsIndexRoute = InstrumentsIndexRouteImport.update({
  id: '/instruments/',
  path: '/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsIndexRoute = CatalogsIndexRouteImport.update({
  id: '/catalogs/',
  path: '/catalogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskManagersIdRoute = TaskManagersIdRouteImport.update({
  id: '/task-managers/$id',
  path: '/task-managers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxEditorRoute = SandboxEditorRouteImport.update({
  id: '/sandbox/editor',
  path: '/sandbox/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringCheckpointsRoute = MonitoringCheckpointsRouteImport.update({
  id: '/monitoring/checkpoints',
  path: '/monitoring/checkpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringAlertsRoute = MonitoringAlertsRouteImport.update({
  id: '/monitoring/alerts',
  path: '/monitoring/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterializedTablesNameRoute = MaterializedTablesNameRouteImport.update({
  id: '/materialized-tables/$name',
  path: '/materialized-tables/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSubmitRoute = JobsSubmitRouteImport.update({
  id: '/jobs/submit',
  path: '/jobs/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRunningRoute = JobsRunningRouteImport.update({
  id: '/jobs/running',
  path: '/jobs/running',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCompletedRoute = JobsCompletedRouteImport.update({
  id: '/jobs/completed',
  path: '/jobs/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsInstrumentNameRoute =
  InstrumentsInstrumentNameRouteImport.update({
    id: '/instruments/$instrumentName',
    path: '/instruments/$instrumentName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsMetricsRoute = InsightsMetricsRouteImport.update({
  id: '/insights/metrics',
  path: '/insights/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsHealthRoute = InsightsHealthRouteImport.update({
  id: '/insights/health',
  path: '/insights/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsBottlenecksRoute = InsightsBottlenecksRouteImport.update({
  id: '/insights/bottlenecks',
  path: '/insights/bottlenecks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsNameRoute = DeploymentsNameRouteImport.update({
  id: '/deployments/$name',
  path: '/deployments/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsExploreRoute = CatalogsExploreRouteImport.update({
  id: '/catalogs/explore',
  path: '/catalogs/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsAvailableRoute = CatalogsAvailableRouteImport.update({
  id: '/catalogs/available',
  path: '/catalogs/available',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsInstrumentNameIndexRoute =
  InstrumentsInstrumentNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const AdminSimulationsIndexRoute = AdminSimulationsIndexRouteImport.update({
  id: '/admin/simulations/',
  path: '/admin/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBenchmarksIndexRoute = AdminBenchmarksIndexRouteImport.update({
  id: '/admin/benchmarks/',
  path: '/admin/benchmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSimulationsRunIdRoute = AdminSimulationsRunIdRouteImport.update({
  id: '/admin/simulations/$runId',
  path: '/admin/simulations/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsInstrumentNameSchemaRegistryIndexRoute =
  InstrumentsInstrumentNameSchemaRegistryIndexRouteImport.update({
    id: '/schema-registry/',
    path: '/schema-registry/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameRedisIndexRoute =
  InstrumentsInstrumentNameRedisIndexRouteImport.update({
    id: '/redis/',
    path: '/redis/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameDatabaseIndexRoute =
  InstrumentsInstrumentNameDatabaseIndexRouteImport.update({
    id: '/database/',
    path: '/database/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameSchemaRegistrySubjectRoute =
  InstrumentsInstrumentNameSchemaRegistrySubjectRouteImport.update({
    id: '/schema-registry/subject',
    path: '/schema-registry/subject',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute =
  InstrumentsInstrumentNameSchemaRegistryCompatibilityRouteImport.update({
    id: '/schema-registry/compatibility',
    path: '/schema-registry/compatibility',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameRedisServerRoute =
  InstrumentsInstrumentNameRedisServerRouteImport.update({
    id: '/redis/server',
    path: '/redis/server',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameRedisKeyRoute =
  InstrumentsInstrumentNameRedisKeyRouteImport.update({
    id: '/redis/key',
    path: '/redis/key',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameDatabaseTableRoute =
  InstrumentsInstrumentNameDatabaseTableRouteImport.update({
    id: '/database/table',
    path: '/database/table',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameDatabaseQueryRoute =
  InstrumentsInstrumentNameDatabaseQueryRouteImport.update({
    id: '/database/query',
    path: '/database/query',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/job-manager': typeof JobManagerRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/catalogs/available': typeof CatalogsAvailableRoute
  '/catalogs/explore': typeof CatalogsExploreRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/insights/bottlenecks': typeof InsightsBottlenecksRoute
  '/insights/health': typeof InsightsHealthRoute
  '/insights/metrics': typeof InsightsMetricsRoute
  '/instruments/$instrumentName': typeof InstrumentsInstrumentNameRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/completed': typeof JobsCompletedRoute
  '/jobs/running': typeof JobsRunningRoute
  '/jobs/submit': typeof JobsSubmitRoute
  '/materialized-tables/$name': typeof MaterializedTablesNameRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/checkpoints': typeof MonitoringCheckpointsRoute
  '/sandbox/editor': typeof SandboxEditorRoute
  '/task-managers/$id': typeof TaskManagersIdRoute
  '/catalogs/': typeof CatalogsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/materialized-tables/': typeof MaterializedTablesIndexRoute
  '/sandbox/': typeof SandboxIndexRoute
  '/task-managers/': typeof TaskManagersIndexRoute
  '/admin/simulations/$runId': typeof AdminSimulationsRunIdRoute
  '/admin/benchmarks/': typeof AdminBenchmarksIndexRoute
  '/admin/simulations/': typeof AdminSimulationsIndexRoute
  '/instruments/$instrumentName/': typeof InstrumentsInstrumentNameIndexRoute
  '/instruments/$instrumentName/database/query': typeof InstrumentsInstrumentNameDatabaseQueryRoute
  '/instruments/$instrumentName/database/table': typeof InstrumentsInstrumentNameDatabaseTableRoute
  '/instruments/$instrumentName/redis/key': typeof InstrumentsInstrumentNameRedisKeyRoute
  '/instruments/$instrumentName/redis/server': typeof InstrumentsInstrumentNameRedisServerRoute
  '/instruments/$instrumentName/schema-registry/compatibility': typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  '/instruments/$instrumentName/schema-registry/subject': typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  '/instruments/$instrumentName/database/': typeof InstrumentsInstrumentNameDatabaseIndexRoute
  '/instruments/$instrumentName/redis/': typeof InstrumentsInstrumentNameRedisIndexRoute
  '/instruments/$instrumentName/schema-registry/': typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/job-manager': typeof JobManagerRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/catalogs/available': typeof CatalogsAvailableRoute
  '/catalogs/explore': typeof CatalogsExploreRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/insights/bottlenecks': typeof InsightsBottlenecksRoute
  '/insights/health': typeof InsightsHealthRoute
  '/insights/metrics': typeof InsightsMetricsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/completed': typeof JobsCompletedRoute
  '/jobs/running': typeof JobsRunningRoute
  '/jobs/submit': typeof JobsSubmitRoute
  '/materialized-tables/$name': typeof MaterializedTablesNameRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/checkpoints': typeof MonitoringCheckpointsRoute
  '/sandbox/editor': typeof SandboxEditorRoute
  '/task-managers/$id': typeof TaskManagersIdRoute
  '/catalogs': typeof CatalogsIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/instruments': typeof InstrumentsIndexRoute
  '/materialized-tables': typeof MaterializedTablesIndexRoute
  '/sandbox': typeof SandboxIndexRoute
  '/task-managers': typeof TaskManagersIndexRoute
  '/admin/simulations/$runId': typeof AdminSimulationsRunIdRoute
  '/admin/benchmarks': typeof AdminBenchmarksIndexRoute
  '/admin/simulations': typeof AdminSimulationsIndexRoute
  '/instruments/$instrumentName': typeof InstrumentsInstrumentNameIndexRoute
  '/instruments/$instrumentName/database/query': typeof InstrumentsInstrumentNameDatabaseQueryRoute
  '/instruments/$instrumentName/database/table': typeof InstrumentsInstrumentNameDatabaseTableRoute
  '/instruments/$instrumentName/redis/key': typeof InstrumentsInstrumentNameRedisKeyRoute
  '/instruments/$instrumentName/redis/server': typeof InstrumentsInstrumentNameRedisServerRoute
  '/instruments/$instrumentName/schema-registry/compatibility': typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  '/instruments/$instrumentName/schema-registry/subject': typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  '/instruments/$instrumentName/database': typeof InstrumentsInstrumentNameDatabaseIndexRoute
  '/instruments/$instrumentName/redis': typeof InstrumentsInstrumentNameRedisIndexRoute
  '/instruments/$instrumentName/schema-registry': typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/job-manager': typeof JobManagerRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/catalogs/available': typeof CatalogsAvailableRoute
  '/catalogs/explore': typeof CatalogsExploreRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/insights/bottlenecks': typeof InsightsBottlenecksRoute
  '/insights/health': typeof InsightsHealthRoute
  '/insights/metrics': typeof InsightsMetricsRoute
  '/instruments/$instrumentName': typeof InstrumentsInstrumentNameRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/completed': typeof JobsCompletedRoute
  '/jobs/running': typeof JobsRunningRoute
  '/jobs/submit': typeof JobsSubmitRoute
  '/materialized-tables/$name': typeof MaterializedTablesNameRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/checkpoints': typeof MonitoringCheckpointsRoute
  '/sandbox/editor': typeof SandboxEditorRoute
  '/task-managers/$id': typeof TaskManagersIdRoute
  '/catalogs/': typeof CatalogsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/materialized-tables/': typeof MaterializedTablesIndexRoute
  '/sandbox/': typeof SandboxIndexRoute
  '/task-managers/': typeof TaskManagersIndexRoute
  '/admin/simulations/$runId': typeof AdminSimulationsRunIdRoute
  '/admin/benchmarks/': typeof AdminBenchmarksIndexRoute
  '/admin/simulations/': typeof AdminSimulationsIndexRoute
  '/instruments/$instrumentName/': typeof InstrumentsInstrumentNameIndexRoute
  '/instruments/$instrumentName/database/query': typeof InstrumentsInstrumentNameDatabaseQueryRoute
  '/instruments/$instrumentName/database/table': typeof InstrumentsInstrumentNameDatabaseTableRoute
  '/instruments/$instrumentName/redis/key': typeof InstrumentsInstrumentNameRedisKeyRoute
  '/instruments/$instrumentName/redis/server': typeof InstrumentsInstrumentNameRedisServerRoute
  '/instruments/$instrumentName/schema-registry/compatibility': typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  '/instruments/$instrumentName/schema-registry/subject': typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  '/instruments/$instrumentName/database/': typeof InstrumentsInstrumentNameDatabaseIndexRoute
  '/instruments/$instrumentName/redis/': typeof InstrumentsInstrumentNameRedisIndexRoute
  '/instruments/$instrumentName/schema-registry/': typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errors'
    | '/job-manager'
    | '/logs'
    | '/overview'
    | '/catalogs/available'
    | '/catalogs/explore'
    | '/deployments/$name'
    | '/insights/bottlenecks'
    | '/insights/health'
    | '/insights/metrics'
    | '/instruments/$instrumentName'
    | '/jobs/$id'
    | '/jobs/completed'
    | '/jobs/running'
    | '/jobs/submit'
    | '/materialized-tables/$name'
    | '/monitoring/alerts'
    | '/monitoring/checkpoints'
    | '/sandbox/editor'
    | '/task-managers/$id'
    | '/catalogs/'
    | '/deployments/'
    | '/instruments/'
    | '/materialized-tables/'
    | '/sandbox/'
    | '/task-managers/'
    | '/admin/simulations/$runId'
    | '/admin/benchmarks/'
    | '/admin/simulations/'
    | '/instruments/$instrumentName/'
    | '/instruments/$instrumentName/database/query'
    | '/instruments/$instrumentName/database/table'
    | '/instruments/$instrumentName/redis/key'
    | '/instruments/$instrumentName/redis/server'
    | '/instruments/$instrumentName/schema-registry/compatibility'
    | '/instruments/$instrumentName/schema-registry/subject'
    | '/instruments/$instrumentName/database/'
    | '/instruments/$instrumentName/redis/'
    | '/instruments/$instrumentName/schema-registry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors'
    | '/job-manager'
    | '/logs'
    | '/overview'
    | '/catalogs/available'
    | '/catalogs/explore'
    | '/deployments/$name'
    | '/insights/bottlenecks'
    | '/insights/health'
    | '/insights/metrics'
    | '/jobs/$id'
    | '/jobs/completed'
    | '/jobs/running'
    | '/jobs/submit'
    | '/materialized-tables/$name'
    | '/monitoring/alerts'
    | '/monitoring/checkpoints'
    | '/sandbox/editor'
    | '/task-managers/$id'
    | '/catalogs'
    | '/deployments'
    | '/instruments'
    | '/materialized-tables'
    | '/sandbox'
    | '/task-managers'
    | '/admin/simulations/$runId'
    | '/admin/benchmarks'
    | '/admin/simulations'
    | '/instruments/$instrumentName'
    | '/instruments/$instrumentName/database/query'
    | '/instruments/$instrumentName/database/table'
    | '/instruments/$instrumentName/redis/key'
    | '/instruments/$instrumentName/redis/server'
    | '/instruments/$instrumentName/schema-registry/compatibility'
    | '/instruments/$instrumentName/schema-registry/subject'
    | '/instruments/$instrumentName/database'
    | '/instruments/$instrumentName/redis'
    | '/instruments/$instrumentName/schema-registry'
  id:
    | '__root__'
    | '/'
    | '/errors'
    | '/job-manager'
    | '/logs'
    | '/overview'
    | '/catalogs/available'
    | '/catalogs/explore'
    | '/deployments/$name'
    | '/insights/bottlenecks'
    | '/insights/health'
    | '/insights/metrics'
    | '/instruments/$instrumentName'
    | '/jobs/$id'
    | '/jobs/completed'
    | '/jobs/running'
    | '/jobs/submit'
    | '/materialized-tables/$name'
    | '/monitoring/alerts'
    | '/monitoring/checkpoints'
    | '/sandbox/editor'
    | '/task-managers/$id'
    | '/catalogs/'
    | '/deployments/'
    | '/instruments/'
    | '/materialized-tables/'
    | '/sandbox/'
    | '/task-managers/'
    | '/admin/simulations/$runId'
    | '/admin/benchmarks/'
    | '/admin/simulations/'
    | '/instruments/$instrumentName/'
    | '/instruments/$instrumentName/database/query'
    | '/instruments/$instrumentName/database/table'
    | '/instruments/$instrumentName/redis/key'
    | '/instruments/$instrumentName/redis/server'
    | '/instruments/$instrumentName/schema-registry/compatibility'
    | '/instruments/$instrumentName/schema-registry/subject'
    | '/instruments/$instrumentName/database/'
    | '/instruments/$instrumentName/redis/'
    | '/instruments/$instrumentName/schema-registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorsRoute: typeof ErrorsRoute
  JobManagerRoute: typeof JobManagerRoute
  LogsRoute: typeof LogsRoute
  OverviewRoute: typeof OverviewRoute
  CatalogsAvailableRoute: typeof CatalogsAvailableRoute
  CatalogsExploreRoute: typeof CatalogsExploreRoute
  DeploymentsNameRoute: typeof DeploymentsNameRoute
  InsightsBottlenecksRoute: typeof InsightsBottlenecksRoute
  InsightsHealthRoute: typeof InsightsHealthRoute
  InsightsMetricsRoute: typeof InsightsMetricsRoute
  InstrumentsInstrumentNameRoute: typeof InstrumentsInstrumentNameRouteWithChildren
  JobsIdRoute: typeof JobsIdRoute
  JobsCompletedRoute: typeof JobsCompletedRoute
  JobsRunningRoute: typeof JobsRunningRoute
  JobsSubmitRoute: typeof JobsSubmitRoute
  MaterializedTablesNameRoute: typeof MaterializedTablesNameRoute
  MonitoringAlertsRoute: typeof MonitoringAlertsRoute
  MonitoringCheckpointsRoute: typeof MonitoringCheckpointsRoute
  SandboxEditorRoute: typeof SandboxEditorRoute
  TaskManagersIdRoute: typeof TaskManagersIdRoute
  CatalogsIndexRoute: typeof CatalogsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  InstrumentsIndexRoute: typeof InstrumentsIndexRoute
  MaterializedTablesIndexRoute: typeof MaterializedTablesIndexRoute
  SandboxIndexRoute: typeof SandboxIndexRoute
  TaskManagersIndexRoute: typeof TaskManagersIndexRoute
  AdminSimulationsRunIdRoute: typeof AdminSimulationsRunIdRoute
  AdminBenchmarksIndexRoute: typeof AdminBenchmarksIndexRoute
  AdminSimulationsIndexRoute: typeof AdminSimulationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-manager': {
      id: '/job-manager'
      path: '/job-manager'
      fullPath: '/job-manager'
      preLoaderRoute: typeof JobManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-managers/': {
      id: '/task-managers/'
      path: '/task-managers'
      fullPath: '/task-managers/'
      preLoaderRoute: typeof TaskManagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/': {
      id: '/sandbox/'
      path: '/sandbox'
      fullPath: '/sandbox/'
      preLoaderRoute: typeof SandboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materialized-tables/': {
      id: '/materialized-tables/'
      path: '/materialized-tables'
      fullPath: '/materialized-tables/'
      preLoaderRoute: typeof MaterializedTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/': {
      id: '/instruments/'
      path: '/instruments'
      fullPath: '/instruments/'
      preLoaderRoute: typeof InstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/': {
      id: '/catalogs/'
      path: '/catalogs'
      fullPath: '/catalogs/'
      preLoaderRoute: typeof CatalogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-managers/$id': {
      id: '/task-managers/$id'
      path: '/task-managers/$id'
      fullPath: '/task-managers/$id'
      preLoaderRoute: typeof TaskManagersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/editor': {
      id: '/sandbox/editor'
      path: '/sandbox/editor'
      fullPath: '/sandbox/editor'
      preLoaderRoute: typeof SandboxEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/checkpoints': {
      id: '/monitoring/checkpoints'
      path: '/monitoring/checkpoints'
      fullPath: '/monitoring/checkpoints'
      preLoaderRoute: typeof MonitoringCheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/alerts': {
      id: '/monitoring/alerts'
      path: '/monitoring/alerts'
      fullPath: '/monitoring/alerts'
      preLoaderRoute: typeof MonitoringAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materialized-tables/$name': {
      id: '/materialized-tables/$name'
      path: '/materialized-tables/$name'
      fullPath: '/materialized-tables/$name'
      preLoaderRoute: typeof MaterializedTablesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/submit': {
      id: '/jobs/submit'
      path: '/jobs/submit'
      fullPath: '/jobs/submit'
      preLoaderRoute: typeof JobsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/running': {
      id: '/jobs/running'
      path: '/jobs/running'
      fullPath: '/jobs/running'
      preLoaderRoute: typeof JobsRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/completed': {
      id: '/jobs/completed'
      path: '/jobs/completed'
      fullPath: '/jobs/completed'
      preLoaderRoute: typeof JobsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$instrumentName': {
      id: '/instruments/$instrumentName'
      path: '/instruments/$instrumentName'
      fullPath: '/instruments/$instrumentName'
      preLoaderRoute: typeof InstrumentsInstrumentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/metrics': {
      id: '/insights/metrics'
      path: '/insights/metrics'
      fullPath: '/insights/metrics'
      preLoaderRoute: typeof InsightsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/health': {
      id: '/insights/health'
      path: '/insights/health'
      fullPath: '/insights/health'
      preLoaderRoute: typeof InsightsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/bottlenecks': {
      id: '/insights/bottlenecks'
      path: '/insights/bottlenecks'
      fullPath: '/insights/bottlenecks'
      preLoaderRoute: typeof InsightsBottlenecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$name': {
      id: '/deployments/$name'
      path: '/deployments/$name'
      fullPath: '/deployments/$name'
      preLoaderRoute: typeof DeploymentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/explore': {
      id: '/catalogs/explore'
      path: '/catalogs/explore'
      fullPath: '/catalogs/explore'
      preLoaderRoute: typeof CatalogsExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/available': {
      id: '/catalogs/available'
      path: '/catalogs/available'
      fullPath: '/catalogs/available'
      preLoaderRoute: typeof CatalogsAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$instrumentName/': {
      id: '/instruments/$instrumentName/'
      path: '/'
      fullPath: '/instruments/$instrumentName/'
      preLoaderRoute: typeof InstrumentsInstrumentNameIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/admin/simulations/': {
      id: '/admin/simulations/'
      path: '/admin/simulations'
      fullPath: '/admin/simulations/'
      preLoaderRoute: typeof AdminSimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/benchmarks/': {
      id: '/admin/benchmarks/'
      path: '/admin/benchmarks'
      fullPath: '/admin/benchmarks/'
      preLoaderRoute: typeof AdminBenchmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/simulations/$runId': {
      id: '/admin/simulations/$runId'
      path: '/admin/simulations/$runId'
      fullPath: '/admin/simulations/$runId'
      preLoaderRoute: typeof AdminSimulationsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$instrumentName/schema-registry/': {
      id: '/instruments/$instrumentName/schema-registry/'
      path: '/schema-registry'
      fullPath: '/instruments/$instrumentName/schema-registry/'
      preLoaderRoute: typeof InstrumentsInstrumentNameSchemaRegistryIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/redis/': {
      id: '/instruments/$instrumentName/redis/'
      path: '/redis'
      fullPath: '/instruments/$instrumentName/redis/'
      preLoaderRoute: typeof InstrumentsInstrumentNameRedisIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/database/': {
      id: '/instruments/$instrumentName/database/'
      path: '/database'
      fullPath: '/instruments/$instrumentName/database/'
      preLoaderRoute: typeof InstrumentsInstrumentNameDatabaseIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/schema-registry/subject': {
      id: '/instruments/$instrumentName/schema-registry/subject'
      path: '/schema-registry/subject'
      fullPath: '/instruments/$instrumentName/schema-registry/subject'
      preLoaderRoute: typeof InstrumentsInstrumentNameSchemaRegistrySubjectRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/schema-registry/compatibility': {
      id: '/instruments/$instrumentName/schema-registry/compatibility'
      path: '/schema-registry/compatibility'
      fullPath: '/instruments/$instrumentName/schema-registry/compatibility'
      preLoaderRoute: typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/redis/server': {
      id: '/instruments/$instrumentName/redis/server'
      path: '/redis/server'
      fullPath: '/instruments/$instrumentName/redis/server'
      preLoaderRoute: typeof InstrumentsInstrumentNameRedisServerRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/redis/key': {
      id: '/instruments/$instrumentName/redis/key'
      path: '/redis/key'
      fullPath: '/instruments/$instrumentName/redis/key'
      preLoaderRoute: typeof InstrumentsInstrumentNameRedisKeyRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/database/table': {
      id: '/instruments/$instrumentName/database/table'
      path: '/database/table'
      fullPath: '/instruments/$instrumentName/database/table'
      preLoaderRoute: typeof InstrumentsInstrumentNameDatabaseTableRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/database/query': {
      id: '/instruments/$instrumentName/database/query'
      path: '/database/query'
      fullPath: '/instruments/$instrumentName/database/query'
      preLoaderRoute: typeof InstrumentsInstrumentNameDatabaseQueryRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
  }
}

interface InstrumentsInstrumentNameRouteChildren {
  InstrumentsInstrumentNameIndexRoute: typeof InstrumentsInstrumentNameIndexRoute
  InstrumentsInstrumentNameDatabaseQueryRoute: typeof InstrumentsInstrumentNameDatabaseQueryRoute
  InstrumentsInstrumentNameDatabaseTableRoute: typeof InstrumentsInstrumentNameDatabaseTableRoute
  InstrumentsInstrumentNameRedisKeyRoute: typeof InstrumentsInstrumentNameRedisKeyRoute
  InstrumentsInstrumentNameRedisServerRoute: typeof InstrumentsInstrumentNameRedisServerRoute
  InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute: typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  InstrumentsInstrumentNameSchemaRegistrySubjectRoute: typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  InstrumentsInstrumentNameDatabaseIndexRoute: typeof InstrumentsInstrumentNameDatabaseIndexRoute
  InstrumentsInstrumentNameRedisIndexRoute: typeof InstrumentsInstrumentNameRedisIndexRoute
  InstrumentsInstrumentNameSchemaRegistryIndexRoute: typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}

const InstrumentsInstrumentNameRouteChildren: InstrumentsInstrumentNameRouteChildren =
  {
    InstrumentsInstrumentNameIndexRoute: InstrumentsInstrumentNameIndexRoute,
    InstrumentsInstrumentNameDatabaseQueryRoute:
      InstrumentsInstrumentNameDatabaseQueryRoute,
    InstrumentsInstrumentNameDatabaseTableRoute:
      InstrumentsInstrumentNameDatabaseTableRoute,
    InstrumentsInstrumentNameRedisKeyRoute:
      InstrumentsInstrumentNameRedisKeyRoute,
    InstrumentsInstrumentNameRedisServerRoute:
      InstrumentsInstrumentNameRedisServerRoute,
    InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute:
      InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute,
    InstrumentsInstrumentNameSchemaRegistrySubjectRoute:
      InstrumentsInstrumentNameSchemaRegistrySubjectRoute,
    InstrumentsInstrumentNameDatabaseIndexRoute:
      InstrumentsInstrumentNameDatabaseIndexRoute,
    InstrumentsInstrumentNameRedisIndexRoute:
      InstrumentsInstrumentNameRedisIndexRoute,
    InstrumentsInstrumentNameSchemaRegistryIndexRoute:
      InstrumentsInstrumentNameSchemaRegistryIndexRoute,
  }

const InstrumentsInstrumentNameRouteWithChildren =
  InstrumentsInstrumentNameRoute._addFileChildren(
    InstrumentsInstrumentNameRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorsRoute: ErrorsRoute,
  JobManagerRoute: JobManagerRoute,
  LogsRoute: LogsRoute,
  OverviewRoute: OverviewRoute,
  CatalogsAvailableRoute: CatalogsAvailableRoute,
  CatalogsExploreRoute: CatalogsExploreRoute,
  DeploymentsNameRoute: DeploymentsNameRoute,
  InsightsBottlenecksRoute: InsightsBottlenecksRoute,
  InsightsHealthRoute: InsightsHealthRoute,
  InsightsMetricsRoute: InsightsMetricsRoute,
  InstrumentsInstrumentNameRoute: InstrumentsInstrumentNameRouteWithChildren,
  JobsIdRoute: JobsIdRoute,
  JobsCompletedRoute: JobsCompletedRoute,
  JobsRunningRoute: JobsRunningRoute,
  JobsSubmitRoute: JobsSubmitRoute,
  MaterializedTablesNameRoute: MaterializedTablesNameRoute,
  MonitoringAlertsRoute: MonitoringAlertsRoute,
  MonitoringCheckpointsRoute: MonitoringCheckpointsRoute,
  SandboxEditorRoute: SandboxEditorRoute,
  TaskManagersIdRoute: TaskManagersIdRoute,
  CatalogsIndexRoute: CatalogsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  InstrumentsIndexRoute: InstrumentsIndexRoute,
  MaterializedTablesIndexRoute: MaterializedTablesIndexRoute,
  SandboxIndexRoute: SandboxIndexRoute,
  TaskManagersIndexRoute: TaskManagersIndexRoute,
  AdminSimulationsRunIdRoute: AdminSimulationsRunIdRoute,
  AdminBenchmarksIndexRoute: AdminBenchmarksIndexRoute,
  AdminSimulationsIndexRoute: AdminSimulationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
