/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as JobManagerRouteImport } from './routes/job-manager'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskManagersIndexRouteImport } from './routes/task-managers/index'
import { Route as SandboxIndexRouteImport } from './routes/sandbox/index'
import { Route as MaterializedTablesIndexRouteImport } from './routes/materialized-tables/index'
import { Route as InstrumentsIndexRouteImport } from './routes/instruments/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments/index'
import { Route as CatalogsIndexRouteImport } from './routes/catalogs/index'
import { Route as TaskManagersIdRouteImport } from './routes/task-managers/$id'
import { Route as SandboxEditorRouteImport } from './routes/sandbox/editor'
import { Route as MonitoringCheckpointsRouteImport } from './routes/monitoring/checkpoints'
import { Route as MonitoringAlertsRouteImport } from './routes/monitoring/alerts'
import { Route as MaterializedTablesNameRouteImport } from './routes/materialized-tables/$name'
import { Route as JobsSubmitRouteImport } from './routes/jobs/submit'
import { Route as JobsRunningRouteImport } from './routes/jobs/running'
import { Route as JobsCompletedRouteImport } from './routes/jobs/completed'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as InstrumentsInstrumentNameRouteImport } from './routes/instruments/$instrumentName'
import { Route as InsightsMetricsRouteImport } from './routes/insights/metrics'
import { Route as InsightsHealthRouteImport } from './routes/insights/health'
import { Route as InsightsBottlenecksRouteImport } from './routes/insights/bottlenecks'
import { Route as HubSqlExplorerRouteImport } from './routes/hub/sql-explorer'
import { Route as HubSandboxRouteImport } from './routes/hub/sandbox'
import { Route as HubLogsRouteImport } from './routes/hub/logs'
import { Route as HubJobManagerRouteImport } from './routes/hub/job-manager'
import { Route as HubErrorsRouteImport } from './routes/hub/errors'
import { Route as Hub_shellTestRouteImport } from './routes/hub/__shell-test'
import { Route as DeploymentsNameRouteImport } from './routes/deployments/$name'
import { Route as CatalogsExploreRouteImport } from './routes/catalogs/explore'
import { Route as CatalogsAvailableRouteImport } from './routes/catalogs/available'
import { Route as InstrumentsInstrumentNameIndexRouteImport } from './routes/instruments/$instrumentName/index'
import { Route as HubTaskManagersIndexRouteImport } from './routes/hub/task-managers/index'
import { Route as HubMaterializedTablesIndexRouteImport } from './routes/hub/materialized-tables/index'
import { Route as HubInstrumentsIndexRouteImport } from './routes/hub/instruments/index'
import { Route as HubDeploymentsIndexRouteImport } from './routes/hub/deployments/index'
import { Route as HubCatalogsIndexRouteImport } from './routes/hub/catalogs/index'
import { Route as AdminSimulationsIndexRouteImport } from './routes/admin/simulations/index'
import { Route as AdminBenchmarksIndexRouteImport } from './routes/admin/benchmarks/index'
import { Route as HubTaskManagersIdRouteImport } from './routes/hub/task-managers/$id'
import { Route as HubMonitoringCheckpointsRouteImport } from './routes/hub/monitoring/checkpoints'
import { Route as HubMonitoringAlertsRouteImport } from './routes/hub/monitoring/alerts'
import { Route as HubMaterializedTablesNameRouteImport } from './routes/hub/materialized-tables/$name'
import { Route as HubJobsSubmitRouteImport } from './routes/hub/jobs/submit'
import { Route as HubJobsRunningRouteImport } from './routes/hub/jobs/running'
import { Route as HubJobsCompletedRouteImport } from './routes/hub/jobs/completed'
import { Route as HubJobsIdRouteImport } from './routes/hub/jobs/$id'
import { Route as HubInstrumentsSchemaRegistryRouteImport } from './routes/hub/instruments/schema-registry'
import { Route as HubInstrumentsRedisRouteImport } from './routes/hub/instruments/redis'
import { Route as HubInstrumentsFlussRouteImport } from './routes/hub/instruments/fluss'
import { Route as HubInstrumentsDatabaseRouteImport } from './routes/hub/instruments/database'
import { Route as HubInsightsMetricsRouteImport } from './routes/hub/insights/metrics'
import { Route as HubInsightsHealthRouteImport } from './routes/hub/insights/health'
import { Route as HubInsightsBottlenecksRouteImport } from './routes/hub/insights/bottlenecks'
import { Route as HubDeploymentsNameRouteImport } from './routes/hub/deployments/$name'
import { Route as HubAdminSimulationsRouteImport } from './routes/hub/admin/simulations'
import { Route as AdminSimulationsRunIdRouteImport } from './routes/admin/simulations/$runId'
import { Route as InstrumentsInstrumentNameSchemaRegistryIndexRouteImport } from './routes/instruments/$instrumentName/schema-registry/index'
import { Route as InstrumentsInstrumentNameRedisIndexRouteImport } from './routes/instruments/$instrumentName/redis/index'
import { Route as InstrumentsInstrumentNameFlussIndexRouteImport } from './routes/instruments/$instrumentName/fluss/index'
import { Route as InstrumentsInstrumentNameDatabaseIndexRouteImport } from './routes/instruments/$instrumentName/database/index'
import { Route as InstrumentsInstrumentNameSchemaRegistrySubjectRouteImport } from './routes/instruments/$instrumentName/schema-registry/subject'
import { Route as InstrumentsInstrumentNameSchemaRegistryCompatibilityRouteImport } from './routes/instruments/$instrumentName/schema-registry/compatibility'
import { Route as InstrumentsInstrumentNameRedisServerRouteImport } from './routes/instruments/$instrumentName/redis/server'
import { Route as InstrumentsInstrumentNameRedisKeyRouteImport } from './routes/instruments/$instrumentName/redis/key'
import { Route as InstrumentsInstrumentNameFlussTableRouteImport } from './routes/instruments/$instrumentName/fluss/table'
import { Route as InstrumentsInstrumentNameFlussHealthRouteImport } from './routes/instruments/$instrumentName/fluss/health'
import { Route as InstrumentsInstrumentNameDatabaseTableRouteImport } from './routes/instruments/$instrumentName/database/table'
import { Route as InstrumentsInstrumentNameDatabaseQueryRouteImport } from './routes/instruments/$instrumentName/database/query'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobManagerRoute = JobManagerRouteImport.update({
  id: '/job-manager',
  path: '/job-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskManagersIndexRoute = TaskManagersIndexRouteImport.update({
  id: '/task-managers/',
  path: '/task-managers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxIndexRoute = SandboxIndexRouteImport.update({
  id: '/sandbox/',
  path: '/sandbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterializedTablesIndexRoute = MaterializedTablesIndexRouteImport.update({
  id: '/materialized-tables/',
  path: '/materialized-tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsIndexRoute = InstrumentsIndexRouteImport.update({
  id: '/instruments/',
  path: '/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsIndexRoute = CatalogsIndexRouteImport.update({
  id: '/catalogs/',
  path: '/catalogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskManagersIdRoute = TaskManagersIdRouteImport.update({
  id: '/task-managers/$id',
  path: '/task-managers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxEditorRoute = SandboxEditorRouteImport.update({
  id: '/sandbox/editor',
  path: '/sandbox/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringCheckpointsRoute = MonitoringCheckpointsRouteImport.update({
  id: '/monitoring/checkpoints',
  path: '/monitoring/checkpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringAlertsRoute = MonitoringAlertsRouteImport.update({
  id: '/monitoring/alerts',
  path: '/monitoring/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterializedTablesNameRoute = MaterializedTablesNameRouteImport.update({
  id: '/materialized-tables/$name',
  path: '/materialized-tables/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSubmitRoute = JobsSubmitRouteImport.update({
  id: '/jobs/submit',
  path: '/jobs/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRunningRoute = JobsRunningRouteImport.update({
  id: '/jobs/running',
  path: '/jobs/running',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCompletedRoute = JobsCompletedRouteImport.update({
  id: '/jobs/completed',
  path: '/jobs/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsInstrumentNameRoute =
  InstrumentsInstrumentNameRouteImport.update({
    id: '/instruments/$instrumentName',
    path: '/instruments/$instrumentName',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsMetricsRoute = InsightsMetricsRouteImport.update({
  id: '/insights/metrics',
  path: '/insights/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsHealthRoute = InsightsHealthRouteImport.update({
  id: '/insights/health',
  path: '/insights/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsBottlenecksRoute = InsightsBottlenecksRouteImport.update({
  id: '/insights/bottlenecks',
  path: '/insights/bottlenecks',
  getParentRoute: () => rootRouteImport,
} as any)
const HubSqlExplorerRoute = HubSqlExplorerRouteImport.update({
  id: '/hub/sql-explorer',
  path: '/hub/sql-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const HubSandboxRoute = HubSandboxRouteImport.update({
  id: '/hub/sandbox',
  path: '/hub/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HubLogsRoute = HubLogsRouteImport.update({
  id: '/hub/logs',
  path: '/hub/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJobManagerRoute = HubJobManagerRouteImport.update({
  id: '/hub/job-manager',
  path: '/hub/job-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const HubErrorsRoute = HubErrorsRouteImport.update({
  id: '/hub/errors',
  path: '/hub/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const Hub_shellTestRoute = Hub_shellTestRouteImport.update({
  id: '/hub/__shell-test',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsNameRoute = DeploymentsNameRouteImport.update({
  id: '/deployments/$name',
  path: '/deployments/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsExploreRoute = CatalogsExploreRouteImport.update({
  id: '/catalogs/explore',
  path: '/catalogs/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsAvailableRoute = CatalogsAvailableRouteImport.update({
  id: '/catalogs/available',
  path: '/catalogs/available',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsInstrumentNameIndexRoute =
  InstrumentsInstrumentNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const HubTaskManagersIndexRoute = HubTaskManagersIndexRouteImport.update({
  id: '/hub/task-managers/',
  path: '/hub/task-managers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMaterializedTablesIndexRoute =
  HubMaterializedTablesIndexRouteImport.update({
    id: '/hub/materialized-tables/',
    path: '/hub/materialized-tables/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HubInstrumentsIndexRoute = HubInstrumentsIndexRouteImport.update({
  id: '/hub/instruments/',
  path: '/hub/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubDeploymentsIndexRoute = HubDeploymentsIndexRouteImport.update({
  id: '/hub/deployments/',
  path: '/hub/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCatalogsIndexRoute = HubCatalogsIndexRouteImport.update({
  id: '/hub/catalogs/',
  path: '/hub/catalogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSimulationsIndexRoute = AdminSimulationsIndexRouteImport.update({
  id: '/admin/simulations/',
  path: '/admin/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBenchmarksIndexRoute = AdminBenchmarksIndexRouteImport.update({
  id: '/admin/benchmarks/',
  path: '/admin/benchmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubTaskManagersIdRoute = HubTaskManagersIdRouteImport.update({
  id: '/hub/task-managers/$id',
  path: '/hub/task-managers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMonitoringCheckpointsRoute =
  HubMonitoringCheckpointsRouteImport.update({
    id: '/hub/monitoring/checkpoints',
    path: '/hub/monitoring/checkpoints',
    getParentRoute: () => rootRouteImport,
  } as any)
const HubMonitoringAlertsRoute = HubMonitoringAlertsRouteImport.update({
  id: '/hub/monitoring/alerts',
  path: '/hub/monitoring/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMaterializedTablesNameRoute =
  HubMaterializedTablesNameRouteImport.update({
    id: '/hub/materialized-tables/$name',
    path: '/hub/materialized-tables/$name',
    getParentRoute: () => rootRouteImport,
  } as any)
const HubJobsSubmitRoute = HubJobsSubmitRouteImport.update({
  id: '/hub/jobs/submit',
  path: '/hub/jobs/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJobsRunningRoute = HubJobsRunningRouteImport.update({
  id: '/hub/jobs/running',
  path: '/hub/jobs/running',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJobsCompletedRoute = HubJobsCompletedRouteImport.update({
  id: '/hub/jobs/completed',
  path: '/hub/jobs/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const HubJobsIdRoute = HubJobsIdRouteImport.update({
  id: '/hub/jobs/$id',
  path: '/hub/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HubInstrumentsSchemaRegistryRoute =
  HubInstrumentsSchemaRegistryRouteImport.update({
    id: '/hub/instruments/schema-registry',
    path: '/hub/instruments/schema-registry',
    getParentRoute: () => rootRouteImport,
  } as any)
const HubInstrumentsRedisRoute = HubInstrumentsRedisRouteImport.update({
  id: '/hub/instruments/redis',
  path: '/hub/instruments/redis',
  getParentRoute: () => rootRouteImport,
} as any)
const HubInstrumentsFlussRoute = HubInstrumentsFlussRouteImport.update({
  id: '/hub/instruments/fluss',
  path: '/hub/instruments/fluss',
  getParentRoute: () => rootRouteImport,
} as any)
const HubInstrumentsDatabaseRoute = HubInstrumentsDatabaseRouteImport.update({
  id: '/hub/instruments/database',
  path: '/hub/instruments/database',
  getParentRoute: () => rootRouteImport,
} as any)
const HubInsightsMetricsRoute = HubInsightsMetricsRouteImport.update({
  id: '/hub/insights/metrics',
  path: '/hub/insights/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const HubInsightsHealthRoute = HubInsightsHealthRouteImport.update({
  id: '/hub/insights/health',
  path: '/hub/insights/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HubInsightsBottlenecksRoute = HubInsightsBottlenecksRouteImport.update({
  id: '/hub/insights/bottlenecks',
  path: '/hub/insights/bottlenecks',
  getParentRoute: () => rootRouteImport,
} as any)
const HubDeploymentsNameRoute = HubDeploymentsNameRouteImport.update({
  id: '/hub/deployments/$name',
  path: '/hub/deployments/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const HubAdminSimulationsRoute = HubAdminSimulationsRouteImport.update({
  id: '/hub/admin/simulations',
  path: '/hub/admin/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSimulationsRunIdRoute = AdminSimulationsRunIdRouteImport.update({
  id: '/admin/simulations/$runId',
  path: '/admin/simulations/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsInstrumentNameSchemaRegistryIndexRoute =
  InstrumentsInstrumentNameSchemaRegistryIndexRouteImport.update({
    id: '/schema-registry/',
    path: '/schema-registry/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameRedisIndexRoute =
  InstrumentsInstrumentNameRedisIndexRouteImport.update({
    id: '/redis/',
    path: '/redis/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameFlussIndexRoute =
  InstrumentsInstrumentNameFlussIndexRouteImport.update({
    id: '/fluss/',
    path: '/fluss/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameDatabaseIndexRoute =
  InstrumentsInstrumentNameDatabaseIndexRouteImport.update({
    id: '/database/',
    path: '/database/',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameSchemaRegistrySubjectRoute =
  InstrumentsInstrumentNameSchemaRegistrySubjectRouteImport.update({
    id: '/schema-registry/subject',
    path: '/schema-registry/subject',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute =
  InstrumentsInstrumentNameSchemaRegistryCompatibilityRouteImport.update({
    id: '/schema-registry/compatibility',
    path: '/schema-registry/compatibility',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameRedisServerRoute =
  InstrumentsInstrumentNameRedisServerRouteImport.update({
    id: '/redis/server',
    path: '/redis/server',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameRedisKeyRoute =
  InstrumentsInstrumentNameRedisKeyRouteImport.update({
    id: '/redis/key',
    path: '/redis/key',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameFlussTableRoute =
  InstrumentsInstrumentNameFlussTableRouteImport.update({
    id: '/fluss/table',
    path: '/fluss/table',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameFlussHealthRoute =
  InstrumentsInstrumentNameFlussHealthRouteImport.update({
    id: '/fluss/health',
    path: '/fluss/health',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameDatabaseTableRoute =
  InstrumentsInstrumentNameDatabaseTableRouteImport.update({
    id: '/database/table',
    path: '/database/table',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)
const InstrumentsInstrumentNameDatabaseQueryRoute =
  InstrumentsInstrumentNameDatabaseQueryRouteImport.update({
    id: '/database/query',
    path: '/database/query',
    getParentRoute: () => InstrumentsInstrumentNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/job-manager': typeof JobManagerRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/catalogs/available': typeof CatalogsAvailableRoute
  '/catalogs/explore': typeof CatalogsExploreRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/hub': typeof Hub_shellTestRoute
  '/hub/errors': typeof HubErrorsRoute
  '/hub/job-manager': typeof HubJobManagerRoute
  '/hub/logs': typeof HubLogsRoute
  '/hub/sandbox': typeof HubSandboxRoute
  '/hub/sql-explorer': typeof HubSqlExplorerRoute
  '/insights/bottlenecks': typeof InsightsBottlenecksRoute
  '/insights/health': typeof InsightsHealthRoute
  '/insights/metrics': typeof InsightsMetricsRoute
  '/instruments/$instrumentName': typeof InstrumentsInstrumentNameRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/completed': typeof JobsCompletedRoute
  '/jobs/running': typeof JobsRunningRoute
  '/jobs/submit': typeof JobsSubmitRoute
  '/materialized-tables/$name': typeof MaterializedTablesNameRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/checkpoints': typeof MonitoringCheckpointsRoute
  '/sandbox/editor': typeof SandboxEditorRoute
  '/task-managers/$id': typeof TaskManagersIdRoute
  '/catalogs/': typeof CatalogsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/hub/': typeof HubIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/materialized-tables/': typeof MaterializedTablesIndexRoute
  '/sandbox/': typeof SandboxIndexRoute
  '/task-managers/': typeof TaskManagersIndexRoute
  '/admin/simulations/$runId': typeof AdminSimulationsRunIdRoute
  '/hub/admin/simulations': typeof HubAdminSimulationsRoute
  '/hub/deployments/$name': typeof HubDeploymentsNameRoute
  '/hub/insights/bottlenecks': typeof HubInsightsBottlenecksRoute
  '/hub/insights/health': typeof HubInsightsHealthRoute
  '/hub/insights/metrics': typeof HubInsightsMetricsRoute
  '/hub/instruments/database': typeof HubInstrumentsDatabaseRoute
  '/hub/instruments/fluss': typeof HubInstrumentsFlussRoute
  '/hub/instruments/redis': typeof HubInstrumentsRedisRoute
  '/hub/instruments/schema-registry': typeof HubInstrumentsSchemaRegistryRoute
  '/hub/jobs/$id': typeof HubJobsIdRoute
  '/hub/jobs/completed': typeof HubJobsCompletedRoute
  '/hub/jobs/running': typeof HubJobsRunningRoute
  '/hub/jobs/submit': typeof HubJobsSubmitRoute
  '/hub/materialized-tables/$name': typeof HubMaterializedTablesNameRoute
  '/hub/monitoring/alerts': typeof HubMonitoringAlertsRoute
  '/hub/monitoring/checkpoints': typeof HubMonitoringCheckpointsRoute
  '/hub/task-managers/$id': typeof HubTaskManagersIdRoute
  '/admin/benchmarks/': typeof AdminBenchmarksIndexRoute
  '/admin/simulations/': typeof AdminSimulationsIndexRoute
  '/hub/catalogs/': typeof HubCatalogsIndexRoute
  '/hub/deployments/': typeof HubDeploymentsIndexRoute
  '/hub/instruments/': typeof HubInstrumentsIndexRoute
  '/hub/materialized-tables/': typeof HubMaterializedTablesIndexRoute
  '/hub/task-managers/': typeof HubTaskManagersIndexRoute
  '/instruments/$instrumentName/': typeof InstrumentsInstrumentNameIndexRoute
  '/instruments/$instrumentName/database/query': typeof InstrumentsInstrumentNameDatabaseQueryRoute
  '/instruments/$instrumentName/database/table': typeof InstrumentsInstrumentNameDatabaseTableRoute
  '/instruments/$instrumentName/fluss/health': typeof InstrumentsInstrumentNameFlussHealthRoute
  '/instruments/$instrumentName/fluss/table': typeof InstrumentsInstrumentNameFlussTableRoute
  '/instruments/$instrumentName/redis/key': typeof InstrumentsInstrumentNameRedisKeyRoute
  '/instruments/$instrumentName/redis/server': typeof InstrumentsInstrumentNameRedisServerRoute
  '/instruments/$instrumentName/schema-registry/compatibility': typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  '/instruments/$instrumentName/schema-registry/subject': typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  '/instruments/$instrumentName/database/': typeof InstrumentsInstrumentNameDatabaseIndexRoute
  '/instruments/$instrumentName/fluss/': typeof InstrumentsInstrumentNameFlussIndexRoute
  '/instruments/$instrumentName/redis/': typeof InstrumentsInstrumentNameRedisIndexRoute
  '/instruments/$instrumentName/schema-registry/': typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/job-manager': typeof JobManagerRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/catalogs/available': typeof CatalogsAvailableRoute
  '/catalogs/explore': typeof CatalogsExploreRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/hub': typeof HubIndexRoute
  '/hub/errors': typeof HubErrorsRoute
  '/hub/job-manager': typeof HubJobManagerRoute
  '/hub/logs': typeof HubLogsRoute
  '/hub/sandbox': typeof HubSandboxRoute
  '/hub/sql-explorer': typeof HubSqlExplorerRoute
  '/insights/bottlenecks': typeof InsightsBottlenecksRoute
  '/insights/health': typeof InsightsHealthRoute
  '/insights/metrics': typeof InsightsMetricsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/completed': typeof JobsCompletedRoute
  '/jobs/running': typeof JobsRunningRoute
  '/jobs/submit': typeof JobsSubmitRoute
  '/materialized-tables/$name': typeof MaterializedTablesNameRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/checkpoints': typeof MonitoringCheckpointsRoute
  '/sandbox/editor': typeof SandboxEditorRoute
  '/task-managers/$id': typeof TaskManagersIdRoute
  '/catalogs': typeof CatalogsIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/instruments': typeof InstrumentsIndexRoute
  '/materialized-tables': typeof MaterializedTablesIndexRoute
  '/sandbox': typeof SandboxIndexRoute
  '/task-managers': typeof TaskManagersIndexRoute
  '/admin/simulations/$runId': typeof AdminSimulationsRunIdRoute
  '/hub/admin/simulations': typeof HubAdminSimulationsRoute
  '/hub/deployments/$name': typeof HubDeploymentsNameRoute
  '/hub/insights/bottlenecks': typeof HubInsightsBottlenecksRoute
  '/hub/insights/health': typeof HubInsightsHealthRoute
  '/hub/insights/metrics': typeof HubInsightsMetricsRoute
  '/hub/instruments/database': typeof HubInstrumentsDatabaseRoute
  '/hub/instruments/fluss': typeof HubInstrumentsFlussRoute
  '/hub/instruments/redis': typeof HubInstrumentsRedisRoute
  '/hub/instruments/schema-registry': typeof HubInstrumentsSchemaRegistryRoute
  '/hub/jobs/$id': typeof HubJobsIdRoute
  '/hub/jobs/completed': typeof HubJobsCompletedRoute
  '/hub/jobs/running': typeof HubJobsRunningRoute
  '/hub/jobs/submit': typeof HubJobsSubmitRoute
  '/hub/materialized-tables/$name': typeof HubMaterializedTablesNameRoute
  '/hub/monitoring/alerts': typeof HubMonitoringAlertsRoute
  '/hub/monitoring/checkpoints': typeof HubMonitoringCheckpointsRoute
  '/hub/task-managers/$id': typeof HubTaskManagersIdRoute
  '/admin/benchmarks': typeof AdminBenchmarksIndexRoute
  '/admin/simulations': typeof AdminSimulationsIndexRoute
  '/hub/catalogs': typeof HubCatalogsIndexRoute
  '/hub/deployments': typeof HubDeploymentsIndexRoute
  '/hub/instruments': typeof HubInstrumentsIndexRoute
  '/hub/materialized-tables': typeof HubMaterializedTablesIndexRoute
  '/hub/task-managers': typeof HubTaskManagersIndexRoute
  '/instruments/$instrumentName': typeof InstrumentsInstrumentNameIndexRoute
  '/instruments/$instrumentName/database/query': typeof InstrumentsInstrumentNameDatabaseQueryRoute
  '/instruments/$instrumentName/database/table': typeof InstrumentsInstrumentNameDatabaseTableRoute
  '/instruments/$instrumentName/fluss/health': typeof InstrumentsInstrumentNameFlussHealthRoute
  '/instruments/$instrumentName/fluss/table': typeof InstrumentsInstrumentNameFlussTableRoute
  '/instruments/$instrumentName/redis/key': typeof InstrumentsInstrumentNameRedisKeyRoute
  '/instruments/$instrumentName/redis/server': typeof InstrumentsInstrumentNameRedisServerRoute
  '/instruments/$instrumentName/schema-registry/compatibility': typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  '/instruments/$instrumentName/schema-registry/subject': typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  '/instruments/$instrumentName/database': typeof InstrumentsInstrumentNameDatabaseIndexRoute
  '/instruments/$instrumentName/fluss': typeof InstrumentsInstrumentNameFlussIndexRoute
  '/instruments/$instrumentName/redis': typeof InstrumentsInstrumentNameRedisIndexRoute
  '/instruments/$instrumentName/schema-registry': typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/job-manager': typeof JobManagerRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/catalogs/available': typeof CatalogsAvailableRoute
  '/catalogs/explore': typeof CatalogsExploreRoute
  '/deployments/$name': typeof DeploymentsNameRoute
  '/hub/__shell-test': typeof Hub_shellTestRoute
  '/hub/errors': typeof HubErrorsRoute
  '/hub/job-manager': typeof HubJobManagerRoute
  '/hub/logs': typeof HubLogsRoute
  '/hub/sandbox': typeof HubSandboxRoute
  '/hub/sql-explorer': typeof HubSqlExplorerRoute
  '/insights/bottlenecks': typeof InsightsBottlenecksRoute
  '/insights/health': typeof InsightsHealthRoute
  '/insights/metrics': typeof InsightsMetricsRoute
  '/instruments/$instrumentName': typeof InstrumentsInstrumentNameRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/completed': typeof JobsCompletedRoute
  '/jobs/running': typeof JobsRunningRoute
  '/jobs/submit': typeof JobsSubmitRoute
  '/materialized-tables/$name': typeof MaterializedTablesNameRoute
  '/monitoring/alerts': typeof MonitoringAlertsRoute
  '/monitoring/checkpoints': typeof MonitoringCheckpointsRoute
  '/sandbox/editor': typeof SandboxEditorRoute
  '/task-managers/$id': typeof TaskManagersIdRoute
  '/catalogs/': typeof CatalogsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/hub/': typeof HubIndexRoute
  '/instruments/': typeof InstrumentsIndexRoute
  '/materialized-tables/': typeof MaterializedTablesIndexRoute
  '/sandbox/': typeof SandboxIndexRoute
  '/task-managers/': typeof TaskManagersIndexRoute
  '/admin/simulations/$runId': typeof AdminSimulationsRunIdRoute
  '/hub/admin/simulations': typeof HubAdminSimulationsRoute
  '/hub/deployments/$name': typeof HubDeploymentsNameRoute
  '/hub/insights/bottlenecks': typeof HubInsightsBottlenecksRoute
  '/hub/insights/health': typeof HubInsightsHealthRoute
  '/hub/insights/metrics': typeof HubInsightsMetricsRoute
  '/hub/instruments/database': typeof HubInstrumentsDatabaseRoute
  '/hub/instruments/fluss': typeof HubInstrumentsFlussRoute
  '/hub/instruments/redis': typeof HubInstrumentsRedisRoute
  '/hub/instruments/schema-registry': typeof HubInstrumentsSchemaRegistryRoute
  '/hub/jobs/$id': typeof HubJobsIdRoute
  '/hub/jobs/completed': typeof HubJobsCompletedRoute
  '/hub/jobs/running': typeof HubJobsRunningRoute
  '/hub/jobs/submit': typeof HubJobsSubmitRoute
  '/hub/materialized-tables/$name': typeof HubMaterializedTablesNameRoute
  '/hub/monitoring/alerts': typeof HubMonitoringAlertsRoute
  '/hub/monitoring/checkpoints': typeof HubMonitoringCheckpointsRoute
  '/hub/task-managers/$id': typeof HubTaskManagersIdRoute
  '/admin/benchmarks/': typeof AdminBenchmarksIndexRoute
  '/admin/simulations/': typeof AdminSimulationsIndexRoute
  '/hub/catalogs/': typeof HubCatalogsIndexRoute
  '/hub/deployments/': typeof HubDeploymentsIndexRoute
  '/hub/instruments/': typeof HubInstrumentsIndexRoute
  '/hub/materialized-tables/': typeof HubMaterializedTablesIndexRoute
  '/hub/task-managers/': typeof HubTaskManagersIndexRoute
  '/instruments/$instrumentName/': typeof InstrumentsInstrumentNameIndexRoute
  '/instruments/$instrumentName/database/query': typeof InstrumentsInstrumentNameDatabaseQueryRoute
  '/instruments/$instrumentName/database/table': typeof InstrumentsInstrumentNameDatabaseTableRoute
  '/instruments/$instrumentName/fluss/health': typeof InstrumentsInstrumentNameFlussHealthRoute
  '/instruments/$instrumentName/fluss/table': typeof InstrumentsInstrumentNameFlussTableRoute
  '/instruments/$instrumentName/redis/key': typeof InstrumentsInstrumentNameRedisKeyRoute
  '/instruments/$instrumentName/redis/server': typeof InstrumentsInstrumentNameRedisServerRoute
  '/instruments/$instrumentName/schema-registry/compatibility': typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  '/instruments/$instrumentName/schema-registry/subject': typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  '/instruments/$instrumentName/database/': typeof InstrumentsInstrumentNameDatabaseIndexRoute
  '/instruments/$instrumentName/fluss/': typeof InstrumentsInstrumentNameFlussIndexRoute
  '/instruments/$instrumentName/redis/': typeof InstrumentsInstrumentNameRedisIndexRoute
  '/instruments/$instrumentName/schema-registry/': typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errors'
    | '/job-manager'
    | '/logs'
    | '/overview'
    | '/catalogs/available'
    | '/catalogs/explore'
    | '/deployments/$name'
    | '/hub'
    | '/hub/errors'
    | '/hub/job-manager'
    | '/hub/logs'
    | '/hub/sandbox'
    | '/hub/sql-explorer'
    | '/insights/bottlenecks'
    | '/insights/health'
    | '/insights/metrics'
    | '/instruments/$instrumentName'
    | '/jobs/$id'
    | '/jobs/completed'
    | '/jobs/running'
    | '/jobs/submit'
    | '/materialized-tables/$name'
    | '/monitoring/alerts'
    | '/monitoring/checkpoints'
    | '/sandbox/editor'
    | '/task-managers/$id'
    | '/catalogs/'
    | '/deployments/'
    | '/hub/'
    | '/instruments/'
    | '/materialized-tables/'
    | '/sandbox/'
    | '/task-managers/'
    | '/admin/simulations/$runId'
    | '/hub/admin/simulations'
    | '/hub/deployments/$name'
    | '/hub/insights/bottlenecks'
    | '/hub/insights/health'
    | '/hub/insights/metrics'
    | '/hub/instruments/database'
    | '/hub/instruments/fluss'
    | '/hub/instruments/redis'
    | '/hub/instruments/schema-registry'
    | '/hub/jobs/$id'
    | '/hub/jobs/completed'
    | '/hub/jobs/running'
    | '/hub/jobs/submit'
    | '/hub/materialized-tables/$name'
    | '/hub/monitoring/alerts'
    | '/hub/monitoring/checkpoints'
    | '/hub/task-managers/$id'
    | '/admin/benchmarks/'
    | '/admin/simulations/'
    | '/hub/catalogs/'
    | '/hub/deployments/'
    | '/hub/instruments/'
    | '/hub/materialized-tables/'
    | '/hub/task-managers/'
    | '/instruments/$instrumentName/'
    | '/instruments/$instrumentName/database/query'
    | '/instruments/$instrumentName/database/table'
    | '/instruments/$instrumentName/fluss/health'
    | '/instruments/$instrumentName/fluss/table'
    | '/instruments/$instrumentName/redis/key'
    | '/instruments/$instrumentName/redis/server'
    | '/instruments/$instrumentName/schema-registry/compatibility'
    | '/instruments/$instrumentName/schema-registry/subject'
    | '/instruments/$instrumentName/database/'
    | '/instruments/$instrumentName/fluss/'
    | '/instruments/$instrumentName/redis/'
    | '/instruments/$instrumentName/schema-registry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors'
    | '/job-manager'
    | '/logs'
    | '/overview'
    | '/catalogs/available'
    | '/catalogs/explore'
    | '/deployments/$name'
    | '/hub'
    | '/hub/errors'
    | '/hub/job-manager'
    | '/hub/logs'
    | '/hub/sandbox'
    | '/hub/sql-explorer'
    | '/insights/bottlenecks'
    | '/insights/health'
    | '/insights/metrics'
    | '/jobs/$id'
    | '/jobs/completed'
    | '/jobs/running'
    | '/jobs/submit'
    | '/materialized-tables/$name'
    | '/monitoring/alerts'
    | '/monitoring/checkpoints'
    | '/sandbox/editor'
    | '/task-managers/$id'
    | '/catalogs'
    | '/deployments'
    | '/instruments'
    | '/materialized-tables'
    | '/sandbox'
    | '/task-managers'
    | '/admin/simulations/$runId'
    | '/hub/admin/simulations'
    | '/hub/deployments/$name'
    | '/hub/insights/bottlenecks'
    | '/hub/insights/health'
    | '/hub/insights/metrics'
    | '/hub/instruments/database'
    | '/hub/instruments/fluss'
    | '/hub/instruments/redis'
    | '/hub/instruments/schema-registry'
    | '/hub/jobs/$id'
    | '/hub/jobs/completed'
    | '/hub/jobs/running'
    | '/hub/jobs/submit'
    | '/hub/materialized-tables/$name'
    | '/hub/monitoring/alerts'
    | '/hub/monitoring/checkpoints'
    | '/hub/task-managers/$id'
    | '/admin/benchmarks'
    | '/admin/simulations'
    | '/hub/catalogs'
    | '/hub/deployments'
    | '/hub/instruments'
    | '/hub/materialized-tables'
    | '/hub/task-managers'
    | '/instruments/$instrumentName'
    | '/instruments/$instrumentName/database/query'
    | '/instruments/$instrumentName/database/table'
    | '/instruments/$instrumentName/fluss/health'
    | '/instruments/$instrumentName/fluss/table'
    | '/instruments/$instrumentName/redis/key'
    | '/instruments/$instrumentName/redis/server'
    | '/instruments/$instrumentName/schema-registry/compatibility'
    | '/instruments/$instrumentName/schema-registry/subject'
    | '/instruments/$instrumentName/database'
    | '/instruments/$instrumentName/fluss'
    | '/instruments/$instrumentName/redis'
    | '/instruments/$instrumentName/schema-registry'
  id:
    | '__root__'
    | '/'
    | '/errors'
    | '/job-manager'
    | '/logs'
    | '/overview'
    | '/catalogs/available'
    | '/catalogs/explore'
    | '/deployments/$name'
    | '/hub/__shell-test'
    | '/hub/errors'
    | '/hub/job-manager'
    | '/hub/logs'
    | '/hub/sandbox'
    | '/hub/sql-explorer'
    | '/insights/bottlenecks'
    | '/insights/health'
    | '/insights/metrics'
    | '/instruments/$instrumentName'
    | '/jobs/$id'
    | '/jobs/completed'
    | '/jobs/running'
    | '/jobs/submit'
    | '/materialized-tables/$name'
    | '/monitoring/alerts'
    | '/monitoring/checkpoints'
    | '/sandbox/editor'
    | '/task-managers/$id'
    | '/catalogs/'
    | '/deployments/'
    | '/hub/'
    | '/instruments/'
    | '/materialized-tables/'
    | '/sandbox/'
    | '/task-managers/'
    | '/admin/simulations/$runId'
    | '/hub/admin/simulations'
    | '/hub/deployments/$name'
    | '/hub/insights/bottlenecks'
    | '/hub/insights/health'
    | '/hub/insights/metrics'
    | '/hub/instruments/database'
    | '/hub/instruments/fluss'
    | '/hub/instruments/redis'
    | '/hub/instruments/schema-registry'
    | '/hub/jobs/$id'
    | '/hub/jobs/completed'
    | '/hub/jobs/running'
    | '/hub/jobs/submit'
    | '/hub/materialized-tables/$name'
    | '/hub/monitoring/alerts'
    | '/hub/monitoring/checkpoints'
    | '/hub/task-managers/$id'
    | '/admin/benchmarks/'
    | '/admin/simulations/'
    | '/hub/catalogs/'
    | '/hub/deployments/'
    | '/hub/instruments/'
    | '/hub/materialized-tables/'
    | '/hub/task-managers/'
    | '/instruments/$instrumentName/'
    | '/instruments/$instrumentName/database/query'
    | '/instruments/$instrumentName/database/table'
    | '/instruments/$instrumentName/fluss/health'
    | '/instruments/$instrumentName/fluss/table'
    | '/instruments/$instrumentName/redis/key'
    | '/instruments/$instrumentName/redis/server'
    | '/instruments/$instrumentName/schema-registry/compatibility'
    | '/instruments/$instrumentName/schema-registry/subject'
    | '/instruments/$instrumentName/database/'
    | '/instruments/$instrumentName/fluss/'
    | '/instruments/$instrumentName/redis/'
    | '/instruments/$instrumentName/schema-registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorsRoute: typeof ErrorsRoute
  JobManagerRoute: typeof JobManagerRoute
  LogsRoute: typeof LogsRoute
  OverviewRoute: typeof OverviewRoute
  CatalogsAvailableRoute: typeof CatalogsAvailableRoute
  CatalogsExploreRoute: typeof CatalogsExploreRoute
  DeploymentsNameRoute: typeof DeploymentsNameRoute
  Hub_shellTestRoute: typeof Hub_shellTestRoute
  HubErrorsRoute: typeof HubErrorsRoute
  HubJobManagerRoute: typeof HubJobManagerRoute
  HubLogsRoute: typeof HubLogsRoute
  HubSandboxRoute: typeof HubSandboxRoute
  HubSqlExplorerRoute: typeof HubSqlExplorerRoute
  InsightsBottlenecksRoute: typeof InsightsBottlenecksRoute
  InsightsHealthRoute: typeof InsightsHealthRoute
  InsightsMetricsRoute: typeof InsightsMetricsRoute
  InstrumentsInstrumentNameRoute: typeof InstrumentsInstrumentNameRouteWithChildren
  JobsIdRoute: typeof JobsIdRoute
  JobsCompletedRoute: typeof JobsCompletedRoute
  JobsRunningRoute: typeof JobsRunningRoute
  JobsSubmitRoute: typeof JobsSubmitRoute
  MaterializedTablesNameRoute: typeof MaterializedTablesNameRoute
  MonitoringAlertsRoute: typeof MonitoringAlertsRoute
  MonitoringCheckpointsRoute: typeof MonitoringCheckpointsRoute
  SandboxEditorRoute: typeof SandboxEditorRoute
  TaskManagersIdRoute: typeof TaskManagersIdRoute
  CatalogsIndexRoute: typeof CatalogsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  HubIndexRoute: typeof HubIndexRoute
  InstrumentsIndexRoute: typeof InstrumentsIndexRoute
  MaterializedTablesIndexRoute: typeof MaterializedTablesIndexRoute
  SandboxIndexRoute: typeof SandboxIndexRoute
  TaskManagersIndexRoute: typeof TaskManagersIndexRoute
  AdminSimulationsRunIdRoute: typeof AdminSimulationsRunIdRoute
  HubAdminSimulationsRoute: typeof HubAdminSimulationsRoute
  HubDeploymentsNameRoute: typeof HubDeploymentsNameRoute
  HubInsightsBottlenecksRoute: typeof HubInsightsBottlenecksRoute
  HubInsightsHealthRoute: typeof HubInsightsHealthRoute
  HubInsightsMetricsRoute: typeof HubInsightsMetricsRoute
  HubInstrumentsDatabaseRoute: typeof HubInstrumentsDatabaseRoute
  HubInstrumentsFlussRoute: typeof HubInstrumentsFlussRoute
  HubInstrumentsRedisRoute: typeof HubInstrumentsRedisRoute
  HubInstrumentsSchemaRegistryRoute: typeof HubInstrumentsSchemaRegistryRoute
  HubJobsIdRoute: typeof HubJobsIdRoute
  HubJobsCompletedRoute: typeof HubJobsCompletedRoute
  HubJobsRunningRoute: typeof HubJobsRunningRoute
  HubJobsSubmitRoute: typeof HubJobsSubmitRoute
  HubMaterializedTablesNameRoute: typeof HubMaterializedTablesNameRoute
  HubMonitoringAlertsRoute: typeof HubMonitoringAlertsRoute
  HubMonitoringCheckpointsRoute: typeof HubMonitoringCheckpointsRoute
  HubTaskManagersIdRoute: typeof HubTaskManagersIdRoute
  AdminBenchmarksIndexRoute: typeof AdminBenchmarksIndexRoute
  AdminSimulationsIndexRoute: typeof AdminSimulationsIndexRoute
  HubCatalogsIndexRoute: typeof HubCatalogsIndexRoute
  HubDeploymentsIndexRoute: typeof HubDeploymentsIndexRoute
  HubInstrumentsIndexRoute: typeof HubInstrumentsIndexRoute
  HubMaterializedTablesIndexRoute: typeof HubMaterializedTablesIndexRoute
  HubTaskManagersIndexRoute: typeof HubTaskManagersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-manager': {
      id: '/job-manager'
      path: '/job-manager'
      fullPath: '/job-manager'
      preLoaderRoute: typeof JobManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-managers/': {
      id: '/task-managers/'
      path: '/task-managers'
      fullPath: '/task-managers/'
      preLoaderRoute: typeof TaskManagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/': {
      id: '/sandbox/'
      path: '/sandbox'
      fullPath: '/sandbox/'
      preLoaderRoute: typeof SandboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materialized-tables/': {
      id: '/materialized-tables/'
      path: '/materialized-tables'
      fullPath: '/materialized-tables/'
      preLoaderRoute: typeof MaterializedTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/': {
      id: '/instruments/'
      path: '/instruments'
      fullPath: '/instruments/'
      preLoaderRoute: typeof InstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/': {
      id: '/catalogs/'
      path: '/catalogs'
      fullPath: '/catalogs/'
      preLoaderRoute: typeof CatalogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-managers/$id': {
      id: '/task-managers/$id'
      path: '/task-managers/$id'
      fullPath: '/task-managers/$id'
      preLoaderRoute: typeof TaskManagersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/editor': {
      id: '/sandbox/editor'
      path: '/sandbox/editor'
      fullPath: '/sandbox/editor'
      preLoaderRoute: typeof SandboxEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/checkpoints': {
      id: '/monitoring/checkpoints'
      path: '/monitoring/checkpoints'
      fullPath: '/monitoring/checkpoints'
      preLoaderRoute: typeof MonitoringCheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/alerts': {
      id: '/monitoring/alerts'
      path: '/monitoring/alerts'
      fullPath: '/monitoring/alerts'
      preLoaderRoute: typeof MonitoringAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materialized-tables/$name': {
      id: '/materialized-tables/$name'
      path: '/materialized-tables/$name'
      fullPath: '/materialized-tables/$name'
      preLoaderRoute: typeof MaterializedTablesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/submit': {
      id: '/jobs/submit'
      path: '/jobs/submit'
      fullPath: '/jobs/submit'
      preLoaderRoute: typeof JobsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/running': {
      id: '/jobs/running'
      path: '/jobs/running'
      fullPath: '/jobs/running'
      preLoaderRoute: typeof JobsRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/completed': {
      id: '/jobs/completed'
      path: '/jobs/completed'
      fullPath: '/jobs/completed'
      preLoaderRoute: typeof JobsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$instrumentName': {
      id: '/instruments/$instrumentName'
      path: '/instruments/$instrumentName'
      fullPath: '/instruments/$instrumentName'
      preLoaderRoute: typeof InstrumentsInstrumentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/metrics': {
      id: '/insights/metrics'
      path: '/insights/metrics'
      fullPath: '/insights/metrics'
      preLoaderRoute: typeof InsightsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/health': {
      id: '/insights/health'
      path: '/insights/health'
      fullPath: '/insights/health'
      preLoaderRoute: typeof InsightsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/bottlenecks': {
      id: '/insights/bottlenecks'
      path: '/insights/bottlenecks'
      fullPath: '/insights/bottlenecks'
      preLoaderRoute: typeof InsightsBottlenecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/sql-explorer': {
      id: '/hub/sql-explorer'
      path: '/hub/sql-explorer'
      fullPath: '/hub/sql-explorer'
      preLoaderRoute: typeof HubSqlExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/sandbox': {
      id: '/hub/sandbox'
      path: '/hub/sandbox'
      fullPath: '/hub/sandbox'
      preLoaderRoute: typeof HubSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/logs': {
      id: '/hub/logs'
      path: '/hub/logs'
      fullPath: '/hub/logs'
      preLoaderRoute: typeof HubLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/job-manager': {
      id: '/hub/job-manager'
      path: '/hub/job-manager'
      fullPath: '/hub/job-manager'
      preLoaderRoute: typeof HubJobManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/errors': {
      id: '/hub/errors'
      path: '/hub/errors'
      fullPath: '/hub/errors'
      preLoaderRoute: typeof HubErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/__shell-test': {
      id: '/hub/__shell-test'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof Hub_shellTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$name': {
      id: '/deployments/$name'
      path: '/deployments/$name'
      fullPath: '/deployments/$name'
      preLoaderRoute: typeof DeploymentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/explore': {
      id: '/catalogs/explore'
      path: '/catalogs/explore'
      fullPath: '/catalogs/explore'
      preLoaderRoute: typeof CatalogsExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/available': {
      id: '/catalogs/available'
      path: '/catalogs/available'
      fullPath: '/catalogs/available'
      preLoaderRoute: typeof CatalogsAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$instrumentName/': {
      id: '/instruments/$instrumentName/'
      path: '/'
      fullPath: '/instruments/$instrumentName/'
      preLoaderRoute: typeof InstrumentsInstrumentNameIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/hub/task-managers/': {
      id: '/hub/task-managers/'
      path: '/hub/task-managers'
      fullPath: '/hub/task-managers/'
      preLoaderRoute: typeof HubTaskManagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/materialized-tables/': {
      id: '/hub/materialized-tables/'
      path: '/hub/materialized-tables'
      fullPath: '/hub/materialized-tables/'
      preLoaderRoute: typeof HubMaterializedTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/instruments/': {
      id: '/hub/instruments/'
      path: '/hub/instruments'
      fullPath: '/hub/instruments/'
      preLoaderRoute: typeof HubInstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/deployments/': {
      id: '/hub/deployments/'
      path: '/hub/deployments'
      fullPath: '/hub/deployments/'
      preLoaderRoute: typeof HubDeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/catalogs/': {
      id: '/hub/catalogs/'
      path: '/hub/catalogs'
      fullPath: '/hub/catalogs/'
      preLoaderRoute: typeof HubCatalogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/simulations/': {
      id: '/admin/simulations/'
      path: '/admin/simulations'
      fullPath: '/admin/simulations/'
      preLoaderRoute: typeof AdminSimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/benchmarks/': {
      id: '/admin/benchmarks/'
      path: '/admin/benchmarks'
      fullPath: '/admin/benchmarks/'
      preLoaderRoute: typeof AdminBenchmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/task-managers/$id': {
      id: '/hub/task-managers/$id'
      path: '/hub/task-managers/$id'
      fullPath: '/hub/task-managers/$id'
      preLoaderRoute: typeof HubTaskManagersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/monitoring/checkpoints': {
      id: '/hub/monitoring/checkpoints'
      path: '/hub/monitoring/checkpoints'
      fullPath: '/hub/monitoring/checkpoints'
      preLoaderRoute: typeof HubMonitoringCheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/monitoring/alerts': {
      id: '/hub/monitoring/alerts'
      path: '/hub/monitoring/alerts'
      fullPath: '/hub/monitoring/alerts'
      preLoaderRoute: typeof HubMonitoringAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/materialized-tables/$name': {
      id: '/hub/materialized-tables/$name'
      path: '/hub/materialized-tables/$name'
      fullPath: '/hub/materialized-tables/$name'
      preLoaderRoute: typeof HubMaterializedTablesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/jobs/submit': {
      id: '/hub/jobs/submit'
      path: '/hub/jobs/submit'
      fullPath: '/hub/jobs/submit'
      preLoaderRoute: typeof HubJobsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/jobs/running': {
      id: '/hub/jobs/running'
      path: '/hub/jobs/running'
      fullPath: '/hub/jobs/running'
      preLoaderRoute: typeof HubJobsRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/jobs/completed': {
      id: '/hub/jobs/completed'
      path: '/hub/jobs/completed'
      fullPath: '/hub/jobs/completed'
      preLoaderRoute: typeof HubJobsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/jobs/$id': {
      id: '/hub/jobs/$id'
      path: '/hub/jobs/$id'
      fullPath: '/hub/jobs/$id'
      preLoaderRoute: typeof HubJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/instruments/schema-registry': {
      id: '/hub/instruments/schema-registry'
      path: '/hub/instruments/schema-registry'
      fullPath: '/hub/instruments/schema-registry'
      preLoaderRoute: typeof HubInstrumentsSchemaRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/instruments/redis': {
      id: '/hub/instruments/redis'
      path: '/hub/instruments/redis'
      fullPath: '/hub/instruments/redis'
      preLoaderRoute: typeof HubInstrumentsRedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/instruments/fluss': {
      id: '/hub/instruments/fluss'
      path: '/hub/instruments/fluss'
      fullPath: '/hub/instruments/fluss'
      preLoaderRoute: typeof HubInstrumentsFlussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/instruments/database': {
      id: '/hub/instruments/database'
      path: '/hub/instruments/database'
      fullPath: '/hub/instruments/database'
      preLoaderRoute: typeof HubInstrumentsDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/insights/metrics': {
      id: '/hub/insights/metrics'
      path: '/hub/insights/metrics'
      fullPath: '/hub/insights/metrics'
      preLoaderRoute: typeof HubInsightsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/insights/health': {
      id: '/hub/insights/health'
      path: '/hub/insights/health'
      fullPath: '/hub/insights/health'
      preLoaderRoute: typeof HubInsightsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/insights/bottlenecks': {
      id: '/hub/insights/bottlenecks'
      path: '/hub/insights/bottlenecks'
      fullPath: '/hub/insights/bottlenecks'
      preLoaderRoute: typeof HubInsightsBottlenecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/deployments/$name': {
      id: '/hub/deployments/$name'
      path: '/hub/deployments/$name'
      fullPath: '/hub/deployments/$name'
      preLoaderRoute: typeof HubDeploymentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/admin/simulations': {
      id: '/hub/admin/simulations'
      path: '/hub/admin/simulations'
      fullPath: '/hub/admin/simulations'
      preLoaderRoute: typeof HubAdminSimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/simulations/$runId': {
      id: '/admin/simulations/$runId'
      path: '/admin/simulations/$runId'
      fullPath: '/admin/simulations/$runId'
      preLoaderRoute: typeof AdminSimulationsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$instrumentName/schema-registry/': {
      id: '/instruments/$instrumentName/schema-registry/'
      path: '/schema-registry'
      fullPath: '/instruments/$instrumentName/schema-registry/'
      preLoaderRoute: typeof InstrumentsInstrumentNameSchemaRegistryIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/redis/': {
      id: '/instruments/$instrumentName/redis/'
      path: '/redis'
      fullPath: '/instruments/$instrumentName/redis/'
      preLoaderRoute: typeof InstrumentsInstrumentNameRedisIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/fluss/': {
      id: '/instruments/$instrumentName/fluss/'
      path: '/fluss'
      fullPath: '/instruments/$instrumentName/fluss/'
      preLoaderRoute: typeof InstrumentsInstrumentNameFlussIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/database/': {
      id: '/instruments/$instrumentName/database/'
      path: '/database'
      fullPath: '/instruments/$instrumentName/database/'
      preLoaderRoute: typeof InstrumentsInstrumentNameDatabaseIndexRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/schema-registry/subject': {
      id: '/instruments/$instrumentName/schema-registry/subject'
      path: '/schema-registry/subject'
      fullPath: '/instruments/$instrumentName/schema-registry/subject'
      preLoaderRoute: typeof InstrumentsInstrumentNameSchemaRegistrySubjectRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/schema-registry/compatibility': {
      id: '/instruments/$instrumentName/schema-registry/compatibility'
      path: '/schema-registry/compatibility'
      fullPath: '/instruments/$instrumentName/schema-registry/compatibility'
      preLoaderRoute: typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/redis/server': {
      id: '/instruments/$instrumentName/redis/server'
      path: '/redis/server'
      fullPath: '/instruments/$instrumentName/redis/server'
      preLoaderRoute: typeof InstrumentsInstrumentNameRedisServerRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/redis/key': {
      id: '/instruments/$instrumentName/redis/key'
      path: '/redis/key'
      fullPath: '/instruments/$instrumentName/redis/key'
      preLoaderRoute: typeof InstrumentsInstrumentNameRedisKeyRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/fluss/table': {
      id: '/instruments/$instrumentName/fluss/table'
      path: '/fluss/table'
      fullPath: '/instruments/$instrumentName/fluss/table'
      preLoaderRoute: typeof InstrumentsInstrumentNameFlussTableRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/fluss/health': {
      id: '/instruments/$instrumentName/fluss/health'
      path: '/fluss/health'
      fullPath: '/instruments/$instrumentName/fluss/health'
      preLoaderRoute: typeof InstrumentsInstrumentNameFlussHealthRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/database/table': {
      id: '/instruments/$instrumentName/database/table'
      path: '/database/table'
      fullPath: '/instruments/$instrumentName/database/table'
      preLoaderRoute: typeof InstrumentsInstrumentNameDatabaseTableRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
    '/instruments/$instrumentName/database/query': {
      id: '/instruments/$instrumentName/database/query'
      path: '/database/query'
      fullPath: '/instruments/$instrumentName/database/query'
      preLoaderRoute: typeof InstrumentsInstrumentNameDatabaseQueryRouteImport
      parentRoute: typeof InstrumentsInstrumentNameRoute
    }
  }
}

interface InstrumentsInstrumentNameRouteChildren {
  InstrumentsInstrumentNameIndexRoute: typeof InstrumentsInstrumentNameIndexRoute
  InstrumentsInstrumentNameDatabaseQueryRoute: typeof InstrumentsInstrumentNameDatabaseQueryRoute
  InstrumentsInstrumentNameDatabaseTableRoute: typeof InstrumentsInstrumentNameDatabaseTableRoute
  InstrumentsInstrumentNameFlussHealthRoute: typeof InstrumentsInstrumentNameFlussHealthRoute
  InstrumentsInstrumentNameFlussTableRoute: typeof InstrumentsInstrumentNameFlussTableRoute
  InstrumentsInstrumentNameRedisKeyRoute: typeof InstrumentsInstrumentNameRedisKeyRoute
  InstrumentsInstrumentNameRedisServerRoute: typeof InstrumentsInstrumentNameRedisServerRoute
  InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute: typeof InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute
  InstrumentsInstrumentNameSchemaRegistrySubjectRoute: typeof InstrumentsInstrumentNameSchemaRegistrySubjectRoute
  InstrumentsInstrumentNameDatabaseIndexRoute: typeof InstrumentsInstrumentNameDatabaseIndexRoute
  InstrumentsInstrumentNameFlussIndexRoute: typeof InstrumentsInstrumentNameFlussIndexRoute
  InstrumentsInstrumentNameRedisIndexRoute: typeof InstrumentsInstrumentNameRedisIndexRoute
  InstrumentsInstrumentNameSchemaRegistryIndexRoute: typeof InstrumentsInstrumentNameSchemaRegistryIndexRoute
}

const InstrumentsInstrumentNameRouteChildren: InstrumentsInstrumentNameRouteChildren =
  {
    InstrumentsInstrumentNameIndexRoute: InstrumentsInstrumentNameIndexRoute,
    InstrumentsInstrumentNameDatabaseQueryRoute:
      InstrumentsInstrumentNameDatabaseQueryRoute,
    InstrumentsInstrumentNameDatabaseTableRoute:
      InstrumentsInstrumentNameDatabaseTableRoute,
    InstrumentsInstrumentNameFlussHealthRoute:
      InstrumentsInstrumentNameFlussHealthRoute,
    InstrumentsInstrumentNameFlussTableRoute:
      InstrumentsInstrumentNameFlussTableRoute,
    InstrumentsInstrumentNameRedisKeyRoute:
      InstrumentsInstrumentNameRedisKeyRoute,
    InstrumentsInstrumentNameRedisServerRoute:
      InstrumentsInstrumentNameRedisServerRoute,
    InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute:
      InstrumentsInstrumentNameSchemaRegistryCompatibilityRoute,
    InstrumentsInstrumentNameSchemaRegistrySubjectRoute:
      InstrumentsInstrumentNameSchemaRegistrySubjectRoute,
    InstrumentsInstrumentNameDatabaseIndexRoute:
      InstrumentsInstrumentNameDatabaseIndexRoute,
    InstrumentsInstrumentNameFlussIndexRoute:
      InstrumentsInstrumentNameFlussIndexRoute,
    InstrumentsInstrumentNameRedisIndexRoute:
      InstrumentsInstrumentNameRedisIndexRoute,
    InstrumentsInstrumentNameSchemaRegistryIndexRoute:
      InstrumentsInstrumentNameSchemaRegistryIndexRoute,
  }

const InstrumentsInstrumentNameRouteWithChildren =
  InstrumentsInstrumentNameRoute._addFileChildren(
    InstrumentsInstrumentNameRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorsRoute: ErrorsRoute,
  JobManagerRoute: JobManagerRoute,
  LogsRoute: LogsRoute,
  OverviewRoute: OverviewRoute,
  CatalogsAvailableRoute: CatalogsAvailableRoute,
  CatalogsExploreRoute: CatalogsExploreRoute,
  DeploymentsNameRoute: DeploymentsNameRoute,
  Hub_shellTestRoute: Hub_shellTestRoute,
  HubErrorsRoute: HubErrorsRoute,
  HubJobManagerRoute: HubJobManagerRoute,
  HubLogsRoute: HubLogsRoute,
  HubSandboxRoute: HubSandboxRoute,
  HubSqlExplorerRoute: HubSqlExplorerRoute,
  InsightsBottlenecksRoute: InsightsBottlenecksRoute,
  InsightsHealthRoute: InsightsHealthRoute,
  InsightsMetricsRoute: InsightsMetricsRoute,
  InstrumentsInstrumentNameRoute: InstrumentsInstrumentNameRouteWithChildren,
  JobsIdRoute: JobsIdRoute,
  JobsCompletedRoute: JobsCompletedRoute,
  JobsRunningRoute: JobsRunningRoute,
  JobsSubmitRoute: JobsSubmitRoute,
  MaterializedTablesNameRoute: MaterializedTablesNameRoute,
  MonitoringAlertsRoute: MonitoringAlertsRoute,
  MonitoringCheckpointsRoute: MonitoringCheckpointsRoute,
  SandboxEditorRoute: SandboxEditorRoute,
  TaskManagersIdRoute: TaskManagersIdRoute,
  CatalogsIndexRoute: CatalogsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  HubIndexRoute: HubIndexRoute,
  InstrumentsIndexRoute: InstrumentsIndexRoute,
  MaterializedTablesIndexRoute: MaterializedTablesIndexRoute,
  SandboxIndexRoute: SandboxIndexRoute,
  TaskManagersIndexRoute: TaskManagersIndexRoute,
  AdminSimulationsRunIdRoute: AdminSimulationsRunIdRoute,
  HubAdminSimulationsRoute: HubAdminSimulationsRoute,
  HubDeploymentsNameRoute: HubDeploymentsNameRoute,
  HubInsightsBottlenecksRoute: HubInsightsBottlenecksRoute,
  HubInsightsHealthRoute: HubInsightsHealthRoute,
  HubInsightsMetricsRoute: HubInsightsMetricsRoute,
  HubInstrumentsDatabaseRoute: HubInstrumentsDatabaseRoute,
  HubInstrumentsFlussRoute: HubInstrumentsFlussRoute,
  HubInstrumentsRedisRoute: HubInstrumentsRedisRoute,
  HubInstrumentsSchemaRegistryRoute: HubInstrumentsSchemaRegistryRoute,
  HubJobsIdRoute: HubJobsIdRoute,
  HubJobsCompletedRoute: HubJobsCompletedRoute,
  HubJobsRunningRoute: HubJobsRunningRoute,
  HubJobsSubmitRoute: HubJobsSubmitRoute,
  HubMaterializedTablesNameRoute: HubMaterializedTablesNameRoute,
  HubMonitoringAlertsRoute: HubMonitoringAlertsRoute,
  HubMonitoringCheckpointsRoute: HubMonitoringCheckpointsRoute,
  HubTaskManagersIdRoute: HubTaskManagersIdRoute,
  AdminBenchmarksIndexRoute: AdminBenchmarksIndexRoute,
  AdminSimulationsIndexRoute: AdminSimulationsIndexRoute,
  HubCatalogsIndexRoute: HubCatalogsIndexRoute,
  HubDeploymentsIndexRoute: HubDeploymentsIndexRoute,
  HubInstrumentsIndexRoute: HubInstrumentsIndexRoute,
  HubMaterializedTablesIndexRoute: HubMaterializedTablesIndexRoute,
  HubTaskManagersIndexRoute: HubTaskManagersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
