FROM alpine:3.21

RUN adduser -D -u 1000 reactor

COPY reactor-server /usr/local/bin/reactor-server
COPY dashboard/ /app/dashboard/

ENV STATIC_DIR=/app/dashboard

USER reactor

EXPOSE 8080

ENTRYPOINT ["reactor-server"]
