package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"errors"
	"fmt"

	"github.com/sandboxws/flink-reactor-console/server/internal/alerts"
	"github.com/sandboxws/flink-reactor-console/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor-console/server/internal/storage"
	"github.com/sandboxws/flink-reactor-console/server/internal/store"
)

// CreateAlertRule is the resolver for the createAlertRule field.
func (r *mutationResolver) CreateAlertRule(ctx context.Context, input model.CreateAlertRuleInput) (*model.AlertRule, error) {
	if r.Stores == nil {
		return nil, fmt.Errorf("storage not configured")
	}
	condJSON, err := conditionInputToJSON(*input.Condition)
	if err != nil {
		return nil, err
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	owner := ""
	if input.Owner != nil {
		owner = *input.Owner
	}
	enabled := true
	if input.Enabled != nil {
		enabled = *input.Enabled
	}
	rule, err := r.Stores.Alerts.CreateRule(ctx, store.AlertRuleInput{
		Name:        input.Name,
		Description: desc,
		Condition:   condJSON,
		Severity:    string(input.Severity),
		Owner:       owner,
		Enabled:     enabled,
		IsPreset:    false,
	})
	if err != nil {
		return nil, err
	}
	return dbRuleToModel(*rule)
}

// UpdateAlertRule is the resolver for the updateAlertRule field.
func (r *mutationResolver) UpdateAlertRule(ctx context.Context, id string, input model.UpdateAlertRuleInput) (*model.AlertRule, error) {
	if r.Stores == nil {
		return nil, fmt.Errorf("storage not configured")
	}
	ruleID, err := parseInt64ID(id)
	if err != nil {
		return nil, err
	}
	condJSON, err := conditionInputToJSON(*input.Condition)
	if err != nil {
		return nil, err
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	owner := ""
	if input.Owner != nil {
		owner = *input.Owner
	}
	rule, err := r.Stores.Alerts.UpdateRule(ctx, ruleID, store.AlertRuleInput{
		Name:        input.Name,
		Description: desc,
		Condition:   condJSON,
		Severity:    string(input.Severity),
		Owner:       owner,
		Enabled:     input.Enabled,
	})
	if err != nil {
		return nil, err
	}
	return dbRuleToModel(*rule)
}

// DeleteAlertRule is the resolver for the deleteAlertRule field.
func (r *mutationResolver) DeleteAlertRule(ctx context.Context, id string) (*model.DeleteResult, error) {
	if r.Stores == nil {
		return nil, fmt.Errorf("storage not configured")
	}
	ruleID, err := parseInt64ID(id)
	if err != nil {
		return nil, err
	}
	if err := r.Stores.Alerts.ResolveByRule(ctx, ruleID); err != nil {
		return nil, err
	}
	if err := r.Stores.Alerts.DeleteRule(ctx, ruleID); err != nil {
		if errors.Is(err, store.ErrAlertRuleNotFound) {
			return &model.DeleteResult{Success: false}, nil
		}
		return nil, err
	}
	return &model.DeleteResult{Success: true}, nil
}

// AcknowledgeAlert is the resolver for the acknowledgeAlert field.
func (r *mutationResolver) AcknowledgeAlert(ctx context.Context, id string, note *string) (*model.AlertInstance, error) {
	if r.Stores == nil {
		return nil, fmt.Errorf("storage not configured")
	}
	instID, err := parseInt64ID(id)
	if err != nil {
		return nil, err
	}
	inst, err := r.Stores.Alerts.TransitionInstance(ctx, instID, storage.AlertStateAcknowledged)
	if err != nil {
		return nil, err
	}
	n := ""
	if note != nil {
		n = *note
	}
	if _, err := r.Stores.Alerts.CreateAck(ctx, instID, "", n); err != nil {
		return nil, err
	}
	return dbInstanceToModel(*inst), nil
}

// SilenceAlert is the resolver for the silenceAlert field.
func (r *mutationResolver) SilenceAlert(ctx context.Context, id string) (*model.AlertInstance, error) {
	if r.Stores == nil {
		return nil, fmt.Errorf("storage not configured")
	}
	instID, err := parseInt64ID(id)
	if err != nil {
		return nil, err
	}
	inst, err := r.Stores.Alerts.TransitionInstance(ctx, instID, storage.AlertStateSilenced)
	if err != nil {
		return nil, err
	}
	return dbInstanceToModel(*inst), nil
}

// ResolveAlert is the resolver for the resolveAlert field.
func (r *mutationResolver) ResolveAlert(ctx context.Context, id string) (*model.AlertInstance, error) {
	if r.Stores == nil {
		return nil, fmt.Errorf("storage not configured")
	}
	instID, err := parseInt64ID(id)
	if err != nil {
		return nil, err
	}
	inst, err := r.Stores.Alerts.TransitionInstance(ctx, instID, storage.AlertStateResolved)
	if err != nil {
		return nil, err
	}
	return dbInstanceToModel(*inst), nil
}

// AlertRules is the resolver for the alertRules field.
func (r *queryResolver) AlertRules(ctx context.Context, enabledOnly *bool) ([]*model.AlertRule, error) {
	if r.Stores == nil {
		return []*model.AlertRule{}, nil
	}
	only := false
	if enabledOnly != nil {
		only = *enabledOnly
	}
	rules, err := r.Stores.Alerts.ListRules(ctx, only)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AlertRule, 0, len(rules))
	for _, rule := range rules {
		m, err := dbRuleToModel(rule)
		if err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, nil
}

// AlertRule is the resolver for the alertRule field.
func (r *queryResolver) AlertRule(ctx context.Context, id string) (*model.AlertRule, error) {
	if r.Stores == nil {
		return nil, nil
	}
	ruleID, err := parseInt64ID(id)
	if err != nil {
		return nil, err
	}
	rule, err := r.Stores.Alerts.GetRule(ctx, ruleID)
	if errors.Is(err, store.ErrAlertRuleNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return dbRuleToModel(*rule)
}

// ActiveAlerts is the resolver for the activeAlerts field.
func (r *queryResolver) ActiveAlerts(ctx context.Context) ([]*model.AlertInstance, error) {
	if r.Stores == nil {
		return []*model.AlertInstance{}, nil
	}
	insts, err := r.Stores.Alerts.ListActiveInstances(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AlertInstance, 0, len(insts))
	for _, inst := range insts {
		out = append(out, dbInstanceToModel(inst))
	}
	return out, nil
}

// AlertHistory is the resolver for the alertHistory field.
func (r *queryResolver) AlertHistory(ctx context.Context, filter *model.AlertHistoryFilterInput) (*model.AlertHistoryPage, error) {
	if r.Stores == nil {
		return &model.AlertHistoryPage{Instances: []*model.AlertInstance{}, Total: 0}, nil
	}
	f := store.AlertHistoryFilter{Limit: 100}
	if filter != nil {
		if filter.RuleID != nil {
			id, err := parseInt64ID(*filter.RuleID)
			if err != nil {
				return nil, err
			}
			f.RuleID = &id
		}
		if filter.State != nil {
			s := string(*filter.State)
			f.State = &s
		}
		if after, err := parseTimePtr(filter.After); err != nil {
			return nil, err
		} else if after != nil {
			f.After = after
		}
		if before, err := parseTimePtr(filter.Before); err != nil {
			return nil, err
		} else if before != nil {
			f.Before = before
		}
		if filter.Limit != nil && *filter.Limit > 0 {
			f.Limit = *filter.Limit
		}
		if filter.Offset != nil && *filter.Offset > 0 {
			f.Offset = *filter.Offset
		}
	}
	insts, err := r.Stores.Alerts.QueryHistory(ctx, f)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AlertInstance, 0, len(insts))
	for _, inst := range insts {
		out = append(out, dbInstanceToModel(inst))
	}
	return &model.AlertHistoryPage{Instances: out, Total: len(out)}, nil
}

// AlertFired is the resolver for the alertFired field.
func (r *subscriptionResolver) AlertFired(ctx context.Context) (<-chan *model.AlertInstance, error) {
	return subscribeInstance(ctx, r.AlertEngine, alerts.EventFired, "alertFired")
}

// AlertResolved is the resolver for the alertResolved field.
func (r *subscriptionResolver) AlertResolved(ctx context.Context) (<-chan *model.AlertInstance, error) {
	return subscribeInstance(ctx, r.AlertEngine, alerts.EventResolved, "alertResolved")
}
