package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"strconv"

	"github.com/sandboxws/flink-reactor/apps/server/internal/flink"
	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// CancelApplication is the resolver for the cancelApplication field.
func (r *mutationResolver) CancelApplication(ctx context.Context, id string, cluster *string) (*model.CancelApplicationResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if err := conn.Service.CancelApplication(ctx, id); err != nil {
		return &model.CancelApplicationResult{Success: false}, err
	}
	return &model.CancelApplicationResult{Success: true}, nil
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context, cluster *string) ([]*model.Application, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	apps, err := conn.Service.ApplicationsOverview(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Application, 0, len(apps))
	for i := range apps {
		result = append(result, mapApplication(&apps[i]))
	}
	return result, nil
}

// Application is the resolver for the application field.
func (r *queryResolver) Application(ctx context.Context, id string, cluster *string) (*model.Application, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	app, err := conn.Service.ApplicationDetail(ctx, id)
	if err != nil {
		return nil, err
	}
	if app == nil {
		return nil, nil
	}
	return mapApplication(app), nil
}

// mapApplication converts a Flink ApplicationOverview into the GraphQL model
// (Flink 2.3+, FLIP-549).
func mapApplication(a *flink.ApplicationOverview) *model.Application {
	var startTime *string
	if a.StartTime > 0 {
		s := strconv.FormatInt(a.StartTime, 10)
		startTime = &s
	}
	return &model.Application{
		ID:        a.ID,
		Name:      a.Name,
		State:     a.State,
		StartTime: startTime,
		JobCount:  a.JobCount,
	}
}
