package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor/apps/server/internal/k8s"
	"github.com/sandboxws/flink-reactor/apps/server/internal/observability"
)

// BlueGreenDeployments is the resolver for the blueGreenDeployments field.
func (r *queryResolver) BlueGreenDeployments(ctx context.Context, cluster *string, _ *string) ([]*model.BlueGreenDeployment, error) {
	if r.Manager == nil {
		return nil, fmt.Errorf("cluster manager not configured")
	}

	conn, err := r.Manager.Resolve(cluster)
	if err != nil {
		return nil, err
	}

	if conn.K8sService == nil {
		return []*model.BlueGreenDeployment{}, nil
	}

	deployments, err := conn.K8sService.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("listing blue-green deployments: %w", err)
	}

	// Update metrics
	observability.BlueGreenDeploymentsTotal.WithLabelValues(conn.Name).Set(float64(len(deployments)))
	stateCounts := make(map[string]float64)
	for _, d := range deployments {
		stateCounts[string(d.State)]++
	}
	for state, count := range stateCounts {
		observability.BlueGreenActiveState.WithLabelValues(state).Set(count)
	}

	result := make([]*model.BlueGreenDeployment, len(deployments))
	for i, d := range deployments {
		result[i] = mapBlueGreenDeployment(&d)
	}
	return result, nil
}

// BlueGreenDeployment is the resolver for the blueGreenDeployment field.
func (r *queryResolver) BlueGreenDeployment(ctx context.Context, name string, _ *string, cluster *string) (*model.BlueGreenDeployment, error) {
	if r.Manager == nil {
		return nil, fmt.Errorf("cluster manager not configured")
	}

	conn, err := r.Manager.Resolve(cluster)
	if err != nil {
		return nil, err
	}

	if conn.K8sService == nil {
		return nil, fmt.Errorf("kubernetes not configured for cluster %q", conn.Name)
	}

	d, err := conn.K8sService.Get(ctx, name)
	if err != nil {
		return nil, fmt.Errorf("getting blue-green deployment %q: %w", name, err)
	}

	return mapBlueGreenDeployment(d), nil
}

// BlueGreenStateChanged is the resolver for the blueGreenStateChanged field.
func (r *subscriptionResolver) BlueGreenStateChanged(ctx context.Context, cluster *string, _ *string) (<-chan *model.BlueGreenDeployment, error) {
	if r.Manager == nil {
		return nil, fmt.Errorf("cluster manager not configured")
	}

	conn, err := r.Manager.Resolve(cluster)
	if err != nil {
		return nil, err
	}

	if conn.K8sService == nil {
		return nil, fmt.Errorf("kubernetes not configured for cluster %q", conn.Name)
	}

	listener := conn.K8sService.EventBus().Subscribe()
	ch := make(chan *model.BlueGreenDeployment, 1)

	observability.ActiveSubscriptions.WithLabelValues("blueGreenStateChanged").Inc()
	go func() {
		defer observability.ActiveSubscriptions.WithLabelValues("blueGreenStateChanged").Dec()
		defer close(ch)
		defer listener.Close()

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-listener.Updates():
				if !ok {
					return
				}
				out := mapBlueGreenDeployment(&evt)
				select {
				case ch <- out:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

func mapBlueGreenDeployment(d *k8s.BlueGreenDeployment) *model.BlueGreenDeployment {
	state := mapBlueGreenState(d.State)
	result := &model.BlueGreenDeployment{
		Name:      d.Name,
		Namespace: d.Namespace,
		State:     state,
	}

	if d.JobStatus != "" {
		result.JobStatus = &d.JobStatus
	}
	if d.Error != "" {
		result.Error = &d.Error
	}
	if d.LastReconciledTimestamp != "" {
		result.LastReconciledTimestamp = &d.LastReconciledTimestamp
	}
	if d.AbortTimestamp != "" {
		result.AbortTimestamp = &d.AbortTimestamp
	}
	if d.DeploymentReadyTimestamp != "" {
		result.DeploymentReadyTimestamp = &d.DeploymentReadyTimestamp
	}
	if d.BlueDeploymentName != "" {
		result.BlueDeploymentName = &d.BlueDeploymentName
	}
	if d.GreenDeploymentName != "" {
		result.GreenDeploymentName = &d.GreenDeploymentName
	}
	if d.ActiveJobID != "" {
		result.ActiveJobID = &d.ActiveJobID
	}
	if d.PendingJobID != "" {
		result.PendingJobID = &d.PendingJobID
	}
	if d.AbortGracePeriod != "" {
		result.AbortGracePeriod = &d.AbortGracePeriod
	}
	if d.DeploymentDeletionDelay != "" {
		result.DeploymentDeletionDelay = &d.DeploymentDeletionDelay
	}

	return result
}

func mapBlueGreenState(state k8s.BlueGreenState) model.BlueGreenState {
	switch state {
	case k8s.StateInitializingBlue:
		return model.BlueGreenStateInitializingBlue
	case k8s.StateActiveBlue:
		return model.BlueGreenStateActiveBlue
	case k8s.StateActiveGreen:
		return model.BlueGreenStateActiveGreen
	case k8s.StateSavepointingBlue:
		return model.BlueGreenStateSavepointingBlue
	case k8s.StateSavepointingGreen:
		return model.BlueGreenStateSavepointingGreen
	case k8s.StateTransitioningBlue:
		return model.BlueGreenStateTransitioningToBlue
	case k8s.StateTransitioningGreen:
		return model.BlueGreenStateTransitioningToGreen
	default:
		return model.BlueGreenStateInitializingBlue
	}
}
