package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// Catalogs is the resolver for the catalogs field.
func (r *queryResolver) Catalogs(ctx context.Context, cluster *string) ([]*model.CatalogInfo, error) {
	catalogs, err := r.CatalogService.ListCatalogs(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.CatalogInfo, len(catalogs))
	for i, c := range catalogs {
		result[i] = &model.CatalogInfo{Name: c.Name, Source: c.Source}
	}
	return result, nil
}

// CatalogDatabases is the resolver for the catalogDatabases field.
func (r *queryResolver) CatalogDatabases(ctx context.Context, catalog string, cluster *string) ([]*model.CatalogDatabase, error) {
	databases, err := r.CatalogService.ListDatabases(ctx, catalog)
	if err != nil {
		return nil, err
	}

	result := make([]*model.CatalogDatabase, len(databases))
	for i, d := range databases {
		result[i] = &model.CatalogDatabase{Name: d.Name}
	}
	return result, nil
}

// CatalogTables is the resolver for the catalogTables field.
func (r *queryResolver) CatalogTables(ctx context.Context, catalog string, database string, cluster *string) ([]*model.CatalogTable, error) {
	tables, err := r.CatalogService.ListTables(ctx, catalog, database)
	if err != nil {
		return nil, err
	}

	result := make([]*model.CatalogTable, len(tables))
	for i, t := range tables {
		result[i] = &model.CatalogTable{Name: t.Name}
	}
	return result, nil
}

// CatalogColumns is the resolver for the catalogColumns field.
func (r *queryResolver) CatalogColumns(ctx context.Context, catalog string, database string, table string, cluster *string) ([]*model.ColumnInfo, error) {
	columns, err := r.CatalogService.ListColumns(ctx, catalog, database, table)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ColumnInfo, len(columns))
	for i, c := range columns {
		result[i] = &model.ColumnInfo{Name: c.Name, Type: c.Type}
	}
	return result, nil
}
