package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"strconv"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// FlinkConfig is the resolver for the flinkConfig field.
func (r *queryResolver) FlinkConfig(ctx context.Context, cluster *string) (*model.FlinkConfig, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	cfg, err := conn.Service.GetFlinkConfig(ctx)
	if err != nil {
		return nil, err
	}

	return &model.FlinkConfig{
		RefreshInterval: cfg.RefreshInterval,
		TimezoneName:    cfg.TimezoneName,
		TimezoneOffset:  strconv.Itoa(cfg.TimezoneOffset),
		FlinkVersion:    cfg.FlinkVersion,
		FlinkRevision:   cfg.FlinkRevision,
		Features: &model.FlinkFeatures{
			WebSubmit:  cfg.Features.WebSubmit,
			WebCancel:  cfg.Features.WebCancel,
			WebRescale: cfg.Features.WebRescale,
			WebHistory: cfg.Features.WebHistory,
		},
	}, nil
}

// DashboardConfig is the resolver for the dashboardConfig field.
func (r *queryResolver) DashboardConfig(_ context.Context) (*model.DashboardConfig, error) {
	var clusters []string
	var instrumentNames []string

	if r.Manager != nil {
		for _, info := range r.Manager.List() {
			clusters = append(clusters, info.Name)
		}
	}

	if r.InstrumentRegistry != nil {
		for _, inst := range r.InstrumentRegistry.List() {
			instrumentNames = append(instrumentNames, inst.Name)
		}
	}

	return &model.DashboardConfig{
		Clusters:    clusters,
		Instruments: instrumentNames,
	}, nil
}
