package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// FlussDatabases is the resolver for the flussDatabases field.
func (r *queryResolver) FlussDatabases(ctx context.Context, instrument string) ([]string, error) {
	fi, err := r.resolveFlussInstrument(instrument)
	if err != nil {
		return nil, err
	}
	return fi.Client().ListDatabases(ctx)
}

// FlussTables is the resolver for the flussTables field.
func (r *queryResolver) FlussTables(ctx context.Context, instrument string, database string) ([]*model.FlussTableSummary, error) {
	fi, err := r.resolveFlussInstrument(instrument)
	if err != nil {
		return nil, err
	}
	tables, err := fi.Client().ListTables(ctx, database)
	if err != nil {
		return nil, err
	}
	out := make([]*model.FlussTableSummary, len(tables))
	for i, t := range tables {
		out[i] = &model.FlussTableSummary{
			Database:      t.Database,
			Name:          t.Name,
			TableType:     string(t.TableType),
			BucketCount:   t.BucketCount,
			BucketKey:     orEmpty(t.BucketKey),
			PrimaryKey:    orEmpty(t.PrimaryKey),
			LastUpdatedMs: int(t.LastUpdatedMs),
		}
	}
	return out, nil
}

// FlussTable is the resolver for the flussTable field.
func (r *queryResolver) FlussTable(ctx context.Context, instrument string, database string, table string) (*model.FlussTableMetadata, error) {
	fi, err := r.resolveFlussInstrument(instrument)
	if err != nil {
		return nil, err
	}
	meta, err := fi.Client().GetTable(ctx, database, table)
	if err != nil {
		return nil, err
	}
	fields := make([]*model.FlussSchemaField, len(meta.Schema))
	for i, f := range meta.Schema {
		fields[i] = &model.FlussSchemaField{
			Name:     f.Name,
			Type:     f.Type,
			Nullable: f.Nullable,
			Comment:  f.Comment,
		}
	}
	props := make(map[string]any, len(meta.Properties))
	for k, v := range meta.Properties {
		props[k] = v
	}
	return &model.FlussTableMetadata{
		Database:      meta.Database,
		Name:          meta.Name,
		TableType:     string(meta.TableType),
		BucketCount:   meta.BucketCount,
		BucketKey:     orEmpty(meta.BucketKey),
		PrimaryKey:    orEmpty(meta.PrimaryKey),
		Schema:        fields,
		Properties:    props,
		Comment:       meta.Comment,
		LastUpdatedMs: int(meta.LastUpdatedMs),
	}, nil
}

// FlussTabletServers is the resolver for the flussTabletServers field.
func (r *queryResolver) FlussTabletServers(ctx context.Context, instrument string) ([]*model.FlussTabletServerHealth, error) {
	fi, err := r.resolveFlussInstrument(instrument)
	if err != nil {
		return nil, err
	}
	servers, err := fi.Client().ListTabletServers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.FlussTabletServerHealth, len(servers))
	for i, s := range servers {
		out[i] = &model.FlussTabletServerHealth{
			Server:     s.Server,
			Alive:      s.Alive,
			Leadership: s.Leadership,
		}
	}
	return out, nil
}

// orEmpty replaces a nil string slice with an empty one — GraphQL non-null
// list fields fail to encode nil, and the JSON tag on our Fluss types omits
// empty slices on the wire.
func orEmpty(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}
