package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"time"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor/apps/server/internal/storage"
	"github.com/sandboxws/flink-reactor/apps/server/internal/store"
)

// StorageStatus is the resolver for the storageStatus field.
func (r *queryResolver) StorageStatus(ctx context.Context) (*model.StorageStatus, error) {
	if !r.StorageConfig.Enabled || r.StoragePool == nil {
		return &model.StorageStatus{
			Enabled:          r.StorageConfig.Enabled,
			Connected:        false,
			MigrationVersion: "",
			TotalConns:       0,
			IdleConns:        0,
		}, nil
	}

	connected := storage.HealthCheck(ctx, r.StoragePool) == nil

	var migrationVersion string
	if connected {
		v, err := storage.MigrationVersion(ctx, r.StoragePool)
		if err == nil {
			migrationVersion = v
		}
	}

	stat := r.StoragePool.Stat()

	return &model.StorageStatus{
		Enabled:          true,
		Connected:        connected,
		MigrationVersion: migrationVersion,
		TotalConns:       int(stat.TotalConns()),
		IdleConns:        int(stat.IdleConns()),
	}, nil
}

// JobHistory is the resolver for the jobHistory field.
// It merges historical jobs from PostgreSQL with live jobs from the Flink API,
// deduplicating by (cluster, jid) and preferring live data for active jobs.
func (r *queryResolver) JobHistory(ctx context.Context, filter *model.JobHistoryFilter, pagination *model.PaginationInput, orderBy *model.OrderByInput) (*model.JobHistoryConnection, error) {
	empty := &model.JobHistoryConnection{
		Edges:    []*model.JobHistoryEdge{},
		PageInfo: &model.JobHistoryPageInfo{HasNextPage: false, TotalCount: 0},
	}

	// Build store filter from GraphQL input.
	var jf store.JobFilter
	if filter != nil {
		jf.ClusterID = filter.ClusterID
		jf.State = filter.State
		jf.Name = filter.Name

		// Custom time range takes precedence over preset timeRange.
		if filter.After != nil {
			t, err := time.Parse(time.RFC3339, *filter.After)
			if err != nil {
				return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
			}
			jf.After = &t
		}
		if filter.Before != nil {
			t, err := time.Parse(time.RFC3339, *filter.Before)
			if err != nil {
				return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
			}
			jf.Before = &t
		}

		// Apply preset timeRange if no custom after/before provided.
		if filter.TimeRange != nil && jf.After == nil && jf.Before == nil {
			t := timeRangeToAfter(*filter.TimeRange)
			jf.After = &t
		}
	}

	// Collect entries from both sources into a unified map keyed by "cluster|jid".
	entries := make(map[string]*model.JobHistoryEntry)

	// 1. Fetch historical jobs from PostgreSQL (large limit, no cursor pagination).
	if r.Stores != nil {
		cp := store.CursorPagination{First: 10000}
		jobs, _, err := r.Stores.Jobs.QueryJobs(ctx, jf, cp)
		if err != nil {
			return nil, fmt.Errorf("query job history: %w", err)
		}
		for _, j := range jobs {
			key := j.Cluster + "|" + j.JID
			entries[key] = dbJobToHistoryEntry(j)
		}
	}

	// 2. Fetch live jobs from all Flink clusters and overlay.
	if r.Manager != nil {
		for _, info := range r.Manager.List() {
			conn, err := r.Manager.Get(info.Name)
			if err != nil {
				continue
			}
			overview, err := conn.Service.GetJobs(ctx)
			if err != nil {
				continue // graceful degradation
			}
			for _, j := range overview.Jobs {
				entry := flinkJobToHistoryEntry(j, info.Name)

				// Apply filters to live jobs.
				if !matchesFilter(entry, filter) {
					continue
				}

				// Live data wins: overwrite any PG entry for the same job.
				key := info.Name + "|" + j.JID
				entries[key] = entry
			}
		}
	}

	if len(entries) == 0 {
		return empty, nil
	}

	// Flatten map to slice.
	allEntries := make([]*model.JobHistoryEntry, 0, len(entries))
	for _, e := range entries {
		allEntries = append(allEntries, e)
	}

	// Sort.
	sortJobEntries(allEntries, orderBy)

	totalCount := len(allEntries)

	// Paginate.
	pageSize := 20
	if pagination != nil && pagination.First != nil && *pagination.First > 0 {
		pageSize = *pagination.First
	}

	startIdx := 0
	if pagination != nil && pagination.After != nil {
		startIdx = findCursorIndex(allEntries, *pagination.After) + 1
	}

	endIdx := startIdx + pageSize
	if endIdx > len(allEntries) {
		endIdx = len(allEntries)
	}

	page := allEntries[startIdx:endIdx]
	edges := make([]*model.JobHistoryEdge, len(page))
	for i, e := range page {
		edges[i] = &model.JobHistoryEdge{
			Node:   e,
			Cursor: buildEntryCursor(e, i+startIdx),
		}
	}

	hasNext := endIdx < len(allEntries)
	var endCursor *string
	if hasNext && len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}

	return &model.JobHistoryConnection{
		Edges: edges,
		PageInfo: &model.JobHistoryPageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
			TotalCount:  totalCount,
		},
	}, nil
}

// CheckpointHistory is the resolver for the checkpointHistory field.
func (r *queryResolver) CheckpointHistory(ctx context.Context, filter *model.CheckpointHistoryFilter, pagination *model.PaginationInput) (*model.CheckpointHistoryConnection, error) {
	if r.Stores == nil {
		return &model.CheckpointHistoryConnection{
			Edges:    []*model.CheckpointHistoryEdge{},
			PageInfo: &model.CheckpointHistoryPageInfo{HasNextPage: false},
		}, nil
	}

	var cf store.CheckpointFilter
	if filter != nil {
		cf.ClusterID = filter.ClusterID
		cf.JobID = filter.JobID
		cf.Status = filter.Status
		cf.IsSavepoint = filter.IsSavepoint
		if filter.After != nil {
			t, err := time.Parse(time.RFC3339, *filter.After)
			if err != nil {
				return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
			}
			cf.After = &t
		}
		if filter.Before != nil {
			t, err := time.Parse(time.RFC3339, *filter.Before)
			if err != nil {
				return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
			}
			cf.Before = &t
		}
	}

	var cp store.CursorPagination
	if pagination != nil {
		if pagination.First != nil {
			cp.First = *pagination.First
		}
		cp.After = pagination.After
	}

	checkpoints, nextCursor, err := r.Stores.Checkpoints.QueryCheckpoints(ctx, cf, cp)
	if err != nil {
		return nil, fmt.Errorf("query checkpoint history: %w", err)
	}

	edges := make([]*model.CheckpointHistoryEdge, len(checkpoints))
	for i, c := range checkpoints {
		entry := dbCheckpointToStoredCheckpoint(c)
		edges[i] = &model.CheckpointHistoryEdge{
			Node:   entry,
			Cursor: store.EncodeCursor(c.TriggerTimestamp, fmt.Sprintf("%d", c.CheckpointID)),
		}
	}

	hasNext := nextCursor != ""
	var endCursor *string
	if hasNext {
		endCursor = &nextCursor
	}

	return &model.CheckpointHistoryConnection{
		Edges: edges,
		PageInfo: &model.CheckpointHistoryPageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
	}, nil
}

// ExceptionHistory is the resolver for the exceptionHistory field.
func (r *queryResolver) ExceptionHistory(ctx context.Context, filter *model.ExceptionHistoryFilter, pagination *model.PaginationInput) (*model.ExceptionHistoryConnection, error) {
	if r.Stores == nil {
		return &model.ExceptionHistoryConnection{
			Edges:    []*model.ExceptionHistoryEdge{},
			PageInfo: &model.ExceptionHistoryPageInfo{HasNextPage: false},
		}, nil
	}

	var ef store.ExceptionFilter
	if filter != nil {
		ef.ClusterID = filter.ClusterID
		ef.JobID = filter.JobID
		ef.ExceptionName = filter.ExceptionName
		if filter.After != nil {
			t, err := time.Parse(time.RFC3339, *filter.After)
			if err != nil {
				return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
			}
			ef.After = &t
		}
		if filter.Before != nil {
			t, err := time.Parse(time.RFC3339, *filter.Before)
			if err != nil {
				return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
			}
			ef.Before = &t
		}
	}

	var cp store.CursorPagination
	if pagination != nil {
		if pagination.First != nil {
			cp.First = *pagination.First
		}
		cp.After = pagination.After
	}

	exceptions, nextCursor, err := r.Stores.Exceptions.QueryExceptions(ctx, ef, cp)
	if err != nil {
		return nil, fmt.Errorf("query exception history: %w", err)
	}

	edges := make([]*model.ExceptionHistoryEdge, len(exceptions))
	for i, e := range exceptions {
		entry := dbExceptionToStoredException(e)
		edges[i] = &model.ExceptionHistoryEdge{
			Node:   entry,
			Cursor: store.EncodeCursor(&e.Timestamp, fmt.Sprintf("%d", e.ID)),
		}
	}

	hasNext := nextCursor != ""
	var endCursor *string
	if hasNext {
		endCursor = &nextCursor
	}

	return &model.ExceptionHistoryConnection{
		Edges: edges,
		PageInfo: &model.ExceptionHistoryPageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
	}, nil
}

// MetricHistory is the resolver for the metricHistory field.
func (r *queryResolver) MetricHistory(ctx context.Context, filter model.MetricHistoryFilter) ([]*model.MetricDataPoint, error) {
	if r.Stores == nil {
		return []*model.MetricDataPoint{}, nil
	}

	mf := store.MetricFilter{
		ClusterID:  &filter.ClusterID,
		SourceType: filter.SourceType,
		SourceID:   filter.SourceID,
		MetricID:   filter.MetricID,
	}
	if filter.After != nil {
		t, err := time.Parse(time.RFC3339, *filter.After)
		if err != nil {
			return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
		}
		mf.After = &t
	}
	if filter.Before != nil {
		t, err := time.Parse(time.RFC3339, *filter.Before)
		if err != nil {
			return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
		}
		mf.Before = &t
	}

	metrics, err := r.Stores.Metrics.QueryMetrics(ctx, mf)
	if err != nil {
		return nil, fmt.Errorf("query metric history: %w", err)
	}

	result := make([]*model.MetricDataPoint, len(metrics))
	for i, m := range metrics {
		result[i] = &model.MetricDataPoint{
			Value:      m.Value,
			CapturedAt: m.CapturedAt.Format(time.RFC3339),
		}
	}
	return result, nil
}

// ClusterOverviewHistory is the resolver for the clusterOverviewHistory field.
func (r *queryResolver) ClusterOverviewHistory(ctx context.Context, clusterID string, after *string, before *string) ([]*model.ClusterOverviewSnapshot, error) {
	if r.Stores == nil {
		return []*model.ClusterOverviewSnapshot{}, nil
	}

	var afterTime, beforeTime time.Time
	if after != nil {
		t, err := time.Parse(time.RFC3339, *after)
		if err != nil {
			return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
		}
		afterTime = t
	}
	if before != nil {
		t, err := time.Parse(time.RFC3339, *before)
		if err != nil {
			return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
		}
		beforeTime = t
	}

	snapshots, err := r.Stores.Metrics.QueryOverviewSnapshots(ctx, clusterID, afterTime, beforeTime)
	if err != nil {
		return nil, fmt.Errorf("query overview history: %w", err)
	}

	result := make([]*model.ClusterOverviewSnapshot, len(snapshots))
	for i, s := range snapshots {
		result[i] = &model.ClusterOverviewSnapshot{
			Cluster:        s.Cluster,
			FlinkVersion:   s.FlinkVersion,
			SlotsTotal:     s.SlotsTotal,
			SlotsAvailable: s.SlotsAvailable,
			JobsRunning:    s.JobsRunning,
			JobsFinished:   s.JobsFinished,
			JobsCancelled:  s.JobsCancelled,
			JobsFailed:     s.JobsFailed,
			TaskManagers:   s.TaskManagers,
			CapturedAt:     s.CapturedAt.Format(time.RFC3339),
		}
	}
	return result, nil
}
