package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"time"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor/apps/server/internal/storage"
	"github.com/sandboxws/flink-reactor/apps/server/internal/store"
)

// StorageStatus is the resolver for the storageStatus field.
func (r *queryResolver) StorageStatus(ctx context.Context) (*model.StorageStatus, error) {
	if !r.StorageConfig.Enabled || r.StoragePool == nil {
		return &model.StorageStatus{
			Enabled:          r.StorageConfig.Enabled,
			Connected:        false,
			MigrationVersion: "",
			TotalConns:       0,
			IdleConns:        0,
		}, nil
	}

	connected := storage.HealthCheck(ctx, r.StoragePool) == nil

	var migrationVersion string
	if connected {
		v, err := storage.MigrationVersion(ctx, r.StoragePool)
		if err == nil {
			migrationVersion = v
		}
	}

	stat := r.StoragePool.Stat()

	return &model.StorageStatus{
		Enabled:          true,
		Connected:        connected,
		MigrationVersion: migrationVersion,
		TotalConns:       int(stat.TotalConns()),
		IdleConns:        int(stat.IdleConns()),
	}, nil
}

// JobHistory is the resolver for the jobHistory field.
func (r *queryResolver) JobHistory(ctx context.Context, filter *model.JobHistoryFilter, pagination *model.PaginationInput) (*model.JobHistoryConnection, error) {
	if r.Stores == nil {
		return &model.JobHistoryConnection{
			Edges:    []*model.JobHistoryEdge{},
			PageInfo: &model.JobHistoryPageInfo{HasNextPage: false},
		}, nil
	}

	// Build store filter from GraphQL input.
	var jf store.JobFilter
	if filter != nil {
		jf.ClusterID = filter.ClusterID
		jf.State = filter.State
		jf.Name = filter.Name
		if filter.After != nil {
			t, err := time.Parse(time.RFC3339, *filter.After)
			if err != nil {
				return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
			}
			jf.After = &t
		}
		if filter.Before != nil {
			t, err := time.Parse(time.RFC3339, *filter.Before)
			if err != nil {
				return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
			}
			jf.Before = &t
		}
	}

	var cp store.CursorPagination
	if pagination != nil {
		if pagination.First != nil {
			cp.First = *pagination.First
		}
		cp.After = pagination.After
	}

	jobs, nextCursor, err := r.Stores.Jobs.QueryJobs(ctx, jf, cp)
	if err != nil {
		return nil, fmt.Errorf("query job history: %w", err)
	}

	edges := make([]*model.JobHistoryEdge, len(jobs))
	for i, j := range jobs {
		entry := dbJobToHistoryEntry(j)
		edges[i] = &model.JobHistoryEdge{
			Node:   entry,
			Cursor: buildJobCursor(j),
		}
	}

	hasNext := nextCursor != ""
	var endCursor *string
	if hasNext {
		endCursor = &nextCursor
	}

	return &model.JobHistoryConnection{
		Edges: edges,
		PageInfo: &model.JobHistoryPageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
	}, nil
}

// CheckpointHistory is the resolver for the checkpointHistory field.
func (r *queryResolver) CheckpointHistory(ctx context.Context, filter *model.CheckpointHistoryFilter, pagination *model.PaginationInput) (*model.CheckpointHistoryConnection, error) {
	if r.Stores == nil {
		return &model.CheckpointHistoryConnection{
			Edges:    []*model.CheckpointHistoryEdge{},
			PageInfo: &model.CheckpointHistoryPageInfo{HasNextPage: false},
		}, nil
	}

	var cf store.CheckpointFilter
	if filter != nil {
		cf.ClusterID = filter.ClusterID
		cf.JobID = filter.JobID
		cf.Status = filter.Status
		cf.IsSavepoint = filter.IsSavepoint
		if filter.After != nil {
			t, err := time.Parse(time.RFC3339, *filter.After)
			if err != nil {
				return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
			}
			cf.After = &t
		}
		if filter.Before != nil {
			t, err := time.Parse(time.RFC3339, *filter.Before)
			if err != nil {
				return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
			}
			cf.Before = &t
		}
	}

	var cp store.CursorPagination
	if pagination != nil {
		if pagination.First != nil {
			cp.First = *pagination.First
		}
		cp.After = pagination.After
	}

	checkpoints, nextCursor, err := r.Stores.Checkpoints.QueryCheckpoints(ctx, cf, cp)
	if err != nil {
		return nil, fmt.Errorf("query checkpoint history: %w", err)
	}

	edges := make([]*model.CheckpointHistoryEdge, len(checkpoints))
	for i, c := range checkpoints {
		entry := dbCheckpointToStoredCheckpoint(c)
		edges[i] = &model.CheckpointHistoryEdge{
			Node:   entry,
			Cursor: store.EncodeCursor(c.TriggerTimestamp, fmt.Sprintf("%d", c.CheckpointID)),
		}
	}

	hasNext := nextCursor != ""
	var endCursor *string
	if hasNext {
		endCursor = &nextCursor
	}

	return &model.CheckpointHistoryConnection{
		Edges: edges,
		PageInfo: &model.CheckpointHistoryPageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
	}, nil
}

// ExceptionHistory is the resolver for the exceptionHistory field.
func (r *queryResolver) ExceptionHistory(ctx context.Context, filter *model.ExceptionHistoryFilter, pagination *model.PaginationInput) (*model.ExceptionHistoryConnection, error) {
	if r.Stores == nil {
		return &model.ExceptionHistoryConnection{
			Edges:    []*model.ExceptionHistoryEdge{},
			PageInfo: &model.ExceptionHistoryPageInfo{HasNextPage: false},
		}, nil
	}

	var ef store.ExceptionFilter
	if filter != nil {
		ef.ClusterID = filter.ClusterID
		ef.JobID = filter.JobID
		ef.ExceptionName = filter.ExceptionName
		if filter.After != nil {
			t, err := time.Parse(time.RFC3339, *filter.After)
			if err != nil {
				return nil, fmt.Errorf("invalid 'after' timestamp: %w", err)
			}
			ef.After = &t
		}
		if filter.Before != nil {
			t, err := time.Parse(time.RFC3339, *filter.Before)
			if err != nil {
				return nil, fmt.Errorf("invalid 'before' timestamp: %w", err)
			}
			ef.Before = &t
		}
	}

	var cp store.CursorPagination
	if pagination != nil {
		if pagination.First != nil {
			cp.First = *pagination.First
		}
		cp.After = pagination.After
	}

	exceptions, nextCursor, err := r.Stores.Exceptions.QueryExceptions(ctx, ef, cp)
	if err != nil {
		return nil, fmt.Errorf("query exception history: %w", err)
	}

	edges := make([]*model.ExceptionHistoryEdge, len(exceptions))
	for i, e := range exceptions {
		entry := dbExceptionToStoredException(e)
		edges[i] = &model.ExceptionHistoryEdge{
			Node:   entry,
			Cursor: store.EncodeCursor(&e.Timestamp, fmt.Sprintf("%d", e.ID)),
		}
	}

	hasNext := nextCursor != ""
	var endCursor *string
	if hasNext {
		endCursor = &nextCursor
	}

	return &model.ExceptionHistoryConnection{
		Edges: edges,
		PageInfo: &model.ExceptionHistoryPageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
	}, nil
}
