package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor/apps/server/internal/storage"
)

// StorageStatus is the resolver for the storageStatus field.
func (r *queryResolver) StorageStatus(ctx context.Context) (*model.StorageStatus, error) {
	if !r.StorageConfig.Enabled || r.StoragePool == nil {
		return &model.StorageStatus{
			Enabled:          r.StorageConfig.Enabled,
			Connected:        false,
			MigrationVersion: "",
			TotalConns:       0,
			IdleConns:        0,
		}, nil
	}

	connected := storage.HealthCheck(ctx, r.StoragePool) == nil

	var migrationVersion string
	if connected {
		v, err := storage.MigrationVersion(ctx, r.StoragePool)
		if err == nil {
			migrationVersion = v
		}
	}

	stat := r.StoragePool.Stat()

	return &model.StorageStatus{
		Enabled:          true,
		Connected:        connected,
		MigrationVersion: migrationVersion,
		TotalConns:       int(stat.TotalConns()),
		IdleConns:        int(stat.IdleConns()),
	}, nil
}
