package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"github.com/sandboxws/flink-reactor-console/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor-console/server/internal/instruments/factory"
)

// TestInstrumentConnection is the resolver for the testInstrumentConnection field.
//
//nolint:revive // gqlgen owns this signature
func (r *mutationResolver) TestInstrumentConnection(ctx context.Context, typeArg string, name string, config map[string]any) (*model.InstrumentTestResult, error) {
	// Build a transient instrument — it is never registered and never persisted.
	inst, err := factory.New(typeArg, name, slog.Default())
	if err != nil {
		return instrumentTestFailure(err.Error()), nil
	}

	// The config may carry secrets (passwords, tokens); marshal it for Init but
	// never log it.
	cfgJSON, err := json.Marshal(config)
	if err != nil {
		return instrumentTestFailure(fmt.Sprintf("invalid config: %v", err)), nil
	}

	testCtx, cancel := context.WithTimeout(ctx, instrumentTestTimeout)
	defer cancel()

	start := time.Now()
	if err := inst.Init(testCtx, cfgJSON); err != nil {
		return instrumentTestFailure(err.Error()), nil
	}
	// Release the transient connection once Init succeeded (mirrors the
	// registry's Shutdown-only-after-Init lifecycle). Use a fresh context so a
	// timed-out probe still shuts down cleanly.
	defer func() { _ = inst.Shutdown(context.Background()) }()

	if err := inst.HealthCheck(testCtx); err != nil {
		return instrumentTestFailure(err.Error()), nil
	}

	latency := int(time.Since(start).Milliseconds())
	return &model.InstrumentTestResult{Ok: true, LatencyMs: &latency}, nil
}

// Instruments is the resolver for the instruments field.
//
//nolint:revive // gqlgen owns this signature
func (r *queryResolver) Instruments(ctx context.Context) ([]*model.InstrumentInfo, error) {
	if r.InstrumentRegistry == nil {
		return []*model.InstrumentInfo{}, nil
	}

	list := r.InstrumentRegistry.List()
	result := make([]*model.InstrumentInfo, len(list))
	for i, info := range list {
		var lastCheck *string
		if info.LastHealthCheck != nil {
			s := info.LastHealthCheck.Format("2006-01-02T15:04:05Z")
			lastCheck = &s
		}
		result[i] = &model.InstrumentInfo{
			Name:            info.Name,
			DisplayName:     info.DisplayName,
			Type:            info.Type,
			Version:         info.Version,
			Healthy:         info.Healthy,
			LastHealthCheck: lastCheck,
			Capabilities:    info.Capabilities,
		}
	}
	return result, nil
}
