package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// Instruments is the resolver for the instruments field.
func (r *queryResolver) Instruments(_ context.Context) ([]*model.InstrumentInfo, error) {
	if r.InstrumentRegistry == nil {
		return []*model.InstrumentInfo{}, nil
	}

	list := r.InstrumentRegistry.List()
	result := make([]*model.InstrumentInfo, len(list))
	for i, info := range list {
		var lastCheck *string
		if info.LastHealthCheck != nil {
			s := info.LastHealthCheck.Format("2006-01-02T15:04:05Z")
			lastCheck = &s
		}
		result[i] = &model.InstrumentInfo{
			Name:            info.Name,
			DisplayName:     info.DisplayName,
			Type:            info.Type,
			Version:         info.Version,
			Healthy:         info.Healthy,
			LastHealthCheck: lastCheck,
			Capabilities:    info.Capabilities,
		}
	}
	return result, nil
}
