package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/flink"
	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// DeleteJar is the resolver for the deleteJar field.
func (r *mutationResolver) DeleteJar(ctx context.Context, id string, cluster *string) (*model.DeleteResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	if err := conn.Service.DeleteJar(ctx, id); err != nil {
		return &model.DeleteResult{Success: false}, err
	}
	return &model.DeleteResult{Success: true}, nil
}

// RunJar is the resolver for the runJar field.
func (r *mutationResolver) RunJar(ctx context.Context, id string, entryClass *string, programArgs *string, parallelism *int, savepointPath *string, allowNonRestoredState *bool, cluster *string) (*model.JarRunResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	opts := &flink.JarRunRequest{}
	if entryClass != nil {
		opts.EntryClass = *entryClass
	}
	if programArgs != nil {
		opts.ProgramArgs = *programArgs
	}
	if parallelism != nil {
		opts.Parallelism = parallelism
	}
	if savepointPath != nil {
		opts.SavepointPath = *savepointPath
	}
	if allowNonRestoredState != nil {
		opts.AllowNonRestored = *allowNonRestoredState
	}

	result, err := conn.Service.RunJar(ctx, id, opts)
	if err != nil {
		return nil, err
	}

	return &model.JarRunResult{JobID: result.JobID}, nil
}

// Jars is the resolver for the jars field.
func (r *queryResolver) Jars(ctx context.Context, cluster *string) ([]*model.JarFile, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	jarList, err := conn.Service.GetJars(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.JarFile, len(jarList.Files))
	for i, j := range jarList.Files {
		entries := make([]*model.JarEntryPoint, len(j.Entry))
		for k, e := range j.Entry {
			entries[k] = &model.JarEntryPoint{
				Name:        e.Name,
				Description: e.Description,
			}
		}
		result[i] = &model.JarFile{
			ID:       j.ID,
			Name:     j.Name,
			Uploaded: i64(j.Uploaded),
			Entry:    entries,
		}
	}
	return result, nil
}
