package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// JobManager is the resolver for the jobManager field.
func (r *queryResolver) JobManager(ctx context.Context, cluster *string) (*model.JobManagerDetail, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	agg, err := conn.Service.GetJobManager(ctx)
	if err != nil {
		return nil, err
	}

	config := make([]*model.JMConfigEntry, len(agg.Config))
	for i, c := range agg.Config {
		config[i] = &model.JMConfigEntry{Key: c.Key, Value: c.Value}
	}

	var env *model.JMEnvironment
	if agg.Environment != nil {
		env = &model.JMEnvironment{
			Jvm: &model.JMEnvironmentJvm{
				Version: agg.Environment.JVM.Version,
				Arch:    agg.Environment.JVM.Arch,
				Options: agg.Environment.JVM.Options,
			},
			Classpath: agg.Environment.Classpath,
		}
	}

	return &model.JobManagerDetail{
		Config:      config,
		Environment: env,
		Metrics:     mapMetrics(agg.Metrics),
	}, nil
}
