package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"strconv"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// CancelJob is the resolver for the cancelJob field.
func (r *mutationResolver) CancelJob(ctx context.Context, id string, cluster *string) (*model.CancelJobResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	if err := conn.Service.CancelJob(ctx, id); err != nil {
		return &model.CancelJobResult{Success: false}, err
	}
	return &model.CancelJobResult{Success: true}, nil
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context, cluster *string) ([]*model.JobOverview, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	overview, err := conn.Service.GetJobs(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.JobOverview, len(overview.Jobs))
	for i, j := range overview.Jobs {
		result[i] = &model.JobOverview{
			ID:               j.JID,
			Name:             j.Name,
			State:            j.State,
			StartTime:        i64(j.StartTime),
			EndTime:          i64(j.EndTime),
			Duration:         i64(j.Duration),
			LastModification: i64(j.LastModification),
			Tasks: &model.TaskCounts{
				Created:      j.Tasks.Created,
				Scheduled:    j.Tasks.Scheduled,
				Deploying:    j.Tasks.Deploying,
				Running:      j.Tasks.Running,
				Finished:     j.Tasks.Finished,
				Canceling:    j.Tasks.Canceling,
				Canceled:     j.Tasks.Canceled,
				Failed:       j.Tasks.Failed,
				Reconciling:  j.Tasks.Reconciling,
				Initializing: j.Tasks.Initializing,
			},
		}
	}
	return result, nil
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string, cluster *string) (*model.JobDetail, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	agg, err := conn.Service.GetJobDetail(ctx, id)
	if err != nil {
		return nil, err
	}

	job := agg.Job

	// Map vertices.
	vertices := make([]*model.JobVertex, len(job.Vertices))
	for i, v := range job.Vertices {
		vertices[i] = mapVertex(&v)
	}

	// Map plan nodes.
	planNodes := make([]*model.PlanNode, len(job.Plan.Nodes))
	for i, n := range job.Plan.Nodes {
		var inputs []*model.PlanNodeInput
		for _, inp := range n.Inputs {
			inputs = append(inputs, &model.PlanNodeInput{
				Num:          inp.Num,
				ID:           inp.ID,
				ShipStrategy: inp.ShipStrategy,
				Exchange:     inp.Exchange,
			})
		}
		planNodes[i] = &model.PlanNode{
			ID:               n.ID,
			Parallelism:      n.Parallelism,
			Operator:         n.Operator,
			OperatorStrategy: n.OperatorStrategy,
			Description:      n.Description,
			Inputs:           inputs,
		}
	}

	// Map exceptions.
	var exceptions []*model.ExceptionEntry
	if agg.Exceptions != nil {
		for _, e := range agg.Exceptions.ExceptionHistory.Entries {
			exceptions = append(exceptions, &model.ExceptionEntry{
				ExceptionName: e.ExceptionName,
				Stacktrace:    e.Stacktrace,
				Timestamp:     i64(e.Timestamp),
				TaskName:      e.TaskName,
				Endpoint:      e.Endpoint,
				TaskManagerID: e.TaskManagerID,
			})
		}
	}

	// Map checkpoints.
	var checkpoints *model.CheckpointStats
	if agg.Checkpoints != nil {
		checkpoints = mapCheckpointStats(agg.Checkpoints)
	}

	// Map checkpoint config.
	var cpConfig *model.CheckpointConfig
	if agg.CheckpointConfig != nil {
		cc := agg.CheckpointConfig
		cpConfig = &model.CheckpointConfig{
			Mode:                             cc.Mode,
			Interval:                         i64(cc.Interval),
			Timeout:                          i64(cc.Timeout),
			MinPause:                         i64(cc.MinPause),
			MaxConcurrent:                    cc.MaxConcurrent,
			ExternalizedEnabled:              cc.Externalization.Enabled,
			ExternalizedDeleteOnCancellation: cc.Externalization.DeleteOnCancellation,
			UnalignedCheckpoints:             cc.UnalignedCheckpoints,
		}
	}

	// Map vertex details.
	var vertexDetails []*model.VertexDetail
	for vid, vd := range agg.VertexDetails {
		vertexDetails = append(vertexDetails, mapVertexDetail(vid, vd))
	}

	// Map watermarks.
	var watermarks []*model.VertexWatermarks
	for vid, wms := range agg.Watermarks {
		entries := make([]*model.WatermarkEntry, len(wms))
		for i, w := range wms {
			entries[i] = &model.WatermarkEntry{ID: w.ID, Value: w.Value}
		}
		watermarks = append(watermarks, &model.VertexWatermarks{
			VertexID:   vid,
			Watermarks: entries,
		})
	}

	// Map backpressure.
	var backPressure []*model.VertexBackPressure
	for vid, bp := range agg.BackPressure {
		subtasks := make([]*model.SubtaskBackPressure, len(bp.Subtasks))
		for i, s := range bp.Subtasks {
			subtasks[i] = &model.SubtaskBackPressure{
				Subtask:           s.Subtask,
				AttemptNumber:     s.AttemptNumber,
				BackpressureLevel: s.BackpressureLevel,
				Ratio:             s.Ratio,
				BusyRatio:         s.BusyRatio,
				IdleRatio:         s.IdleRatio,
			}
		}
		backPressure = append(backPressure, &model.VertexBackPressure{
			VertexID: vid,
			BackPressure: &model.BackPressureInfo{
				Status:            bp.Status,
				BackpressureLevel: bp.BackpressureLevel,
				EndTimestamp:      i64(bp.EndTimestamp),
				Subtasks:          subtasks,
			},
		})
	}

	// Map accumulators.
	var accumulators []*model.VertexAccumulators
	for vid, acc := range agg.Accumulators {
		entries := make([]*model.UserAccumulator, len(acc.UserAccumulators))
		for i, a := range acc.UserAccumulators {
			entries[i] = &model.UserAccumulator{
				Name:  a.Name,
				Type:  a.Type,
				Value: a.Value,
			}
		}
		accumulators = append(accumulators, &model.VertexAccumulators{
			VertexID:     vid,
			Accumulators: entries,
		})
	}

	return &model.JobDetail{
		ID:        job.JID,
		Name:      job.Name,
		State:     job.State,
		StartTime: i64(job.StartTime),
		EndTime:   i64(job.EndTime),
		Duration:  i64(job.Duration),
		Now:       i64(job.Now),
		Vertices:  vertices,
		Plan: &model.JobPlan{
			Jid:   job.Plan.JID,
			Name:  job.Plan.Name,
			Type:  job.Plan.Type,
			Nodes: planNodes,
		},
		Exceptions:       exceptions,
		Checkpoints:      checkpoints,
		CheckpointConfig: cpConfig,
		VertexDetails:    vertexDetails,
		Watermarks:       watermarks,
		BackPressure:     backPressure,
		Accumulators:     accumulators,
	}, nil
}

// VertexDetail is the resolver for the vertexDetail field.
func (r *queryResolver) VertexDetail(ctx context.Context, jobID string, vertexID string, cluster *string) (*model.VertexDetail, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	vd, err := conn.Service.GetVertexDetail(ctx, jobID, vertexID)
	if err != nil {
		return nil, err
	}

	return mapVertexDetail(vertexID, vd), nil
}

// SubtaskTimes is the resolver for the subtaskTimes field.
func (r *queryResolver) SubtaskTimes(ctx context.Context, jobID string, vertexID string, cluster *string) (*model.SubtaskTimes, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	st, err := conn.Service.GetSubtaskTimes(ctx, jobID, vertexID)
	if err != nil {
		return nil, err
	}

	subtasks := make([]*model.SubtaskTimesEntry, len(st.Subtasks))
	for i, s := range st.Subtasks {
		var timestamps []*model.TimestampEntry
		for k, v := range s.Timestamps {
			timestamps = append(timestamps, &model.TimestampEntry{Key: k, Value: i64(v)})
		}
		subtasks[i] = &model.SubtaskTimesEntry{
			Subtask:    s.Subtask,
			Host:       s.Host,
			Duration:   i64(s.Duration),
			Timestamps: timestamps,
		}
	}

	return &model.SubtaskTimes{
		ID:       st.ID,
		Name:     st.Name,
		Now:      i64(st.Now),
		Subtasks: subtasks,
	}, nil
}

// Flamegraph is the resolver for the flamegraph field.
func (r *queryResolver) Flamegraph(ctx context.Context, jobID string, vertexID string, typeArg string, cluster *string) (*model.Flamegraph, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	fg, err := conn.Service.GetVertexFlamegraph(ctx, jobID, vertexID, typeArg)
	if err != nil {
		return nil, err
	}

	return &model.Flamegraph{
		EndTimestamp: i64(fg.EndTimestamp),
		Data:         mapFlamegraphNode(&fg.Data),
	}, nil
}

// CheckpointDetail is the resolver for the checkpointDetail field.
func (r *queryResolver) CheckpointDetail(ctx context.Context, jobID string, checkpointID string, cluster *string) (*model.CheckpointHistoryEntry, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	cpID, err := strconv.ParseInt(checkpointID, 10, 64)
	if err != nil {
		return nil, err
	}

	detail, err := conn.Service.GetCheckpointDetail(ctx, jobID, cpID)
	if err != nil {
		return nil, err
	}

	return &model.CheckpointHistoryEntry{
		ID:                      i64(detail.ID),
		Status:                  detail.Status,
		IsSavepoint:             detail.IsSavepoint,
		TriggerTimestamp:        i64(detail.TriggerTimestamp),
		LatestAckTimestamp:      i64(detail.LatestAckTimestamp),
		StateSize:               i64(detail.StateSize),
		EndToEndDuration:        i64(detail.EndToEndDuration),
		ProcessedData:           derefI64(detail.ProcessedData),
		PersistedData:           derefI64(detail.PersistedData),
		NumSubtasks:             detail.NumSubtasks,
		NumAcknowledgedSubtasks: detail.NumAcknowledgedSubtask,
		CheckpointedSize:        i64p(detail.CheckpointedSize),
	}, nil
}
