package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// KafkaTopics is the resolver for the kafkaTopics field.
func (r *queryResolver) KafkaTopics(ctx context.Context, instrument string) ([]*model.KafkaTopic, error) {
	ki, err := r.resolveKafkaInstrument(instrument)
	if err != nil {
		return nil, err
	}

	topics, err := ki.Client().ListTopics(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.KafkaTopic, len(topics))
	for i, t := range topics {
		result[i] = &model.KafkaTopic{
			Name:              t.Name,
			PartitionCount:    t.PartitionCount,
			ReplicationFactor: t.ReplicationFactor,
			Internal:          t.Internal,
		}
	}
	return result, nil
}

// KafkaTopic is the resolver for the kafkaTopic field.
func (r *queryResolver) KafkaTopic(ctx context.Context, instrument string, name string) (*model.KafkaTopicDetail, error) {
	ki, err := r.resolveKafkaInstrument(instrument)
	if err != nil {
		return nil, err
	}

	detail, err := ki.Client().GetTopicDetail(ctx, name)
	if err != nil {
		return nil, err
	}

	partitions := make([]*model.KafkaPartition, len(detail.Partitions))
	for i, p := range detail.Partitions {
		replicas := make([]int, len(p.Replicas))
		for j, r := range p.Replicas {
			replicas[j] = int(r)
		}
		isr := make([]int, len(p.InSyncReplicas))
		for j, r := range p.InSyncReplicas {
			isr[j] = int(r)
		}
		partitions[i] = &model.KafkaPartition{
			ID:             int(p.ID),
			Leader:         int(p.Leader),
			Replicas:       replicas,
			InSyncReplicas: isr,
		}
	}

	configEntries := make([]*model.KafkaConfigEntry, len(detail.ConfigEntries))
	for i, c := range detail.ConfigEntries {
		configEntries[i] = &model.KafkaConfigEntry{
			Key:   c.Key,
			Value: c.Value,
		}
	}

	return &model.KafkaTopicDetail{
		Name:              detail.Name,
		PartitionCount:    detail.PartitionCount,
		ReplicationFactor: detail.ReplicationFactor,
		Internal:          detail.Internal,
		Partitions:        partitions,
		ConfigEntries:     configEntries,
		MessageCount:      int(detail.MessageCount),
	}, nil
}

// KafkaConsumerGroups is the resolver for the kafkaConsumerGroups field.
func (r *queryResolver) KafkaConsumerGroups(ctx context.Context, instrument string) ([]*model.KafkaConsumerGroup, error) {
	ki, err := r.resolveKafkaInstrument(instrument)
	if err != nil {
		return nil, err
	}

	groups, err := ki.Client().ListConsumerGroups(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.KafkaConsumerGroup, len(groups))
	for i, g := range groups {
		result[i] = &model.KafkaConsumerGroup{
			GroupID:     g.GroupID,
			State:       g.State,
			MemberCount: g.MemberCount,
			TotalLag:    int(g.TotalLag),
		}
	}
	return result, nil
}

// KafkaConsumerGroup is the resolver for the kafkaConsumerGroup field.
func (r *queryResolver) KafkaConsumerGroup(ctx context.Context, instrument string, groupID string) (*model.KafkaConsumerGroupDetail, error) {
	ki, err := r.resolveKafkaInstrument(instrument)
	if err != nil {
		return nil, err
	}

	detail, err := ki.Client().GetConsumerGroupDetail(ctx, groupID)
	if err != nil {
		return nil, err
	}

	members := make([]*model.KafkaGroupMember, len(detail.Members))
	for i, m := range detail.Members {
		assignments := make([]*model.KafkaTopicPartition, len(m.Assignments))
		for j, a := range m.Assignments {
			assignments[j] = &model.KafkaTopicPartition{
				Topic:     a.Topic,
				Partition: int(a.Partition),
			}
		}
		members[i] = &model.KafkaGroupMember{
			ClientID:    m.ClientID,
			ClientHost:  m.ClientHost,
			Assignments: assignments,
		}
	}

	offsets := make([]*model.KafkaPartitionOffset, len(detail.Offsets))
	for i, o := range detail.Offsets {
		offsets[i] = &model.KafkaPartitionOffset{
			Topic:           o.Topic,
			Partition:       int(o.Partition),
			CommittedOffset: int(o.CommittedOffset),
			EndOffset:       int(o.EndOffset),
			Lag:             int(o.Lag),
		}
	}

	return &model.KafkaConsumerGroupDetail{
		GroupID:      detail.GroupID,
		State:        detail.State,
		Protocol:     detail.Protocol,
		ProtocolType: detail.ProtocolType,
		Members:      members,
		Offsets:      offsets,
	}, nil
}
