package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor/apps/server/internal/materialized"
)

// SuspendMaterializedTable is the resolver for the suspendMaterializedTable field.
func (r *mutationResolver) SuspendMaterializedTable(ctx context.Context, name string, catalog string, cluster *string) (*model.MaterializedTable, error) {
	svc, err := r.resolveMaterializedService(cluster)
	if err != nil {
		return nil, err
	}

	table, err := svc.SuspendTable(ctx, name, catalog)
	if err != nil {
		return nil, err
	}
	return mapMaterializedTable(table), nil
}

// ResumeMaterializedTable is the resolver for the resumeMaterializedTable field.
func (r *mutationResolver) ResumeMaterializedTable(ctx context.Context, name string, catalog string, cluster *string) (*model.MaterializedTable, error) {
	svc, err := r.resolveMaterializedService(cluster)
	if err != nil {
		return nil, err
	}

	table, err := svc.ResumeTable(ctx, name, catalog)
	if err != nil {
		return nil, err
	}
	return mapMaterializedTable(table), nil
}

// RefreshMaterializedTable is the resolver for the refreshMaterializedTable field.
func (r *mutationResolver) RefreshMaterializedTable(ctx context.Context, name string, catalog string, cluster *string) (*model.MaterializedTable, error) {
	svc, err := r.resolveMaterializedService(cluster)
	if err != nil {
		return nil, err
	}

	table, err := svc.RefreshTable(ctx, name, catalog)
	if err != nil {
		return nil, err
	}
	return mapMaterializedTable(table), nil
}

// MaterializedTables is the resolver for the materializedTables field.
func (r *queryResolver) MaterializedTables(ctx context.Context, cluster *string, catalog *string) ([]*model.MaterializedTable, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if conn.SQLClient == nil {
		return []*model.MaterializedTable{}, nil
	}

	svc := materialized.NewService(conn.SQLClient)

	cat := ""
	if catalog != nil {
		cat = *catalog
	}

	tables, err := svc.ListTables(ctx, cat)
	if err != nil {
		return nil, err
	}

	result := make([]*model.MaterializedTable, len(tables))
	for i := range tables {
		result[i] = mapMaterializedTable(&tables[i])
	}
	return result, nil
}

// MaterializedTable is the resolver for the materializedTable field.
func (r *queryResolver) MaterializedTable(ctx context.Context, name string, catalog string, cluster *string) (*model.MaterializedTable, error) {
	svc, err := r.resolveMaterializedService(cluster)
	if err != nil {
		return nil, err
	}

	table, err := svc.GetTable(ctx, name, catalog)
	if err != nil {
		return nil, err
	}
	return mapMaterializedTable(table), nil
}
