package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// CheckSchemaCompatibility is the resolver for the checkSchemaCompatibility field.
func (r *mutationResolver) CheckSchemaCompatibility(ctx context.Context, instrument string, subject string, schema string, schemaType string) (*model.CompatibilityResult, error) {
	si, err := r.resolveSchemaRegistryInstrument(instrument)
	if err != nil {
		return nil, err
	}

	res, err := si.Client().CheckCompatibility(ctx, subject, schema, schemaType)
	if err != nil {
		return nil, err
	}

	messages := res.Messages
	if messages == nil {
		messages = []string{}
	}
	return &model.CompatibilityResult{
		IsCompatible: res.IsCompatible,
		Messages:     messages,
	}, nil
}

// SchemaSubjects is the resolver for the schemaSubjects field.
func (r *queryResolver) SchemaSubjects(ctx context.Context, instrument string) ([]*model.SchemaSubject, error) {
	si, err := r.resolveSchemaRegistryInstrument(instrument)
	if err != nil {
		return nil, err
	}

	subjects, err := si.Client().ListSubjects(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.SchemaSubject, len(subjects))
	for i, s := range subjects {
		out[i] = &model.SchemaSubject{
			Name:          s.Name,
			LatestVersion: s.LatestVersion,
			SchemaType:    s.SchemaType,
			SchemaID:      s.SchemaID,
			Compatibility: s.Compatibility,
		}
	}
	return out, nil
}

// SchemaVersions is the resolver for the schemaVersions field.
func (r *queryResolver) SchemaVersions(ctx context.Context, instrument string, subject string) ([]int, error) {
	si, err := r.resolveSchemaRegistryInstrument(instrument)
	if err != nil {
		return nil, err
	}
	return si.Client().GetSubjectVersions(ctx, subject)
}

// SchemaDetail is the resolver for the schemaDetail field.
func (r *queryResolver) SchemaDetail(ctx context.Context, instrument string, subject string, version int) (*model.SchemaDetail, error) {
	si, err := r.resolveSchemaRegistryInstrument(instrument)
	if err != nil {
		return nil, err
	}

	detail, err := si.Client().GetSchemaDetail(ctx, subject, version)
	if err != nil {
		return nil, err
	}

	refs := make([]*model.SchemaReference, len(detail.References))
	for i, r := range detail.References {
		refs[i] = &model.SchemaReference{
			Name:    r.Name,
			Subject: r.Subject,
			Version: r.Version,
		}
	}

	return &model.SchemaDetail{
		Subject:    detail.Subject,
		Version:    detail.Version,
		ID:         detail.ID,
		SchemaType: detail.SchemaType,
		Schema:     detail.Schema,
		References: refs,
	}, nil
}
