package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"strconv"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor/apps/server/internal/simulation"
)

// RunSimulation is the resolver for the runSimulation field.
func (r *mutationResolver) RunSimulation(ctx context.Context, input model.SimulationInput) (*model.SimulationRun, error) {
	if r.SimulationEngine == nil {
		return nil, fmt.Errorf("simulations require storage to be enabled")
	}

	run, err := r.SimulationEngine.Run(ctx, simulation.SimulationInput{
		Scenario:   input.Scenario,
		TargetJobs: input.TargetJobs,
		Parameters: input.Parameters,
		Cluster:    input.Cluster,
	})
	if err != nil {
		return nil, err
	}

	return mapSimulationRun(run), nil
}

// StopSimulation is the resolver for the stopSimulation field.
func (r *mutationResolver) StopSimulation(ctx context.Context, runID string) (*model.SimulationRun, error) {
	if r.SimulationEngine == nil {
		return nil, fmt.Errorf("simulations require storage to be enabled")
	}

	id, err := strconv.ParseInt(runID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid run ID: %s", runID)
	}

	run, err := r.SimulationEngine.Stop(ctx, id)
	if err != nil {
		return nil, err
	}

	return mapSimulationRun(run), nil
}

// SimulationPreflight is the resolver for the simulationPreflight field.
func (r *queryResolver) SimulationPreflight(ctx context.Context) ([]*model.PreflightCheck, error) {
	checks := simulation.RunPreflight(ctx)

	result := make([]*model.PreflightCheck, len(checks))
	for i, c := range checks {
		result[i] = &model.PreflightCheck{
			ID:       c.ID,
			Label:    c.Label,
			Status:   c.Status,
			Required: c.Required,
		}
		if c.Detail != "" {
			result[i].Detail = &c.Detail
		}
		if c.Fix != "" {
			result[i].Fix = &c.Fix
		}
	}
	return result, nil
}

// SimulationRuns is the resolver for the simulationRuns field.
func (r *queryResolver) SimulationRuns(ctx context.Context) ([]*model.SimulationRun, error) {
	if r.SimulationEngine == nil {
		return []*model.SimulationRun{}, nil
	}

	runs, err := r.SimulationEngine.ListRuns(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.SimulationRun, len(runs))
	for i := range runs {
		result[i] = mapSimulationRun(&runs[i])
	}
	return result, nil
}

// SimulationRun is the resolver for the simulationRun field.
func (r *queryResolver) SimulationRun(ctx context.Context, id string) (*model.SimulationRun, error) {
	if r.SimulationEngine == nil {
		return nil, nil
	}

	runID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid run ID: %s", id)
	}

	run, err := r.SimulationEngine.GetRun(ctx, runID)
	if err != nil {
		return nil, err
	}

	return mapSimulationRun(run), nil
}

// SimulationPresets is the resolver for the simulationPresets field.
func (r *queryResolver) SimulationPresets(ctx context.Context) ([]*model.SimulationPreset, error) {
	if r.SimulationEngine == nil {
		return []*model.SimulationPreset{}, nil
	}

	domainPresets := r.SimulationEngine.Presets()
	result := make([]*model.SimulationPreset, len(domainPresets))
	for i, p := range domainPresets {
		result[i] = &model.SimulationPreset{
			Name:              p.Name,
			Description:       p.Description,
			Scenario:          p.Scenario,
			DefaultParameters: p.DefaultParameters,
			Category:          p.Category,
		}
	}
	return result, nil
}
