package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/sandboxws/flink-reactor/apps/server/internal/flink"
	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// CreateSQLSession is the resolver for the createSQLSession field.
func (r *mutationResolver) CreateSQLSession(ctx context.Context, cluster *string) (*model.SQLSessionResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if conn.SQLClient == nil {
		return nil, fmt.Errorf("SQL Gateway not configured for cluster %q", conn.Name)
	}

	var result flink.SQLGatewaySessionResponse
	if err := conn.SQLClient.PostJSON(ctx, "/v3/sessions", map[string]any{}, &result); err != nil {
		return nil, err
	}

	// Replay bundled catalog DDL so sample databases are available in this session.
	if len(r.CatalogInitDDL) > 0 {
		for _, stmt := range r.CatalogInitDDL {
			var op flink.SQLGatewayOperationResponse
			body := map[string]string{"statement": stmt}
			submitPath := fmt.Sprintf("/v3/sessions/%s/statements", result.SessionHandle)
			if submitErr := conn.SQLClient.PostJSON(ctx, submitPath, body, &op); submitErr != nil {
				// Log but don't fail — partial catalog availability is acceptable.
				continue
			}
			// Fetch result to ensure DDL completes before the next statement.
			fetchPath := fmt.Sprintf("/v3/sessions/%s/operations/%s/result/0",
				result.SessionHandle, op.OperationHandle)
			var rs flink.SQLGatewayResultSet
			_ = conn.SQLClient.GetJSON(ctx, fetchPath, &rs)
		}
	}

	return &model.SQLSessionResult{SessionHandle: result.SessionHandle}, nil
}

// SubmitStatement is the resolver for the submitStatement field.
func (r *mutationResolver) SubmitStatement(ctx context.Context, sessionHandle string, statement string, cluster *string) (*model.SQLStatementResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if conn.SQLClient == nil {
		return nil, fmt.Errorf("SQL Gateway not configured for cluster %q", conn.Name)
	}

	var result flink.SQLGatewayOperationResponse
	body := map[string]string{"statement": statement}
	path := fmt.Sprintf("/v3/sessions/%s/statements", sessionHandle)
	if err := conn.SQLClient.PostJSON(ctx, path, body, &result); err != nil {
		return nil, err
	}
	return &model.SQLStatementResult{OperationHandle: result.OperationHandle}, nil
}

// FetchSQLResults is the resolver for the fetchSQLResults field.
func (r *mutationResolver) FetchSQLResults(ctx context.Context, sessionHandle string, operationHandle string, token *string, cluster *string) (*model.SQLFetchResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if conn.SQLClient == nil {
		return nil, fmt.Errorf("SQL Gateway not configured for cluster %q", conn.Name)
	}

	tok := "0"
	if token != nil {
		tok = *token
	}

	path := fmt.Sprintf("/v3/sessions/%s/operations/%s/result/%s", sessionHandle, operationHandle, tok)
	var resultSet flink.SQLGatewayResultSet
	if err := conn.SQLClient.GetJSON(ctx, path, &resultSet); err != nil {
		// Flink SQL Gateway returns HTTP 500 both when an operation is still
		// running (e.g., JDBC query in progress) AND when it has failed.
		// Check the operation status to distinguish these cases.
		var apiErr *flink.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == 500 {
			statusPath := fmt.Sprintf("/v3/sessions/%s/operations/%s/status", sessionHandle, operationHandle)
			var opStatus flink.SQLGatewayOperationStatusResponse
			if statusErr := conn.SQLClient.GetJSON(ctx, statusPath, &opStatus); statusErr == nil {
				if opStatus.Status == "ERROR" {
					// Operation failed — surface the original error.
					return nil, fmt.Errorf("query failed: %s", apiErr.Error())
				}
			}
			// Operation is still running — tell the client to retry.
			return &model.SQLFetchResult{
				Columns:   []*model.SQLColumn{},
				Rows:      [][]*string{},
				HasMore:   true,
				NextToken: &tok,
			}, nil
		}
		return nil, err
	}

	columns := make([]*model.SQLColumn, len(resultSet.Results.Columns))
	for i, c := range resultSet.Results.Columns {
		columns[i] = &model.SQLColumn{Name: c.Name, DataType: c.LogicalType.Type}
	}

	rows := make([][]*string, len(resultSet.Results.Data))
	for i, row := range resultSet.Results.Data {
		rows[i] = mapSQLRow(&row)
	}

	hasMore := resultSet.NextResultURI != nil
	var nextToken *string
	if resultSet.NextResultURI != nil {
		t := extractToken(*resultSet.NextResultURI)
		nextToken = &t
	}

	return &model.SQLFetchResult{
		Columns:   columns,
		Rows:      rows,
		HasMore:   hasMore,
		NextToken: nextToken,
	}, nil
}

// CloseSQLSession is the resolver for the closeSQLSession field.
func (r *mutationResolver) CloseSQLSession(ctx context.Context, sessionHandle string, cluster *string) (*model.SQLCloseResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if conn.SQLClient == nil {
		return nil, fmt.Errorf("SQL Gateway not configured for cluster %q", conn.Name)
	}

	path := fmt.Sprintf("/v3/sessions/%s", sessionHandle)
	if err := conn.SQLClient.Delete(ctx, path); err != nil {
		return &model.SQLCloseResult{Success: false}, err
	}
	return &model.SQLCloseResult{Success: true}, nil
}

// ExplainStatement is the resolver for the explainStatement field.
func (r *mutationResolver) ExplainStatement(ctx context.Context, sessionHandle string, statement string, cluster *string) (*model.SQLExplainResult, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}
	if conn.SQLClient == nil {
		return nil, fmt.Errorf("SQL Gateway not configured for cluster %q", conn.Name)
	}

	// Submit EXPLAIN statement
	var opResult flink.SQLGatewayOperationResponse
	body := map[string]string{"statement": "EXPLAIN " + statement}
	submitPath := fmt.Sprintf("/v3/sessions/%s/statements", sessionHandle)
	if err := conn.SQLClient.PostJSON(ctx, submitPath, body, &opResult); err != nil {
		return nil, err
	}

	// Poll for operation completion — SQL Gateway operations are async.
	statusPath := fmt.Sprintf("/v3/sessions/%s/operations/%s/status",
		sessionHandle, opResult.OperationHandle)
	for i := 0; i < 30; i++ {
		var opStatus flink.SQLGatewayOperationStatusResponse
		if err := conn.SQLClient.GetJSON(ctx, statusPath, &opStatus); err != nil {
			return nil, fmt.Errorf("failed to check EXPLAIN status: %w", err)
		}
		switch opStatus.Status {
		case "FINISHED":
			goto fetch
		case "ERROR":
			// Fetch results to get the actual error details — SQL Gateway returns
			// the exception as an HTTP 500 on the result endpoint.
			errFetchPath := fmt.Sprintf("/v3/sessions/%s/operations/%s/result/0",
				sessionHandle, opResult.OperationHandle)
			var errResult flink.SQLGatewayResultSet
			if fetchErr := conn.SQLClient.GetJSON(ctx, errFetchPath, &errResult); fetchErr != nil {
				// Extract the root cause from the Flink exception
				var apiErr *flink.APIError
				if errors.As(fetchErr, &apiErr) {
					// extractRootCause finds the deepest "Caused by:" line
					for _, entry := range apiErr.Errors {
						if cause := flink.ExtractRootCause(entry.Message); cause != "" {
							return nil, fmt.Errorf("EXPLAIN failed: %s", cause)
						}
					}
				}
				return nil, fmt.Errorf("EXPLAIN failed: %w", fetchErr)
			}
			return nil, fmt.Errorf("EXPLAIN failed on the Flink cluster")
		case "CANCELED":
			return nil, fmt.Errorf("EXPLAIN was canceled")
		}
		// Still RUNNING — wait before retrying
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(100 * time.Millisecond):
		}
	}
	return nil, fmt.Errorf("EXPLAIN timed out after 3s")

fetch:
	// Fetch the result
	fetchPath := fmt.Sprintf("/v3/sessions/%s/operations/%s/result/0",
		sessionHandle, opResult.OperationHandle)
	var resultSet flink.SQLGatewayResultSet
	if err := conn.SQLClient.GetJSON(ctx, fetchPath, &resultSet); err != nil {
		return nil, fmt.Errorf("failed to fetch EXPLAIN result: %w", err)
	}

	// Extract plan text from the result rows
	var planText string
	for _, row := range resultSet.Results.Data {
		for _, field := range row.Fields {
			if s, ok := field.(string); ok && s != "" {
				planText = s
				break
			}
		}
		if planText != "" {
			break
		}
	}

	if planText == "" {
		return nil, fmt.Errorf("EXPLAIN returned empty result")
	}

	// Detect format: JSON plans start with { or [
	format := "text"
	trimmed := strings.TrimSpace(planText)
	if len(trimmed) > 0 && (trimmed[0] == '{' || trimmed[0] == '[') {
		format = "json"
	}

	return &model.SQLExplainResult{
		PlanText: planText,
		Format:   format,
	}, nil
}
