package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/sandboxws/flink-reactor/apps/server/internal/graphql/model"
)

// TaskManagers is the resolver for the taskManagers field.
func (r *queryResolver) TaskManagers(ctx context.Context, cluster *string) ([]*model.TaskManagerOverview, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	tmList, err := conn.Service.GetTaskManagers(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.TaskManagerOverview, len(tmList.TaskManagers))
	for i := range tmList.TaskManagers {
		result[i] = mapTMItem(&tmList.TaskManagers[i])
	}
	return result, nil
}

// TaskManager is the resolver for the taskManager field.
func (r *queryResolver) TaskManager(ctx context.Context, id string, cluster *string) (*model.TaskManagerDetail, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	agg, err := conn.Service.GetTaskManagerDetail(ctx, id)
	if err != nil {
		return nil, err
	}

	tm := agg.Detail
	var allocatedSlots []*model.AllocatedSlot
	for _, s := range tm.AllocatedSlots {
		allocatedSlots = append(allocatedSlots, &model.AllocatedSlot{
			Index:    s.Index,
			JobID:    s.JobID,
			Resource: mapResourceProfile(&s.Resource),
		})
	}

	return &model.TaskManagerDetail{
		ID:                     tm.ID,
		Path:                   tm.Path,
		DataPort:               tm.DataPort,
		JmxPort:                tm.JMXPort,
		TimeSinceLastHeartbeat: i64(tm.TimeSinceLastHeartbeat),
		SlotsNumber:            tm.SlotsNumber,
		FreeSlots:              tm.FreeSlots,
		TotalResource:          mapResourceProfile(&tm.TotalResource),
		FreeResource:           mapResourceProfile(&tm.FreeResource),
		Hardware:               mapHardware(&tm.Hardware),
		MemoryConfiguration:    mapTMMemory(&tm.MemoryConfiguration),
		AllocatedSlots:         allocatedSlots,
		Metrics:                mapMetrics(agg.Metrics),
	}, nil
}

// TaskManagerLogs is the resolver for the taskManagerLogs field.
func (r *queryResolver) TaskManagerLogs(ctx context.Context, id string, cluster *string) ([]*model.TMLogEntry, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	var logList struct {
		Logs []struct {
			Name string `json:"name"`
			Size int64  `json:"size"`
		} `json:"logs"`
	}
	if err := conn.Service.Client().GetJSON(ctx, "/taskmanagers/"+id+"/logs", &logList); err != nil {
		return nil, err
	}

	result := make([]*model.TMLogEntry, len(logList.Logs))
	for i, l := range logList.Logs {
		result[i] = &model.TMLogEntry{Name: l.Name, Size: i64(l.Size)}
	}
	return result, nil
}

// TaskManagerThreadDump is the resolver for the taskManagerThreadDump field.
func (r *queryResolver) TaskManagerThreadDump(ctx context.Context, id string, cluster *string) ([]*model.ThreadDumpEntry, error) {
	conn, err := r.resolveCluster(cluster)
	if err != nil {
		return nil, err
	}

	var dump struct {
		ThreadInfos []struct {
			ThreadName            string `json:"threadName"`
			StringifiedThreadInfo string `json:"stringifiedThreadInfo"`
		} `json:"threadInfos"`
	}
	if err := conn.Service.Client().GetJSON(ctx, "/taskmanagers/"+id+"/thread-dump", &dump); err != nil {
		return nil, err
	}

	result := make([]*model.ThreadDumpEntry, len(dump.ThreadInfos))
	for i, t := range dump.ThreadInfos {
		result[i] = &model.ThreadDumpEntry{
			ThreadName:            t.ThreadName,
			StringifiedThreadInfo: t.StringifiedThreadInfo,
		}
	}
	return result, nil
}
