package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/sandboxws/flink-reactor-console/server/internal/graphql/model"
	"github.com/sandboxws/flink-reactor-console/server/internal/templates"
)

// InstantiateTemplate is the resolver for the instantiateTemplate field. It
// materialises the named template's scaffolded source (files + top-level
// pipeline TSX) from the embedded manifest. It performs NO deploy and touches no
// cluster, SQL Gateway, or operator — deploy is a separate, gated path
// (flows-09). `params` is accepted for forward compatibility but not yet applied
// (typed per-template options are a v0.1 Non-Goal).
func (r *mutationResolver) InstantiateTemplate(_ context.Context, name string, _ map[string]any) (*model.TemplateInstantiation, error) {
	if r.TemplateRegistry == nil {
		return nil, fmt.Errorf("template registry unavailable")
	}
	if _, ok := r.TemplateRegistry.Get(name); !ok {
		return nil, fmt.Errorf("unknown template %q", name)
	}
	src, ok := r.TemplateRegistry.Source(name)
	if !ok {
		return nil, fmt.Errorf("no source available for template %q", name)
	}

	files := make([]*model.TemplateFile, 0, len(src.Files))
	for _, f := range src.Files {
		files = append(files, &model.TemplateFile{Path: f.Path, Content: f.Content})
	}
	return &model.TemplateInstantiation{Files: files, PipelineTsx: src.PipelineTsx}, nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(_ context.Context, category *model.TemplateCategory) ([]*model.Template, error) {
	if r.TemplateRegistry == nil {
		return []*model.Template{}, nil
	}

	var entries []templates.Manifest
	if category != nil {
		entries = r.TemplateRegistry.ByCategory(string(*category))
	} else {
		entries = r.TemplateRegistry.All()
	}

	out := make([]*model.Template, 0, len(entries))
	for _, m := range entries {
		out = append(out, templateToModel(m))
	}
	return out, nil
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(_ context.Context, name string) (*model.Template, error) {
	if r.TemplateRegistry == nil {
		return nil, nil
	}
	m, ok := r.TemplateRegistry.Get(name)
	if !ok {
		return nil, nil
	}
	return templateToModel(m), nil
}
