import { createHash } from "node:crypto"
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs"
import { basename, dirname, extname, join, resolve } from "node:path"
import { pathToFileURL } from "node:url"
import type { ConstructNode } from "@flink-reactor/dsl/browser"
import { createJiti, type Jiti } from "jiti"
import type { LoadError, LoadErrorKind } from "./types.js"

// The language server owns its jiti instance (closely following the DSL loader
// in `src/cli/discovery.ts`, but anchored at the project dir — see `getJiti`)
// rather than calling `loadPipeline` directly. Why: node IDs are generated by
// module-level counter state inside
// `@flink-reactor/dsl`, and the ONLY way to reset *the exact copy the loaded
// pipeline uses* is to import the reset function through the SAME jiti that
// loads the pipeline. A sibling `import { resetNodeIdCounter }` resolves to a
// different module realm under jiti / a bundler / a test runner, leaving the
// counter to drift across re-synths. Sharing one jiti makes reset reliable in
// every environment (worker, tsx, vitest).

const jitiCache = new Map<string, Jiti>()

/** Resolve the `@/` alias target from tsconfig (mirrors the DSL loader). */
function resolveAtAlias(projectDir: string): string {
  const tsconfigPath = join(projectDir, "tsconfig.json")
  if (!existsSync(tsconfigPath)) return projectDir
  try {
    const raw = readFileSync(tsconfigPath, "utf-8").replace(/\/\/.*$/gm, "")
    const tsconfig = JSON.parse(raw)
    const mapping: string | undefined =
      tsconfig?.compilerOptions?.paths?.["@/*"]?.[0]
    if (!mapping) return projectDir
    return resolve(projectDir, mapping.replace(/\/?\*$/, ""))
  } catch {
    return projectDir
  }
}

function getJiti(projectDir: string): Jiti {
  const key = resolve(projectDir)
  let instance = jitiCache.get(key)
  if (!instance) {
    // Anchor jiti INSIDE the project so bare specifiers — above all
    // `@flink-reactor/dsl` — resolve against the project's own node_modules:
    // the complete, version-matched DSL the pipeline is written against. The
    // DSL's CLI loader can pass `import.meta.url` because it already runs from
    // inside the project's DSL package; the language server runs from its
    // bundled location, where `import.meta.url` resolves the server's vendored
    // fallback copy instead — which lacks the DSL's runtime deps (e.g. `effect`)
    // and may be a different version, breaking the reset and the in-realm
    // guarantee above.
    instance = createJiti(pathToFileURL(`${key}/`).href, {
      jsx: { runtime: "automatic", importSource: "@flink-reactor/dsl" },
      alias: { "@": resolveAtAlias(key) },
    })
    jitiCache.set(key, instance)
  }
  return instance
}

/** Reset the DSL node-id counter in the SAME realm the pipeline loads into, by
 *  importing the reset through this jiti instance. */
async function resetCounterInRealm(jiti: Jiti): Promise<void> {
  const dsl = (await jiti.import("@flink-reactor/dsl")) as {
    resetNodeIdCounter?: () => void
  }
  dsl.resetNodeIdCounter?.()
}

/** Typed failure thrown internally and mapped to a structured `LoadError`. */
class LoadFailure extends Error {
  constructor(
    readonly kind: LoadErrorKind,
    message: string,
  ) {
    super(message)
    this.name = "LoadFailure"
  }
}

export interface LoadInput {
  readonly entryPoint: string
  readonly projectDir: string
  /** When set, the buffer is materialized to an adjacent temp file and loaded
   *  from there so unsaved edits synthesize and `jiti`'s path cache never
   *  returns a stale module. */
  readonly documentText?: string
}

export type LoadOutcome =
  | { readonly ok: true; readonly node: ConstructNode }
  | { readonly ok: false; readonly error: LoadError }

function looksLikeNode(v: unknown): v is ConstructNode {
  return (
    !!v &&
    typeof v === "object" &&
    "id" in v &&
    "kind" in v &&
    "component" in v &&
    "children" in v
  )
}

/**
 * Resolve a module's `default` export to a ConstructNode across the supported
 * tiers: (1) already a node, (2) a function returning a node, (3) error.
 */
async function resolveDefault(def: unknown): Promise<ConstructNode> {
  if (def === undefined || def === null) {
    throw new LoadFailure(
      "no-default",
      "Pipeline module has no default export. Export a <Pipeline> (or a function returning one) as `default`.",
    )
  }
  if (looksLikeNode(def)) return def

  if (typeof def === "function") {
    let result: unknown
    try {
      result = await (def as (...args: unknown[]) => unknown)()
    } catch (err) {
      throw new LoadFailure(
        "not-a-node",
        `Default export is a function that threw when invoked with no arguments: ${errMessage(err)}. ` +
          "Provide a zero-argument wrapper that returns the <Pipeline>.",
      )
    }
    if (looksLikeNode(result)) return result
    throw new LoadFailure(
      "not-a-node",
      "Default export is a function but did not return a <Pipeline> ConstructNode.",
    )
  }

  throw new LoadFailure(
    "not-a-node",
    "Default export is neither a ConstructNode nor a function returning one.",
  )
}

function errMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}

/**
 * Load a pipeline entry into a ConstructNode.
 *
 * Resets the DSL node-id counter (in-realm) so IDs are deterministic, then
 * evaluates the module. When `documentText` is supplied, the buffer is written
 * to a content-hashed dotfile next to the entry (so `@/` and relative imports
 * resolve identically) and loaded from there; the temp file is always removed.
 */
export async function loadPipelineNode(input: LoadInput): Promise<LoadOutcome> {
  const jiti = getJiti(input.projectDir)
  let loadPath = input.entryPoint
  let tempPath: string | undefined

  try {
    // Reset BEFORE loading, in the realm the pipeline will use.
    await resetCounterInRealm(jiti)

    if (input.documentText != null) {
      const ext = extname(input.entryPoint) || ".tsx"
      const stem = basename(input.entryPoint, ext)
      const hash = createHash("sha1")
        .update(input.documentText)
        .digest("hex")
        .slice(0, 12)
      tempPath = join(
        dirname(input.entryPoint),
        `.__fr_lsp__.${stem}.${hash}${ext}`,
      )
      writeFileSync(tempPath, input.documentText, "utf-8")
      loadPath = tempPath
    }

    const mod = (await jiti.import(resolve(loadPath))) as Record<
      string,
      unknown
    >
    const node = await resolveDefault(mod.default)
    return { ok: true, node }
  } catch (err) {
    return { ok: false, error: toLoadError(err) }
  } finally {
    if (tempPath) {
      try {
        unlinkSync(tempPath)
      } catch {
        // best-effort cleanup; a leftover dotfile is harmless
      }
    }
  }
}

function toLoadError(err: unknown): LoadError {
  if (err instanceof LoadFailure) {
    return { kind: err.kind, message: err.message, stack: err.stack }
  }
  if (err instanceof Error) {
    return { kind: "eval", message: err.message, stack: err.stack }
  }
  return { kind: "eval", message: String(err) }
}
