// Package tap provides DB-backed storage for Tap pipeline manifests.
package tap

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/sandboxws/flink-reactor/apps/server/internal/storage"
	"github.com/sandboxws/flink-reactor/apps/server/internal/store"
)

// Metadata describes how to observe a single tapped operator's output stream.
type Metadata struct {
	NodeID              string            `json:"nodeId"`
	Name                string            `json:"name"`
	ComponentType       string            `json:"componentType"`
	ComponentName       string            `json:"componentName"`
	Schema              map[string]string `json:"schema"`
	ConnectorType       string            `json:"connectorType"`
	ObservationSQL      string            `json:"observationSql"`
	ConsumerGroupID     string            `json:"consumerGroupId"`
	Config              json.RawMessage   `json:"config"`
	ConnectorProperties map[string]string `json:"connectorProperties"`
}

// Manifest represents a tap manifest generated by the DSL's synth command.
type Manifest struct {
	PipelineName string     `json:"pipelineName"`
	FlinkVersion string     `json:"flinkVersion"`
	GeneratedAt  string     `json:"generatedAt"`
	Taps         []Metadata `json:"taps"`
}

// Store provides DB-backed access to tap manifests.
type Store struct {
	manifests *store.TapManifestStore
}

// NewStore creates a tap Store backed by the given TapManifestStore.
func NewStore(manifests *store.TapManifestStore) *Store {
	return &Store{manifests: manifests}
}

// ManifestByPipeline returns the manifest matching the given pipeline name.
// Returns nil if not found.
func (s *Store) ManifestByPipeline(ctx context.Context, pipelineName string) (*Manifest, error) {
	row, err := s.manifests.GetByPipeline(ctx, pipelineName)
	if err != nil {
		return nil, err
	}
	if row == nil {
		return nil, nil
	}
	return unmarshalManifest(row)
}

// Manifests returns all stored tap manifests.
func (s *Store) Manifests(ctx context.Context) ([]Manifest, error) {
	rows, err := s.manifests.List(ctx)
	if err != nil {
		return nil, err
	}

	manifests := make([]Manifest, 0, len(rows))
	for _, row := range rows {
		m, err := unmarshalManifest(&row)
		if err != nil {
			return nil, err
		}
		manifests = append(manifests, *m)
	}
	return manifests, nil
}

// Upsert stores a manifest in the database.
func (s *Store) Upsert(ctx context.Context, m Manifest) error {
	data, err := json.Marshal(m)
	if err != nil {
		return fmt.Errorf("marshal manifest: %w", err)
	}

	var flinkVersion *string
	if m.FlinkVersion != "" {
		flinkVersion = &m.FlinkVersion
	}

	return s.manifests.Upsert(ctx, storage.DBTapManifest{
		PipelineName: m.PipelineName,
		Manifest:     data,
		FlinkVersion: flinkVersion,
	})
}

// Delete removes a manifest by pipeline name. Returns true if deleted.
func (s *Store) Delete(ctx context.Context, pipelineName string) (bool, error) {
	return s.manifests.Delete(ctx, pipelineName)
}

// unmarshalManifest converts a DB row's JSONB manifest into a Manifest struct.
func unmarshalManifest(row *storage.DBTapManifest) (*Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(row.Manifest, &m); err != nil {
		return nil, fmt.Errorf("unmarshal manifest for %q: %w", row.PipelineName, err)
	}
	return &m, nil
}
